// <auto-generated>
//     Generated by tools/EConomic.SpecConverter (facade).
//     Regenerate after a spec refresh; do not edit by hand.
// </auto-generated>
#nullable enable

using EConomic.Pagination;
using EConomic.Querying;
using Generated = EConomic.Rest.Generated;

namespace EConomic.Rest
{

/// <summary>
/// A resource from <c>/accounting-years</c>.
/// </summary>
public sealed record AccountingYear
{
    /// <summary>The <c>fromDate</c> field.</summary>
    public DateOnly? FromDate { get; init; }

    /// <summary>The <c>toDate</c> field.</summary>
    public DateOnly? ToDate { get; init; }

    /// <summary>The <c>closed</c> field.</summary>
    public bool Closed { get; init; }

    /// <summary>The <c>year</c> field.</summary>
    public string? Year { get; init; }

    /// <summary>The <c>periods</c> field.</summary>
    public System.Uri? Periods { get; init; }

    /// <summary>The <c>entries</c> field.</summary>
    public System.Uri? Entries { get; init; }

    /// <summary>The <c>totals</c> field.</summary>
    public System.Uri? Totals { get; init; }

    /// <summary>The <c>vouchers</c> field.</summary>
    public System.Uri? Vouchers { get; init; }

    /// <summary>The <c>self</c> field.</summary>
    public required System.Uri Self { get; init; }
}

/// <summary>Fetches pages of <c>/accounting-years</c> and maps them to <see cref="AccountingYear"/>.</summary>
internal sealed class AccountingYearPageSource(Generated.AccountingYearsClient client)
    : IEconomicPageSource<AccountingYear>
{
    public async Task<EconomicPage<AccountingYear>> GetPageAsync(
        EconomicPageRequest request,
        CancellationToken cancellationToken)
    {
        var response = await FacadeTransport.SendAsync(
            () => client.GetAccountingYearsAsync(
                request.Filter, request.Sort, request.PageIndex, request.PageSize, cancellationToken),
            "GET /accounting-years").ConfigureAwait(false);

        var items = new List<AccountingYear>(response.Collection?.Count ?? 0);
        foreach (var item in response.Collection ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicPage<AccountingYear>(items, request.PageIndex, request.PageSize);
    }

    private static AccountingYear Map(Generated.AccountingYear source) => new()
    {
        FromDate = source.FromDate == default ? null : source.FromDate,
        ToDate = source.ToDate == default ? null : source.ToDate,
        Closed = source.Closed,
        Year = source.Year,
        Periods = source.Periods,
        Entries = source.Entries,
        Totals = source.Totals,
        Vouchers = source.Vouchers,
        Self = source.Self,
    };

    private static EconomicReference? Reference(int? number, System.Uri? self) =>
        number is null ? null : new EconomicReference(number.Value, self);
}

/// <summary>
/// A resource from <c>/accounts</c>.
/// </summary>
public sealed record Account
{
    /// <summary>The <c>accountNumber</c> field.</summary>
    public int AccountNumber { get; init; }

    /// <summary>The <c>accountType</c> field.</summary>
    public string? AccountType { get; init; }

    /// <summary>The <c>balance</c> field.</summary>
    public decimal Balance { get; init; }

    /// <summary>The <c>draftBalance</c> field.</summary>
    public decimal DraftBalance { get; init; }

    /// <summary>The <c>barred</c> field.</summary>
    public bool Barred { get; init; }

    /// <summary>The <c>blockDirectEntries</c> field.</summary>
    public bool BlockDirectEntries { get; init; }

    /// <summary>The <c>contraAccount</c> field.</summary>
    public EconomicReference? ContraAccount { get; init; }

    /// <summary>The <c>debitCredit</c> field.</summary>
    public string? DebitCredit { get; init; }

    /// <summary>The <c>name</c> field.</summary>
    public string? Name { get; init; }

    /// <summary>The <c>totalFromAccount</c> field.</summary>
    public EconomicReference? TotalFromAccount { get; init; }

    /// <summary>The <c>accountingYears</c> field.</summary>
    public System.Uri? AccountingYears { get; init; }

    /// <summary>The <c>self</c> field.</summary>
    public required System.Uri Self { get; init; }
}

/// <summary>Fetches pages of <c>/accounts</c> and maps them to <see cref="Account"/>.</summary>
internal sealed class AccountPageSource(Generated.AccountsClient client)
    : IEconomicPageSource<Account>
{
    public async Task<EconomicPage<Account>> GetPageAsync(
        EconomicPageRequest request,
        CancellationToken cancellationToken)
    {
        var response = await FacadeTransport.SendAsync(
            () => client.GetAccountsAsync(
                request.Filter, request.Sort, request.PageIndex, request.PageSize, cancellationToken),
            "GET /accounts").ConfigureAwait(false);

        var items = new List<Account>(response.Collection?.Count ?? 0);
        foreach (var item in response.Collection ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicPage<Account>(items, request.PageIndex, request.PageSize);
    }

    private static Account Map(Generated.Account source) => new()
    {
        AccountNumber = source.AccountNumber,
        AccountType = source.AccountType.ToString(),
        Balance = (decimal)source.Balance,
        DraftBalance = (decimal)source.DraftBalance,
        Barred = source.Barred,
        BlockDirectEntries = source.BlockDirectEntries,
        ContraAccount = Reference(source.ContraAccount?.AccountNumber, source.ContraAccount?.Self),
        DebitCredit = source.DebitCredit.ToString(),
        Name = source.Name,
        TotalFromAccount = Reference(source.TotalFromAccount?.AccountNumber, source.TotalFromAccount?.Self),
        AccountingYears = source.AccountingYears,
        Self = source.Self,
    };

    private static EconomicReference? Reference(int? number, System.Uri? self) =>
        number is null ? null : new EconomicReference(number.Value, self);
}

/// <summary>
/// A resource from <c>/app-roles</c>.
/// </summary>
public sealed record AppRole
{
    /// <summary>The <c>roleNumber</c> field.</summary>
    public int RoleNumber { get; init; }

    /// <summary>The <c>name</c> field.</summary>
    public string? Name { get; init; }
}

/// <summary>Fetches pages of <c>/app-roles</c> and maps them to <see cref="AppRole"/>.</summary>
internal sealed class AppRolePageSource(Generated.AppRolesClient client)
    : IEconomicPageSource<AppRole>
{
    public async Task<EconomicPage<AppRole>> GetPageAsync(
        EconomicPageRequest request,
        CancellationToken cancellationToken)
    {
        var response = await FacadeTransport.SendAsync(
            () => client.GetAppRolesAsync(
                request.Filter, request.Sort, request.PageIndex, request.PageSize, cancellationToken),
            "GET /app-roles").ConfigureAwait(false);

        var items = new List<AppRole>(response.Collection?.Count ?? 0);
        foreach (var item in response.Collection ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicPage<AppRole>(items, request.PageIndex, request.PageSize);
    }

    private static AppRole Map(Generated.AppRole source) => new()
    {
        RoleNumber = source.RoleNumber,
        Name = source.Name.ToString(),
    };

    private static EconomicReference? Reference(int? number, System.Uri? self) =>
        number is null ? null : new EconomicReference(number.Value, self);
}

/// <summary>
/// A resource from <c>/currencies</c>.
/// </summary>
public sealed record Currency
{
    /// <summary>The <c>name</c> field.</summary>
    public string? Name { get; init; }

    /// <summary>The <c>code</c> field.</summary>
    public string? Code { get; init; }

    /// <summary>The <c>isoNumber</c> field.</summary>
    public string? IsoNumber { get; init; }

    /// <summary>The <c>self</c> field.</summary>
    public required System.Uri Self { get; init; }
}

/// <summary>Fetches pages of <c>/currencies</c> and maps them to <see cref="Currency"/>.</summary>
internal sealed class CurrencyPageSource(Generated.CurrenciesClient client)
    : IEconomicPageSource<Currency>
{
    public async Task<EconomicPage<Currency>> GetPageAsync(
        EconomicPageRequest request,
        CancellationToken cancellationToken)
    {
        var response = await FacadeTransport.SendAsync(
            () => client.GetCurrenciesAsync(
                request.Filter, request.Sort, request.PageIndex, request.PageSize, cancellationToken),
            "GET /currencies").ConfigureAwait(false);

        var items = new List<Currency>(response.Collection?.Count ?? 0);
        foreach (var item in response.Collection ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicPage<Currency>(items, request.PageIndex, request.PageSize);
    }

    private static Currency Map(Generated.Currency source) => new()
    {
        Name = source.Name,
        Code = source.Code,
        IsoNumber = source.IsoNumber,
        Self = source.Self,
    };

    private static EconomicReference? Reference(int? number, System.Uri? self) =>
        number is null ? null : new EconomicReference(number.Value, self);
}

/// <summary>
/// A resource from <c>/customer-groups</c>.
/// </summary>
public sealed record CustomerGroup
{
    /// <summary>The <c>customerGroupNumber</c> field.</summary>
    public int CustomerGroupNumber { get; init; }

    /// <summary>The <c>name</c> field.</summary>
    public string? Name { get; init; }

    /// <summary>The <c>customers</c> field.</summary>
    public System.Uri? Customers { get; init; }

    /// <summary>The <c>self</c> field.</summary>
    public required System.Uri Self { get; init; }
}

/// <summary>Fetches pages of <c>/customer-groups</c> and maps them to <see cref="CustomerGroup"/>.</summary>
internal sealed class CustomerGroupPageSource(Generated.CustomerGroupsClient client)
    : IEconomicPageSource<CustomerGroup>
{
    public async Task<EconomicPage<CustomerGroup>> GetPageAsync(
        EconomicPageRequest request,
        CancellationToken cancellationToken)
    {
        var response = await FacadeTransport.SendAsync(
            () => client.GetCustomerGroupsAsync(
                request.Filter, request.Sort, request.PageIndex, request.PageSize, cancellationToken),
            "GET /customer-groups").ConfigureAwait(false);

        var items = new List<CustomerGroup>(response.Collection?.Count ?? 0);
        foreach (var item in response.Collection ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicPage<CustomerGroup>(items, request.PageIndex, request.PageSize);
    }

    private static CustomerGroup Map(Generated.CustomerGroup source) => new()
    {
        CustomerGroupNumber = source.CustomerGroupNumber,
        Name = source.Name,
        Customers = source.Customers,
        Self = source.Self,
    };

    private static EconomicReference? Reference(int? number, System.Uri? self) =>
        number is null ? null : new EconomicReference(number.Value, self);
}

/// <summary>
/// A resource from <c>/customers</c>.
/// </summary>
public sealed record Customer
{
    /// <summary>The <c>address</c> field.</summary>
    public string? Address { get; init; }

    /// <summary>The <c>balance</c> field.</summary>
    public decimal Balance { get; init; }

    /// <summary>The <c>barred</c> field.</summary>
    public bool Barred { get; init; }

    /// <summary>The <c>city</c> field.</summary>
    public string? City { get; init; }

    /// <summary>The <c>corporateIdentificationNumber</c> field.</summary>
    public string? CorporateIdentificationNumber { get; init; }

    /// <summary>The <c>pNumber</c> field.</summary>
    public string? PNumber { get; init; }

    /// <summary>The <c>country</c> field.</summary>
    public string? Country { get; init; }

    /// <summary>The <c>creditLimit</c> field.</summary>
    public decimal CreditLimit { get; init; }

    /// <summary>The <c>currency</c> field.</summary>
    public required string Currency { get; init; }

    /// <summary>The <c>customerNumber</c> field.</summary>
    public int CustomerNumber { get; init; }

    /// <summary>The <c>dueAmount</c> field.</summary>
    public decimal DueAmount { get; init; }

    /// <summary>The <c>ean</c> field.</summary>
    public string? Ean { get; init; }

    /// <summary>The <c>email</c> field.</summary>
    public string? Email { get; init; }

    /// <summary>The <c>lastUpdated</c> field.</summary>
    public DateTimeOffset? LastUpdated { get; init; }

    /// <summary>The <c>name</c> field.</summary>
    public required string Name { get; init; }

    /// <summary>The <c>publicEntryNumber</c> field.</summary>
    public string? PublicEntryNumber { get; init; }

    /// <summary>The <c>telephoneAndFaxNumber</c> field.</summary>
    public string? TelephoneAndFaxNumber { get; init; }

    /// <summary>The <c>mobilePhone</c> field.</summary>
    public string? MobilePhone { get; init; }

    /// <summary>The <c>eInvoicingDisabledByDefault</c> field.</summary>
    public bool EInvoicingDisabledByDefault { get; init; }

    /// <summary>The <c>vatNumber</c> field.</summary>
    public string? VatNumber { get; init; }

    /// <summary>The <c>website</c> field.</summary>
    public string? Website { get; init; }

    /// <summary>The <c>zip</c> field.</summary>
    public string? Zip { get; init; }

    /// <summary>The <c>contacts</c> field.</summary>
    public System.Uri? Contacts { get; init; }

    /// <summary>The <c>deliveryLocations</c> field.</summary>
    public System.Uri? DeliveryLocations { get; init; }

    /// <summary>The <c>defaultDeliveryLocation</c> field.</summary>
    public EconomicReference? DefaultDeliveryLocation { get; init; }

    /// <summary>The <c>attention</c> field.</summary>
    public EconomicReference? Attention { get; init; }

    /// <summary>The <c>customerContact</c> field.</summary>
    public EconomicReference? CustomerContact { get; init; }

    /// <summary>The <c>customerGroup</c> field.</summary>
    public EconomicReference? CustomerGroup { get; init; }

    /// <summary>The <c>layout</c> field.</summary>
    public EconomicReference? Layout { get; init; }

    /// <summary>The <c>paymentTerms</c> field.</summary>
    public EconomicReference? PaymentTerms { get; init; }

    /// <summary>The <c>salesPerson</c> field.</summary>
    public EconomicReference? SalesPerson { get; init; }

    /// <summary>The <c>vatZone</c> field.</summary>
    public EconomicReference? VatZone { get; init; }

    /// <summary>The <c>self</c> field.</summary>
    public required System.Uri Self { get; init; }
}

/// <summary>Fetches pages of <c>/customers</c> and maps them to <see cref="Customer"/>.</summary>
internal sealed class CustomerPageSource(Generated.CustomersClient client)
    : IEconomicPageSource<Customer>
{
    public async Task<EconomicPage<Customer>> GetPageAsync(
        EconomicPageRequest request,
        CancellationToken cancellationToken)
    {
        var response = await FacadeTransport.SendAsync(
            () => client.GetCustomersAsync(
                request.Filter, request.Sort, request.PageIndex, request.PageSize, cancellationToken),
            "GET /customers").ConfigureAwait(false);

        var items = new List<Customer>(response.Collection?.Count ?? 0);
        foreach (var item in response.Collection ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicPage<Customer>(items, request.PageIndex, request.PageSize);
    }

    private static Customer Map(Generated.Customer source) => new()
    {
        Address = source.Address,
        Balance = (decimal)source.Balance,
        Barred = source.Barred,
        City = source.City,
        CorporateIdentificationNumber = source.CorporateIdentificationNumber,
        PNumber = source.PNumber,
        Country = source.Country,
        CreditLimit = (decimal)source.CreditLimit,
        Currency = source.Currency ?? string.Empty,
        CustomerNumber = source.CustomerNumber,
        DueAmount = (decimal)source.DueAmount,
        Ean = source.Ean,
        Email = source.Email,
        LastUpdated = source.LastUpdated == default ? null : source.LastUpdated,
        Name = source.Name ?? string.Empty,
        PublicEntryNumber = source.PublicEntryNumber,
        TelephoneAndFaxNumber = source.TelephoneAndFaxNumber,
        MobilePhone = source.MobilePhone,
        EInvoicingDisabledByDefault = source.EInvoicingDisabledByDefault,
        VatNumber = source.VatNumber,
        Website = source.Website,
        Zip = source.Zip,
        Contacts = source.Contacts,
        DeliveryLocations = source.DeliveryLocations,
        DefaultDeliveryLocation = Reference(source.DefaultDeliveryLocation?.DeliveryLocationNumber, source.DefaultDeliveryLocation?.Self),
        Attention = Reference(source.Attention?.CustomerContactNumber, source.Attention?.Self),
        CustomerContact = Reference(source.CustomerContact?.CustomerContactNumber, source.CustomerContact?.Self),
        CustomerGroup = Reference(source.CustomerGroup?.CustomerGroupNumber, source.CustomerGroup?.Self),
        Layout = Reference(source.Layout?.LayoutNumber, source.Layout?.Self),
        PaymentTerms = Reference(source.PaymentTerms?.PaymentTermsNumber, source.PaymentTerms?.Self),
        SalesPerson = Reference(source.SalesPerson?.EmployeeNumber, source.SalesPerson?.Self),
        VatZone = Reference(source.VatZone?.VatZoneNumber, source.VatZone?.Self),
        Self = source.Self,
    };

    private static EconomicReference? Reference(int? number, System.Uri? self) =>
        number is null ? null : new EconomicReference(number.Value, self);
}

/// <summary>
/// A resource from <c>/departmental-distributions</c>.
/// </summary>
public sealed record DepartmentalDistributionSummary
{
    /// <summary>The <c>departmentalDistributionNumber</c> field.</summary>
    public int DepartmentalDistributionNumber { get; init; }

    /// <summary>The <c>name</c> field.</summary>
    public string? Name { get; init; }

    /// <summary>The <c>distributionType</c> field.</summary>
    public string? DistributionType { get; init; }

    /// <summary>The <c>self</c> field.</summary>
    public required System.Uri Self { get; init; }
}

/// <summary>Fetches pages of <c>/departmental-distributions</c> and maps them to <see cref="DepartmentalDistributionSummary"/>.</summary>
internal sealed class DepartmentalDistributionSummaryPageSource(Generated.DepartmentalDistributionsClient client)
    : IEconomicPageSource<DepartmentalDistributionSummary>
{
    public async Task<EconomicPage<DepartmentalDistributionSummary>> GetPageAsync(
        EconomicPageRequest request,
        CancellationToken cancellationToken)
    {
        var response = await FacadeTransport.SendAsync(
            () => client.GetDepartmentalDistributionsAsync(
                request.Filter, request.Sort, request.PageIndex, request.PageSize, cancellationToken),
            "GET /departmental-distributions").ConfigureAwait(false);

        var items = new List<DepartmentalDistributionSummary>(response.Collection?.Count ?? 0);
        foreach (var item in response.Collection ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicPage<DepartmentalDistributionSummary>(items, request.PageIndex, request.PageSize);
    }

    private static DepartmentalDistributionSummary Map(Generated.DepartmentalDistributionSummary source) => new()
    {
        DepartmentalDistributionNumber = source.DepartmentalDistributionNumber,
        Name = source.Name,
        DistributionType = source.DistributionType.ToString(),
        Self = source.Self,
    };

    private static EconomicReference? Reference(int? number, System.Uri? self) =>
        number is null ? null : new EconomicReference(number.Value, self);
}

/// <summary>
/// A resource from <c>/departments</c>.
/// </summary>
public sealed record Department
{
    /// <summary>The <c>departmentNumber</c> field.</summary>
    public int DepartmentNumber { get; init; }

    /// <summary>The <c>name</c> field.</summary>
    public required string Name { get; init; }

    /// <summary>The <c>barred</c> field.</summary>
    public bool Barred { get; init; }

    /// <summary>The <c>self</c> field.</summary>
    public required System.Uri Self { get; init; }
}

/// <summary>Fetches pages of <c>/departments</c> and maps them to <see cref="Department"/>.</summary>
internal sealed class DepartmentPageSource(Generated.DepartmentsClient client)
    : IEconomicPageSource<Department>
{
    public async Task<EconomicPage<Department>> GetPageAsync(
        EconomicPageRequest request,
        CancellationToken cancellationToken)
    {
        var response = await FacadeTransport.SendAsync(
            () => client.GetDepartmentsAsync(
                request.Filter, request.Sort, request.PageIndex, request.PageSize, cancellationToken),
            "GET /departments").ConfigureAwait(false);

        var items = new List<Department>(response.Collection?.Count ?? 0);
        foreach (var item in response.Collection ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicPage<Department>(items, request.PageIndex, request.PageSize);
    }

    private static Department Map(Generated.Department source) => new()
    {
        DepartmentNumber = source.DepartmentNumber,
        Name = source.Name ?? string.Empty,
        Barred = source.Barred,
        Self = source.Self,
    };

    private static EconomicReference? Reference(int? number, System.Uri? self) =>
        number is null ? null : new EconomicReference(number.Value, self);
}

/// <summary>
/// A resource from <c>/employees</c>.
/// </summary>
public sealed record Employee
{
    /// <summary>The <c>employeeNumber</c> field.</summary>
    public int EmployeeNumber { get; init; }

    /// <summary>The <c>employeeGroup</c> field.</summary>
    public EconomicReference? EmployeeGroup { get; init; }

    /// <summary>The <c>name</c> field.</summary>
    public string? Name { get; init; }

    /// <summary>The <c>customers</c> field.</summary>
    public System.Uri? Customers { get; init; }

    /// <summary>The <c>draftInvoices</c> field.</summary>
    public System.Uri? DraftInvoices { get; init; }

    /// <summary>The <c>bookedInvoices</c> field.</summary>
    public System.Uri? BookedInvoices { get; init; }

    /// <summary>The <c>email</c> field.</summary>
    public string? Email { get; init; }

    /// <summary>The <c>phone</c> field.</summary>
    public string? Phone { get; init; }

    /// <summary>The <c>barred</c> field.</summary>
    public bool Barred { get; init; }

    /// <summary>The <c>self</c> field.</summary>
    public required System.Uri Self { get; init; }
}

/// <summary>Fetches pages of <c>/employees</c> and maps them to <see cref="Employee"/>.</summary>
internal sealed class EmployeePageSource(Generated.EmployeesClient client)
    : IEconomicPageSource<Employee>
{
    public async Task<EconomicPage<Employee>> GetPageAsync(
        EconomicPageRequest request,
        CancellationToken cancellationToken)
    {
        var response = await FacadeTransport.SendAsync(
            () => client.GetEmployeesAsync(
                request.Filter, request.Sort, request.PageIndex, request.PageSize, cancellationToken),
            "GET /employees").ConfigureAwait(false);

        var items = new List<Employee>(response.Collection?.Count ?? 0);
        foreach (var item in response.Collection ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicPage<Employee>(items, request.PageIndex, request.PageSize);
    }

    private static Employee Map(Generated.Employee source) => new()
    {
        EmployeeNumber = source.EmployeeNumber,
        EmployeeGroup = Reference(source.EmployeeGroup?.EmployeeGroupNumber, source.EmployeeGroup?.Self),
        Name = source.Name,
        Customers = source.Customers,
        DraftInvoices = source.DraftInvoices,
        BookedInvoices = source.BookedInvoices,
        Email = source.Email,
        Phone = source.Phone,
        Barred = source.Barred,
        Self = source.Self,
    };

    private static EconomicReference? Reference(int? number, System.Uri? self) =>
        number is null ? null : new EconomicReference(number.Value, self);
}

/// <summary>
/// A resource from <c>/journals</c>.
/// </summary>
public sealed record Journal
{
    /// <summary>The <c>name</c> field.</summary>
    public string? Name { get; init; }

    /// <summary>The <c>vouchers</c> field.</summary>
    public System.Uri? Vouchers { get; init; }

    /// <summary>The <c>entries</c> field.</summary>
    public System.Uri? Entries { get; init; }

    /// <summary>The <c>journalNumber</c> field.</summary>
    public int JournalNumber { get; init; }

    /// <summary>The <c>self</c> field.</summary>
    public required System.Uri Self { get; init; }
}

/// <summary>Fetches pages of <c>/journals</c> and maps them to <see cref="Journal"/>.</summary>
internal sealed class JournalPageSource(Generated.JournalsClient client)
    : IEconomicPageSource<Journal>
{
    public async Task<EconomicPage<Journal>> GetPageAsync(
        EconomicPageRequest request,
        CancellationToken cancellationToken)
    {
        var response = await FacadeTransport.SendAsync(
            () => client.GetJournalsAsync(
                request.Filter, request.Sort, request.PageIndex, request.PageSize, cancellationToken),
            "GET /journals").ConfigureAwait(false);

        var items = new List<Journal>(response.Collection?.Count ?? 0);
        foreach (var item in response.Collection ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicPage<Journal>(items, request.PageIndex, request.PageSize);
    }

    private static Journal Map(Generated.Journal source) => new()
    {
        Name = source.Name,
        Vouchers = source.Vouchers,
        Entries = source.Entries,
        JournalNumber = source.JournalNumber,
        Self = source.Self,
    };

    private static EconomicReference? Reference(int? number, System.Uri? self) =>
        number is null ? null : new EconomicReference(number.Value, self);
}

/// <summary>
/// A resource from <c>/layouts</c>.
/// </summary>
public sealed record Layout
{
    /// <summary>The <c>layoutNumber</c> field.</summary>
    public int LayoutNumber { get; init; }

    /// <summary>The <c>name</c> field.</summary>
    public string? Name { get; init; }

    /// <summary>The <c>deleted</c> field.</summary>
    public bool Deleted { get; init; }

    /// <summary>The <c>self</c> field.</summary>
    public required System.Uri Self { get; init; }
}

/// <summary>Fetches pages of <c>/layouts</c> and maps them to <see cref="Layout"/>.</summary>
internal sealed class LayoutPageSource(Generated.LayoutsClient client)
    : IEconomicPageSource<Layout>
{
    public async Task<EconomicPage<Layout>> GetPageAsync(
        EconomicPageRequest request,
        CancellationToken cancellationToken)
    {
        var response = await FacadeTransport.SendAsync(
            () => client.GetLayoutsAsync(
                request.Filter, request.Sort, request.PageIndex, request.PageSize, cancellationToken),
            "GET /layouts").ConfigureAwait(false);

        var items = new List<Layout>(response.Collection?.Count ?? 0);
        foreach (var item in response.Collection ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicPage<Layout>(items, request.PageIndex, request.PageSize);
    }

    private static Layout Map(Generated.Layout source) => new()
    {
        LayoutNumber = source.LayoutNumber,
        Name = source.Name,
        Deleted = source.Deleted,
        Self = source.Self,
    };

    private static EconomicReference? Reference(int? number, System.Uri? self) =>
        number is null ? null : new EconomicReference(number.Value, self);
}

/// <summary>
/// A resource from <c>/payment-terms</c>.
/// </summary>
public sealed record PaymentTerms
{
    /// <summary>The <c>paymentTermsNumber</c> field.</summary>
    public int PaymentTermsNumber { get; init; }

    /// <summary>The <c>daysOfCredit</c> field.</summary>
    public int DaysOfCredit { get; init; }

    /// <summary>The <c>description</c> field.</summary>
    public string? Description { get; init; }

    /// <summary>The <c>name</c> field.</summary>
    public string? Name { get; init; }

    /// <summary>The <c>paymentTermsType</c> field.</summary>
    public string? PaymentTermsType { get; init; }

    /// <summary>The <c>contraAccountForPrepaidAmount</c> field.</summary>
    public EconomicReference? ContraAccountForPrepaidAmount { get; init; }

    /// <summary>The <c>contraAccountForRemainderAmount</c> field.</summary>
    public EconomicReference? ContraAccountForRemainderAmount { get; init; }

    /// <summary>The <c>percentageForPrepaidAmount</c> field.</summary>
    public decimal PercentageForPrepaidAmount { get; init; }

    /// <summary>The <c>percentageForRemainderAmount</c> field.</summary>
    public decimal PercentageForRemainderAmount { get; init; }

    /// <summary>The <c>creditCardCompany</c> field.</summary>
    public EconomicReference? CreditCardCompany { get; init; }

    /// <summary>The <c>self</c> field.</summary>
    public required System.Uri Self { get; init; }
}

/// <summary>Fetches pages of <c>/payment-terms</c> and maps them to <see cref="PaymentTerms"/>.</summary>
internal sealed class PaymentTermsPageSource(Generated.PaymentTermsClient client)
    : IEconomicPageSource<PaymentTerms>
{
    public async Task<EconomicPage<PaymentTerms>> GetPageAsync(
        EconomicPageRequest request,
        CancellationToken cancellationToken)
    {
        var response = await FacadeTransport.SendAsync(
            () => client.GetPaymentTermsAsync(
                request.Filter, request.Sort, request.PageIndex, request.PageSize, cancellationToken),
            "GET /payment-terms").ConfigureAwait(false);

        var items = new List<PaymentTerms>(response.Collection?.Count ?? 0);
        foreach (var item in response.Collection ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicPage<PaymentTerms>(items, request.PageIndex, request.PageSize);
    }

    private static PaymentTerms Map(Generated.PaymentTerms source) => new()
    {
        PaymentTermsNumber = source.PaymentTermsNumber,
        DaysOfCredit = source.DaysOfCredit,
        Description = source.Description,
        Name = source.Name,
        PaymentTermsType = source.PaymentTermsType.ToString(),
        ContraAccountForPrepaidAmount = Reference(source.ContraAccountForPrepaidAmount?.AccountNumber, source.ContraAccountForPrepaidAmount?.Self),
        ContraAccountForRemainderAmount = Reference(source.ContraAccountForRemainderAmount?.AccountNumber, source.ContraAccountForRemainderAmount?.Self),
        PercentageForPrepaidAmount = (decimal)source.PercentageForPrepaidAmount,
        PercentageForRemainderAmount = (decimal)source.PercentageForRemainderAmount,
        CreditCardCompany = Reference(source.CreditCardCompany?.CustomerNumber, source.CreditCardCompany?.Self),
        Self = source.Self,
    };

    private static EconomicReference? Reference(int? number, System.Uri? self) =>
        number is null ? null : new EconomicReference(number.Value, self);
}

/// <summary>
/// A resource from <c>/payment-types</c>.
/// </summary>
public sealed record PaymentType
{
    /// <summary>The <c>paymentTypeNumber</c> field.</summary>
    public int PaymentTypeNumber { get; init; }

    /// <summary>The <c>name</c> field.</summary>
    public required string Name { get; init; }

    /// <summary>The <c>self</c> field.</summary>
    public required System.Uri Self { get; init; }
}

/// <summary>Fetches pages of <c>/payment-types</c> and maps them to <see cref="PaymentType"/>.</summary>
internal sealed class PaymentTypePageSource(Generated.PaymentTypesClient client)
    : IEconomicPageSource<PaymentType>
{
    public async Task<EconomicPage<PaymentType>> GetPageAsync(
        EconomicPageRequest request,
        CancellationToken cancellationToken)
    {
        var response = await FacadeTransport.SendAsync(
            () => client.GetPaymentTypesAsync(
                request.Filter, request.Sort, request.PageIndex, request.PageSize, cancellationToken),
            "GET /payment-types").ConfigureAwait(false);

        var items = new List<PaymentType>(response.Collection?.Count ?? 0);
        foreach (var item in response.Collection ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicPage<PaymentType>(items, request.PageIndex, request.PageSize);
    }

    private static PaymentType Map(Generated.PaymentType source) => new()
    {
        PaymentTypeNumber = source.PaymentTypeNumber,
        Name = source.Name ?? string.Empty,
        Self = source.Self,
    };

    private static EconomicReference? Reference(int? number, System.Uri? self) =>
        number is null ? null : new EconomicReference(number.Value, self);
}

/// <summary>
/// A resource from <c>/product-groups</c>.
/// </summary>
public sealed record ProductGroup
{
    /// <summary>The <c>productGroupNumber</c> field.</summary>
    public int ProductGroupNumber { get; init; }

    /// <summary>The <c>name</c> field.</summary>
    public string? Name { get; init; }

    /// <summary>The <c>salesAccounts</c> field.</summary>
    public System.Uri? SalesAccounts { get; init; }

    /// <summary>The <c>products</c> field.</summary>
    public System.Uri? Products { get; init; }

    /// <summary>The <c>inventoryEnabled</c> field.</summary>
    public bool InventoryEnabled { get; init; }

    /// <summary>The <c>self</c> field.</summary>
    public required System.Uri Self { get; init; }
}

/// <summary>Fetches pages of <c>/product-groups</c> and maps them to <see cref="ProductGroup"/>.</summary>
internal sealed class ProductGroupPageSource(Generated.ProductGroupsClient client)
    : IEconomicPageSource<ProductGroup>
{
    public async Task<EconomicPage<ProductGroup>> GetPageAsync(
        EconomicPageRequest request,
        CancellationToken cancellationToken)
    {
        var response = await FacadeTransport.SendAsync(
            () => client.GetProductGroupsAsync(
                request.Filter, request.Sort, request.PageIndex, request.PageSize, cancellationToken),
            "GET /product-groups").ConfigureAwait(false);

        var items = new List<ProductGroup>(response.Collection?.Count ?? 0);
        foreach (var item in response.Collection ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicPage<ProductGroup>(items, request.PageIndex, request.PageSize);
    }

    private static ProductGroup Map(Generated.ProductGroup source) => new()
    {
        ProductGroupNumber = source.ProductGroupNumber,
        Name = source.Name,
        SalesAccounts = source.SalesAccounts,
        Products = source.Products,
        InventoryEnabled = source.InventoryEnabled,
        Self = source.Self,
    };

    private static EconomicReference? Reference(int? number, System.Uri? self) =>
        number is null ? null : new EconomicReference(number.Value, self);
}

/// <summary>
/// A resource from <c>/products</c>.
/// </summary>
public sealed record Product
{
    /// <summary>The <c>productNumber</c> field.</summary>
    public required string ProductNumber { get; init; }

    /// <summary>The <c>description</c> field.</summary>
    public string? Description { get; init; }

    /// <summary>The <c>name</c> field.</summary>
    public required string Name { get; init; }

    /// <summary>The <c>costPrice</c> field.</summary>
    public decimal CostPrice { get; init; }

    /// <summary>The <c>recommendedPrice</c> field.</summary>
    public decimal RecommendedPrice { get; init; }

    /// <summary>The <c>salesPrice</c> field.</summary>
    public decimal SalesPrice { get; init; }

    /// <summary>The <c>barCode</c> field.</summary>
    public string? BarCode { get; init; }

    /// <summary>The <c>barred</c> field.</summary>
    public bool Barred { get; init; }

    /// <summary>The <c>lastUpdated</c> field.</summary>
    public DateTimeOffset? LastUpdated { get; init; }

    /// <summary>The <c>unit</c> field.</summary>
    public EconomicReference? Unit { get; init; }

    /// <summary>The <c>departmentalDistribution</c> field.</summary>
    public EconomicReference? DepartmentalDistribution { get; init; }

    /// <summary>The <c>self</c> field.</summary>
    public required System.Uri Self { get; init; }
}

/// <summary>Fetches pages of <c>/products</c> and maps them to <see cref="Product"/>.</summary>
internal sealed class ProductPageSource(Generated.ProductsClient client)
    : IEconomicPageSource<Product>
{
    public async Task<EconomicPage<Product>> GetPageAsync(
        EconomicPageRequest request,
        CancellationToken cancellationToken)
    {
        var response = await FacadeTransport.SendAsync(
            () => client.GetProductsAsync(
                request.Filter, request.Sort, request.PageIndex, request.PageSize, cancellationToken),
            "GET /products").ConfigureAwait(false);

        var items = new List<Product>(response.Collection?.Count ?? 0);
        foreach (var item in response.Collection ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicPage<Product>(items, request.PageIndex, request.PageSize);
    }

    private static Product Map(Generated.Product source) => new()
    {
        ProductNumber = source.ProductNumber ?? string.Empty,
        Description = source.Description,
        Name = source.Name ?? string.Empty,
        CostPrice = (decimal)source.CostPrice,
        RecommendedPrice = (decimal)source.RecommendedPrice,
        SalesPrice = (decimal)source.SalesPrice,
        BarCode = source.BarCode,
        Barred = source.Barred,
        LastUpdated = source.LastUpdated == default ? null : source.LastUpdated,
        Unit = Reference(source.Unit?.UnitNumber, source.Unit?.Self),
        DepartmentalDistribution = Reference(source.DepartmentalDistribution?.DepartmentalDistributionNumber, source.DepartmentalDistribution?.Self),
        Self = source.Self,
    };

    private static EconomicReference? Reference(int? number, System.Uri? self) =>
        number is null ? null : new EconomicReference(number.Value, self);
}

/// <summary>
/// A resource from <c>/suppliers</c>.
/// </summary>
public sealed record Supplier
{
    /// <summary>The <c>address</c> field.</summary>
    public string? Address { get; init; }

    /// <summary>The <c>attention</c> field.</summary>
    public EconomicReference? Attention { get; init; }

    /// <summary>The <c>bankAccount</c> field.</summary>
    public string? BankAccount { get; init; }

    /// <summary>The <c>barred</c> field.</summary>
    public bool Barred { get; init; }

    /// <summary>The <c>city</c> field.</summary>
    public string? City { get; init; }

    /// <summary>The <c>contacts</c> field.</summary>
    public System.Uri? Contacts { get; init; }

    /// <summary>The <c>corporateIdentificationNumber</c> field.</summary>
    public string? CorporateIdentificationNumber { get; init; }

    /// <summary>The <c>costAccount</c> field.</summary>
    public EconomicReference? CostAccount { get; init; }

    /// <summary>The <c>country</c> field.</summary>
    public string? Country { get; init; }

    /// <summary>The <c>currency</c> field.</summary>
    public required string Currency { get; init; }

    /// <summary>The <c>defaultInvoiceText</c> field.</summary>
    public string? DefaultInvoiceText { get; init; }

    /// <summary>The <c>email</c> field.</summary>
    public string? Email { get; init; }

    /// <summary>The <c>layout</c> field.</summary>
    public EconomicReference? Layout { get; init; }

    /// <summary>The <c>name</c> field.</summary>
    public string? Name { get; init; }

    /// <summary>The <c>paymentTerms</c> field.</summary>
    public EconomicReference? PaymentTerms { get; init; }

    /// <summary>The <c>phone</c> field.</summary>
    public string? Phone { get; init; }

    /// <summary>The <c>salesPerson</c> field.</summary>
    public EconomicReference? SalesPerson { get; init; }

    /// <summary>The <c>supplierContact</c> field.</summary>
    public EconomicReference? SupplierContact { get; init; }

    /// <summary>The <c>supplierGroup</c> field.</summary>
    public EconomicReference? SupplierGroup { get; init; }

    /// <summary>The <c>supplierNumber</c> field.</summary>
    public int SupplierNumber { get; init; }

    /// <summary>The <c>vatZone</c> field.</summary>
    public EconomicReference? VatZone { get; init; }

    /// <summary>The <c>zip</c> field.</summary>
    public string? Zip { get; init; }

    /// <summary>The <c>self</c> field.</summary>
    public string? Self { get; init; }
}

/// <summary>Fetches pages of <c>/suppliers</c> and maps them to <see cref="Supplier"/>.</summary>
internal sealed class SupplierPageSource(Generated.SuppliersClient client)
    : IEconomicPageSource<Supplier>
{
    public async Task<EconomicPage<Supplier>> GetPageAsync(
        EconomicPageRequest request,
        CancellationToken cancellationToken)
    {
        var response = await FacadeTransport.SendAsync(
            () => client.GetSuppliersAsync(
                request.Filter, request.Sort, request.PageIndex, request.PageSize, cancellationToken),
            "GET /suppliers").ConfigureAwait(false);

        var items = new List<Supplier>(response.Collection?.Count ?? 0);
        foreach (var item in response.Collection ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicPage<Supplier>(items, request.PageIndex, request.PageSize);
    }

    private static Supplier Map(Generated.Supplier source) => new()
    {
        Address = source.Address,
        Attention = Reference(source.Attention?.SupplierContactNumber, source.Attention?.Self),
        BankAccount = source.BankAccount,
        Barred = source.Barred,
        City = source.City,
        Contacts = source.Contacts,
        CorporateIdentificationNumber = source.CorporateIdentificationNumber,
        CostAccount = Reference(source.CostAccount?.AccountNumber, source.CostAccount?.Self),
        Country = source.Country,
        Currency = source.Currency ?? string.Empty,
        DefaultInvoiceText = source.DefaultInvoiceText,
        Email = source.Email,
        Layout = Reference(source.Layout?.LayoutNumber, source.Layout?.Self),
        Name = source.Name,
        PaymentTerms = Reference(source.PaymentTerms?.PaymentTermsNumber, source.PaymentTerms?.Self),
        Phone = source.Phone,
        SalesPerson = Reference(source.SalesPerson?.EmployeeNumber, source.SalesPerson?.Self),
        SupplierContact = Reference(source.SupplierContact?.SupplierContactNumber, source.SupplierContact?.Self),
        SupplierGroup = Reference(source.SupplierGroup?.SupplierGroupNumber, source.SupplierGroup?.Self),
        SupplierNumber = source.SupplierNumber,
        VatZone = Reference(source.VatZone?.VatZoneNumber, source.VatZone?.Self),
        Zip = source.Zip,
        Self = source.Self,
    };

    private static EconomicReference? Reference(int? number, System.Uri? self) =>
        number is null ? null : new EconomicReference(number.Value, self);
}

/// <summary>
/// A resource from <c>/units</c>.
/// </summary>
public sealed record Unit
{
    /// <summary>The <c>unitNumber</c> field.</summary>
    public int UnitNumber { get; init; }

    /// <summary>The <c>name</c> field.</summary>
    public string? Name { get; init; }

    /// <summary>The <c>self</c> field.</summary>
    public required System.Uri Self { get; init; }
}

/// <summary>Fetches pages of <c>/units</c> and maps them to <see cref="Unit"/>.</summary>
internal sealed class UnitPageSource(Generated.UnitsClient client)
    : IEconomicPageSource<Unit>
{
    public async Task<EconomicPage<Unit>> GetPageAsync(
        EconomicPageRequest request,
        CancellationToken cancellationToken)
    {
        var response = await FacadeTransport.SendAsync(
            () => client.GetUnitsAsync(
                request.Filter, request.Sort, request.PageIndex, request.PageSize, cancellationToken),
            "GET /units").ConfigureAwait(false);

        var items = new List<Unit>(response.Collection?.Count ?? 0);
        foreach (var item in response.Collection ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicPage<Unit>(items, request.PageIndex, request.PageSize);
    }

    private static Unit Map(Generated.Unit source) => new()
    {
        UnitNumber = source.UnitNumber,
        Name = source.Name,
        Self = source.Self,
    };

    private static EconomicReference? Reference(int? number, System.Uri? self) =>
        number is null ? null : new EconomicReference(number.Value, self);
}

/// <summary>
/// A resource from <c>/vat-accounts</c>.
/// </summary>
public sealed record VatAccount
{
    /// <summary>The <c>account</c> field.</summary>
    public EconomicReference? Account { get; init; }

    /// <summary>The <c>contraAccount</c> field.</summary>
    public EconomicReference? ContraAccount { get; init; }

    /// <summary>The <c>vatType</c> field.</summary>
    public EconomicReference? VatType { get; init; }

    /// <summary>The <c>barred</c> field.</summary>
    public bool Barred { get; init; }

    /// <summary>The <c>name</c> field.</summary>
    public string? Name { get; init; }

    /// <summary>The <c>ratePercentage</c> field.</summary>
    public decimal RatePercentage { get; init; }

    /// <summary>The <c>vatCode</c> field.</summary>
    public string? VatCode { get; init; }

    /// <summary>The <c>self</c> field.</summary>
    public required System.Uri Self { get; init; }
}

/// <summary>Fetches pages of <c>/vat-accounts</c> and maps them to <see cref="VatAccount"/>.</summary>
internal sealed class VatAccountPageSource(Generated.VatAccountsClient client)
    : IEconomicPageSource<VatAccount>
{
    public async Task<EconomicPage<VatAccount>> GetPageAsync(
        EconomicPageRequest request,
        CancellationToken cancellationToken)
    {
        var response = await FacadeTransport.SendAsync(
            () => client.GetVatAccountsAsync(
                request.Filter, request.Sort, request.PageIndex, request.PageSize, cancellationToken),
            "GET /vat-accounts").ConfigureAwait(false);

        var items = new List<VatAccount>(response.Collection?.Count ?? 0);
        foreach (var item in response.Collection ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicPage<VatAccount>(items, request.PageIndex, request.PageSize);
    }

    private static VatAccount Map(Generated.VatAccount source) => new()
    {
        Account = Reference(source.Account?.AccountNumber, source.Account?.Self),
        ContraAccount = Reference(source.ContraAccount?.AccountNumber, source.ContraAccount?.Self),
        VatType = Reference(source.VatType?.VatTypeNumber, source.VatType?.Self),
        Barred = source.Barred,
        Name = source.Name,
        RatePercentage = (decimal)source.RatePercentage,
        VatCode = source.VatCode,
        Self = source.Self,
    };

    private static EconomicReference? Reference(int? number, System.Uri? self) =>
        number is null ? null : new EconomicReference(number.Value, self);
}

/// <summary>
/// A resource from <c>/vat-types</c>.
/// </summary>
public sealed record VatType
{
    /// <summary>The <c>vatTypeNumber</c> field.</summary>
    public int VatTypeNumber { get; init; }

    /// <summary>The <c>name</c> field.</summary>
    public required string Name { get; init; }

    /// <summary>The <c>self</c> field.</summary>
    public required System.Uri Self { get; init; }
}

/// <summary>Fetches pages of <c>/vat-types</c> and maps them to <see cref="VatType"/>.</summary>
internal sealed class VatTypePageSource(Generated.VatTypesClient client)
    : IEconomicPageSource<VatType>
{
    public async Task<EconomicPage<VatType>> GetPageAsync(
        EconomicPageRequest request,
        CancellationToken cancellationToken)
    {
        var response = await FacadeTransport.SendAsync(
            () => client.GetVatTypesAsync(
                request.Filter, request.Sort, request.PageIndex, request.PageSize, cancellationToken),
            "GET /vat-types").ConfigureAwait(false);

        var items = new List<VatType>(response.Collection?.Count ?? 0);
        foreach (var item in response.Collection ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicPage<VatType>(items, request.PageIndex, request.PageSize);
    }

    private static VatType Map(Generated.VatType source) => new()
    {
        VatTypeNumber = source.VatTypeNumber,
        Name = source.Name ?? string.Empty,
        Self = source.Self,
    };

    private static EconomicReference? Reference(int? number, System.Uri? self) =>
        number is null ? null : new EconomicReference(number.Value, self);
}

/// <summary>
/// A resource from <c>/vat-zones</c>.
/// </summary>
public sealed record VatZone
{
    /// <summary>The <c>vatZoneNumber</c> field.</summary>
    public int VatZoneNumber { get; init; }

    /// <summary>The <c>name</c> field.</summary>
    public string? Name { get; init; }

    /// <summary>The <c>enabledForCustomer</c> field.</summary>
    public bool EnabledForCustomer { get; init; }

    /// <summary>The <c>enabledForSupplier</c> field.</summary>
    public bool EnabledForSupplier { get; init; }

    /// <summary>The <c>self</c> field.</summary>
    public required System.Uri Self { get; init; }
}

/// <summary>Fetches pages of <c>/vat-zones</c> and maps them to <see cref="VatZone"/>.</summary>
internal sealed class VatZonePageSource(Generated.VatZonesClient client)
    : IEconomicPageSource<VatZone>
{
    public async Task<EconomicPage<VatZone>> GetPageAsync(
        EconomicPageRequest request,
        CancellationToken cancellationToken)
    {
        var response = await FacadeTransport.SendAsync(
            () => client.GetVatZonesAsync(
                request.Filter, request.Sort, request.PageIndex, request.PageSize, cancellationToken),
            "GET /vat-zones").ConfigureAwait(false);

        var items = new List<VatZone>(response.Collection?.Count ?? 0);
        foreach (var item in response.Collection ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicPage<VatZone>(items, request.PageIndex, request.PageSize);
    }

    private static VatZone Map(Generated.VatZone source) => new()
    {
        VatZoneNumber = source.VatZoneNumber,
        Name = source.Name,
        EnabledForCustomer = source.EnabledForCustomer,
        EnabledForSupplier = source.EnabledForSupplier,
        Self = source.Self,
    };

    private static EconomicReference? Reference(int? number, System.Uri? self) =>
        number is null ? null : new EconomicReference(number.Value, self);
}
}

namespace EConomic
{
    using EConomic.Rest;

    public sealed partial class EconomicClient
    {
        /// <summary><c>/accounting-years</c>, as a composable query.</summary>
        public EconomicQuery<AccountingYear, AccountingYearFilter, AccountingYearSort> AccountingYears =>
            new(new AccountingYearPageSource(new Generated.AccountingYearsClient(HttpClient)));

        /// <summary><c>/accounts</c>, as a composable query.</summary>
        public EconomicQuery<Account, AccountFilter, AccountSort> Accounts =>
            new(new AccountPageSource(new Generated.AccountsClient(HttpClient)));

        /// <summary><c>/app-roles</c>, as a composable query.</summary>
        public EconomicQuery<AppRole, AppRoleFilter, AppRoleSort> AppRoles =>
            new(new AppRolePageSource(new Generated.AppRolesClient(HttpClient)));

        /// <summary><c>/currencies</c>, as a composable query.</summary>
        public EconomicQuery<Currency, CurrencyFilter, CurrencySort> Currencies =>
            new(new CurrencyPageSource(new Generated.CurrenciesClient(HttpClient)));

        /// <summary><c>/customer-groups</c>, as a composable query.</summary>
        public EconomicQuery<CustomerGroup, CustomerGroupFilter, CustomerGroupSort> CustomerGroups =>
            new(new CustomerGroupPageSource(new Generated.CustomerGroupsClient(HttpClient)));

        /// <summary><c>/customers</c>, as a composable query.</summary>
        public EconomicQuery<Customer, CustomerFilter, CustomerSort> Customers =>
            new(new CustomerPageSource(new Generated.CustomersClient(HttpClient)));

        /// <summary><c>/departmental-distributions</c>, as a composable query.</summary>
        public EconomicQuery<DepartmentalDistributionSummary, DepartmentalDistributionSummaryFilter, DepartmentalDistributionSummarySort> DepartmentalDistributions =>
            new(new DepartmentalDistributionSummaryPageSource(new Generated.DepartmentalDistributionsClient(HttpClient)));

        /// <summary><c>/departments</c>, as a composable query.</summary>
        public EconomicQuery<Department, DepartmentFilter, DepartmentSort> Departments =>
            new(new DepartmentPageSource(new Generated.DepartmentsClient(HttpClient)));

        /// <summary><c>/employees</c>, as a composable query.</summary>
        public EconomicQuery<Employee, EmployeeFilter, EmployeeSort> Employees =>
            new(new EmployeePageSource(new Generated.EmployeesClient(HttpClient)));

        /// <summary><c>/journals</c>, as a composable query.</summary>
        public EconomicQuery<Journal, JournalFilter, JournalSort> Journals =>
            new(new JournalPageSource(new Generated.JournalsClient(HttpClient)));

        /// <summary><c>/layouts</c>, as a composable query.</summary>
        public EconomicQuery<Layout, LayoutFilter, LayoutSort> Layouts =>
            new(new LayoutPageSource(new Generated.LayoutsClient(HttpClient)));

        /// <summary><c>/payment-terms</c>, as a composable query.</summary>
        public EconomicQuery<PaymentTerms, PaymentTermsFilter, PaymentTermsSort> PaymentTerms =>
            new(new PaymentTermsPageSource(new Generated.PaymentTermsClient(HttpClient)));

        /// <summary><c>/payment-types</c>, as a composable query.</summary>
        public EconomicQuery<PaymentType, PaymentTypeFilter, PaymentTypeSort> PaymentTypes =>
            new(new PaymentTypePageSource(new Generated.PaymentTypesClient(HttpClient)));

        /// <summary><c>/product-groups</c>, as a composable query.</summary>
        public EconomicQuery<ProductGroup, ProductGroupFilter, ProductGroupSort> ProductGroups =>
            new(new ProductGroupPageSource(new Generated.ProductGroupsClient(HttpClient)));

        /// <summary><c>/products</c>, as a composable query.</summary>
        public EconomicQuery<Product, ProductFilter, ProductSort> Products =>
            new(new ProductPageSource(new Generated.ProductsClient(HttpClient)));

        /// <summary><c>/suppliers</c>, as a composable query.</summary>
        public EconomicQuery<Supplier, SupplierFilter, SupplierSort> Suppliers =>
            new(new SupplierPageSource(new Generated.SuppliersClient(HttpClient)));

        /// <summary><c>/units</c>, as a composable query.</summary>
        public EconomicQuery<Unit, UnitFilter, UnitSort> Units =>
            new(new UnitPageSource(new Generated.UnitsClient(HttpClient)));

        /// <summary><c>/vat-accounts</c>, as a composable query.</summary>
        public EconomicQuery<VatAccount, VatAccountFilter, VatAccountSort> VatAccounts =>
            new(new VatAccountPageSource(new Generated.VatAccountsClient(HttpClient)));

        /// <summary><c>/vat-types</c>, as a composable query.</summary>
        public EconomicQuery<VatType, VatTypeFilter, VatTypeSort> VatTypes =>
            new(new VatTypePageSource(new Generated.VatTypesClient(HttpClient)));

        /// <summary><c>/vat-zones</c>, as a composable query.</summary>
        public EconomicQuery<VatZone, VatZoneFilter, VatZoneSort> VatZones =>
            new(new VatZonePageSource(new Generated.VatZonesClient(HttpClient)));
    }
}
