// <auto-generated>
//     Generated by tools/EConomic.SpecConverter (filters).
//     Regenerate after a spec refresh; do not edit by hand.
// </auto-generated>
#nullable enable

using EConomic.Querying;

namespace EConomic.Rest;

/// <summary>
/// The properties e-conomic will filter <c>Account</c> on, each typed to the
/// operators it accepts. Anything absent here is not filterable.
/// </summary>
/// <remarks>
/// Operator sets are inferred from each property's type: the legacy schemas record only
/// whether a property is filterable, not which operators it accepts. The inference errs
/// toward fewer operators, so it can under-report but will not produce a request the
/// server rejects.
/// </remarks>
public sealed class AccountFilter
{
    /// <summary>Maps to <c>accountNumber</c>.</summary>
    [EconomicField("accountNumber")]
    public NumericField<int> AccountNumber { get; } = null!;

    /// <summary>Maps to <c>accountType</c>.</summary>
    [EconomicField("accountType")]
    public TextField AccountType { get; } = null!;

    /// <summary>Maps to <c>balance</c>.</summary>
    [EconomicField("balance")]
    public NumericField<decimal> Balance { get; } = null!;

    /// <summary>Maps to <c>barred</c>.</summary>
    [EconomicField("barred")]
    public BooleanField Barred { get; } = null!;

    /// <summary>Maps to <c>blockDirectEntries</c>.</summary>
    [EconomicField("blockDirectEntries")]
    public BooleanField BlockDirectEntries { get; } = null!;

    /// <summary>Maps to <c>debitCredit</c>.</summary>
    [EconomicField("debitCredit")]
    public TextField DebitCredit { get; } = null!;

    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public TextField Name { get; } = null!;
}

/// <summary>
/// The properties e-conomic will sort <c>Account</c> by.
/// </summary>
public sealed class AccountSort
{
    /// <summary>Maps to <c>accountNumber</c>.</summary>
    [EconomicField("accountNumber")]
    public EconomicSortField AccountNumber { get; } = null!;

    /// <summary>Maps to <c>accountType</c>.</summary>
    [EconomicField("accountType")]
    public EconomicSortField AccountType { get; } = null!;

    /// <summary>Maps to <c>balance</c>.</summary>
    [EconomicField("balance")]
    public EconomicSortField Balance { get; } = null!;

    /// <summary>Maps to <c>blockDirectEntries</c>.</summary>
    [EconomicField("blockDirectEntries")]
    public EconomicSortField BlockDirectEntries { get; } = null!;

    /// <summary>Maps to <c>debitCredit</c>.</summary>
    [EconomicField("debitCredit")]
    public EconomicSortField DebitCredit { get; } = null!;

    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public EconomicSortField Name { get; } = null!;
}

/// <summary>
/// The properties e-conomic will filter <c>AccountingYear</c> on, each typed to the
/// operators it accepts. Anything absent here is not filterable.
/// </summary>
/// <remarks>
/// Operator sets are inferred from each property's type: the legacy schemas record only
/// whether a property is filterable, not which operators it accepts. The inference errs
/// toward fewer operators, so it can under-report but will not produce a request the
/// server rejects.
/// </remarks>
public sealed class AccountingYearFilter
{
    /// <summary>Maps to <c>fromDate</c>.</summary>
    [EconomicField("fromDate")]
    public ComparableField<System.DateOnly> FromDate { get; } = null!;

    /// <summary>Maps to <c>toDate</c>.</summary>
    [EconomicField("toDate")]
    public ComparableField<System.DateOnly> ToDate { get; } = null!;

    /// <summary>Maps to <c>closed</c>.</summary>
    [EconomicField("closed")]
    public BooleanField Closed { get; } = null!;

    /// <summary>Maps to <c>year</c>.</summary>
    [EconomicField("year")]
    public TextField Year { get; } = null!;
}

/// <summary>
/// The properties e-conomic will sort <c>AccountingYear</c> by.
/// </summary>
public sealed class AccountingYearSort
{
    /// <summary>Maps to <c>fromDate</c>.</summary>
    [EconomicField("fromDate")]
    public EconomicSortField FromDate { get; } = null!;

    /// <summary>Maps to <c>toDate</c>.</summary>
    [EconomicField("toDate")]
    public EconomicSortField ToDate { get; } = null!;

    /// <summary>Maps to <c>closed</c>.</summary>
    [EconomicField("closed")]
    public EconomicSortField Closed { get; } = null!;

    /// <summary>Maps to <c>year</c>.</summary>
    [EconomicField("year")]
    public EconomicSortField Year { get; } = null!;
}

/// <summary>
/// The properties e-conomic will filter <c>AppRole</c> on, each typed to the
/// operators it accepts. Anything absent here is not filterable.
/// </summary>
/// <remarks>
/// Operator sets are inferred from each property's type: the legacy schemas record only
/// whether a property is filterable, not which operators it accepts. The inference errs
/// toward fewer operators, so it can under-report but will not produce a request the
/// server rejects.
/// </remarks>
public sealed class AppRoleFilter
{
    /// <summary>Maps to <c>roleNumber</c>.</summary>
    [EconomicField("roleNumber")]
    public NumericField<int> RoleNumber { get; } = null!;
}

/// <summary>
/// The properties e-conomic will sort <c>AppRole</c> by.
/// </summary>
public sealed class AppRoleSort
{
    /// <summary>Maps to <c>roleNumber</c>.</summary>
    [EconomicField("roleNumber")]
    public EconomicSortField RoleNumber { get; } = null!;
}

/// <summary>
/// The properties e-conomic will filter <c>Currency</c> on, each typed to the
/// operators it accepts. Anything absent here is not filterable.
/// </summary>
/// <remarks>
/// Operator sets are inferred from each property's type: the legacy schemas record only
/// whether a property is filterable, not which operators it accepts. The inference errs
/// toward fewer operators, so it can under-report but will not produce a request the
/// server rejects.
/// </remarks>
public sealed class CurrencyFilter
{
}

/// <summary>
/// The properties e-conomic will sort <c>Currency</c> by.
/// </summary>
public sealed class CurrencySort
{
}

/// <summary>
/// The properties e-conomic will filter <c>Customer</c> on, each typed to the
/// operators it accepts. Anything absent here is not filterable.
/// </summary>
/// <remarks>
/// Operator sets are inferred from each property's type: the legacy schemas record only
/// whether a property is filterable, not which operators it accepts. The inference errs
/// toward fewer operators, so it can under-report but will not produce a request the
/// server rejects.
/// </remarks>
public sealed class CustomerFilter
{
    /// <summary>Maps to <c>address</c>.</summary>
    [EconomicField("address")]
    public TextField Address { get; } = null!;

    /// <summary>Maps to <c>balance</c>.</summary>
    [EconomicField("balance")]
    public NumericField<decimal> Balance { get; } = null!;

    /// <summary>Maps to <c>barred</c>.</summary>
    [EconomicField("barred")]
    public BooleanField Barred { get; } = null!;

    /// <summary>Maps to <c>city</c>.</summary>
    [EconomicField("city")]
    public TextField City { get; } = null!;

    /// <summary>Maps to <c>corporateIdentificationNumber</c>.</summary>
    [EconomicField("corporateIdentificationNumber")]
    public TextField CorporateIdentificationNumber { get; } = null!;

    /// <summary>Maps to <c>country</c>.</summary>
    [EconomicField("country")]
    public TextField Country { get; } = null!;

    /// <summary>Maps to <c>creditLimit</c>.</summary>
    [EconomicField("creditLimit")]
    public NumericField<decimal> CreditLimit { get; } = null!;

    /// <summary>Maps to <c>currency</c>.</summary>
    [EconomicField("currency")]
    public TextField Currency { get; } = null!;

    /// <summary>Maps to <c>customerNumber</c>.</summary>
    [EconomicField("customerNumber")]
    public NumericField<int> CustomerNumber { get; } = null!;

    /// <summary>Maps to <c>ean</c>.</summary>
    [EconomicField("ean")]
    public TextField Ean { get; } = null!;

    /// <summary>Maps to <c>email</c>.</summary>
    [EconomicField("email")]
    public TextField Email { get; } = null!;

    /// <summary>Maps to <c>lastUpdated</c>.</summary>
    [EconomicField("lastUpdated")]
    public ComparableField<System.DateTimeOffset> LastUpdated { get; } = null!;

    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public TextField Name { get; } = null!;

    /// <summary>Maps to <c>publicEntryNumber</c>.</summary>
    [EconomicField("publicEntryNumber")]
    public TextField PublicEntryNumber { get; } = null!;

    /// <summary>Maps to <c>telephoneAndFaxNumber</c>.</summary>
    [EconomicField("telephoneAndFaxNumber")]
    public TextField TelephoneAndFaxNumber { get; } = null!;

    /// <summary>Maps to <c>mobilePhone</c>.</summary>
    [EconomicField("mobilePhone")]
    public TextField MobilePhone { get; } = null!;

    /// <summary>Maps to <c>vatNumber</c>.</summary>
    [EconomicField("vatNumber")]
    public TextField VatNumber { get; } = null!;

    /// <summary>Maps to <c>website</c>.</summary>
    [EconomicField("website")]
    public TextField Website { get; } = null!;

    /// <summary>Maps to <c>zip</c>.</summary>
    [EconomicField("zip")]
    public TextField Zip { get; } = null!;

    /// <summary>Maps to <c>customerGroup.customerGroupNumber</c>.</summary>
    [EconomicField("customerGroup.customerGroupNumber")]
    public NumericField<int> CustomerGroupNumber { get; } = null!;
}

/// <summary>
/// The properties e-conomic will sort <c>Customer</c> by.
/// </summary>
public sealed class CustomerSort
{
    /// <summary>Maps to <c>address</c>.</summary>
    [EconomicField("address")]
    public EconomicSortField Address { get; } = null!;

    /// <summary>Maps to <c>balance</c>.</summary>
    [EconomicField("balance")]
    public EconomicSortField Balance { get; } = null!;

    /// <summary>Maps to <c>city</c>.</summary>
    [EconomicField("city")]
    public EconomicSortField City { get; } = null!;

    /// <summary>Maps to <c>corporateIdentificationNumber</c>.</summary>
    [EconomicField("corporateIdentificationNumber")]
    public EconomicSortField CorporateIdentificationNumber { get; } = null!;

    /// <summary>Maps to <c>country</c>.</summary>
    [EconomicField("country")]
    public EconomicSortField Country { get; } = null!;

    /// <summary>Maps to <c>creditLimit</c>.</summary>
    [EconomicField("creditLimit")]
    public EconomicSortField CreditLimit { get; } = null!;

    /// <summary>Maps to <c>currency</c>.</summary>
    [EconomicField("currency")]
    public EconomicSortField Currency { get; } = null!;

    /// <summary>Maps to <c>customerNumber</c>.</summary>
    [EconomicField("customerNumber")]
    public EconomicSortField CustomerNumber { get; } = null!;

    /// <summary>Maps to <c>ean</c>.</summary>
    [EconomicField("ean")]
    public EconomicSortField Ean { get; } = null!;

    /// <summary>Maps to <c>email</c>.</summary>
    [EconomicField("email")]
    public EconomicSortField Email { get; } = null!;

    /// <summary>Maps to <c>lastUpdated</c>.</summary>
    [EconomicField("lastUpdated")]
    public EconomicSortField LastUpdated { get; } = null!;

    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public EconomicSortField Name { get; } = null!;

    /// <summary>Maps to <c>publicEntryNumber</c>.</summary>
    [EconomicField("publicEntryNumber")]
    public EconomicSortField PublicEntryNumber { get; } = null!;

    /// <summary>Maps to <c>telephoneAndFaxNumber</c>.</summary>
    [EconomicField("telephoneAndFaxNumber")]
    public EconomicSortField TelephoneAndFaxNumber { get; } = null!;

    /// <summary>Maps to <c>mobilePhone</c>.</summary>
    [EconomicField("mobilePhone")]
    public EconomicSortField MobilePhone { get; } = null!;

    /// <summary>Maps to <c>vatNumber</c>.</summary>
    [EconomicField("vatNumber")]
    public EconomicSortField VatNumber { get; } = null!;

    /// <summary>Maps to <c>website</c>.</summary>
    [EconomicField("website")]
    public EconomicSortField Website { get; } = null!;

    /// <summary>Maps to <c>zip</c>.</summary>
    [EconomicField("zip")]
    public EconomicSortField Zip { get; } = null!;
}

/// <summary>
/// The properties e-conomic will filter <c>CustomerGroup</c> on, each typed to the
/// operators it accepts. Anything absent here is not filterable.
/// </summary>
/// <remarks>
/// Operator sets are inferred from each property's type: the legacy schemas record only
/// whether a property is filterable, not which operators it accepts. The inference errs
/// toward fewer operators, so it can under-report but will not produce a request the
/// server rejects.
/// </remarks>
public sealed class CustomerGroupFilter
{
    /// <summary>Maps to <c>customerGroupNumber</c>.</summary>
    [EconomicField("customerGroupNumber")]
    public NumericField<int> CustomerGroupNumber { get; } = null!;

    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public TextField Name { get; } = null!;

    /// <summary>Maps to <c>account.accountNumber</c>.</summary>
    [EconomicField("account.accountNumber")]
    public NumericField<int> AccountNumber { get; } = null!;

    /// <summary>Maps to <c>account.accountType</c>.</summary>
    [EconomicField("account.accountType")]
    public TextField AccountType { get; } = null!;

    /// <summary>Maps to <c>account.balance</c>.</summary>
    [EconomicField("account.balance")]
    public NumericField<decimal> AccountBalance { get; } = null!;

    /// <summary>Maps to <c>account.blockDirectEntries</c>.</summary>
    [EconomicField("account.blockDirectEntries")]
    public BooleanField AccountBlockDirectEntries { get; } = null!;

    /// <summary>Maps to <c>account.debitCredit</c>.</summary>
    [EconomicField("account.debitCredit")]
    public TextField AccountDebitCredit { get; } = null!;

    /// <summary>Maps to <c>account.name</c>.</summary>
    [EconomicField("account.name")]
    public TextField AccountName { get; } = null!;
}

/// <summary>
/// The properties e-conomic will sort <c>CustomerGroup</c> by.
/// </summary>
public sealed class CustomerGroupSort
{
    /// <summary>Maps to <c>customerGroupNumber</c>.</summary>
    [EconomicField("customerGroupNumber")]
    public EconomicSortField CustomerGroupNumber { get; } = null!;

    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public EconomicSortField Name { get; } = null!;

    /// <summary>Maps to <c>account.accountNumber</c>.</summary>
    [EconomicField("account.accountNumber")]
    public EconomicSortField AccountNumber { get; } = null!;

    /// <summary>Maps to <c>account.accountType</c>.</summary>
    [EconomicField("account.accountType")]
    public EconomicSortField AccountType { get; } = null!;

    /// <summary>Maps to <c>account.balance</c>.</summary>
    [EconomicField("account.balance")]
    public EconomicSortField AccountBalance { get; } = null!;

    /// <summary>Maps to <c>account.blockDirectEntries</c>.</summary>
    [EconomicField("account.blockDirectEntries")]
    public EconomicSortField AccountBlockDirectEntries { get; } = null!;

    /// <summary>Maps to <c>account.debitCredit</c>.</summary>
    [EconomicField("account.debitCredit")]
    public EconomicSortField AccountDebitCredit { get; } = null!;

    /// <summary>Maps to <c>account.name</c>.</summary>
    [EconomicField("account.name")]
    public EconomicSortField AccountName { get; } = null!;
}

/// <summary>
/// The properties e-conomic will filter <c>Department</c> on, each typed to the
/// operators it accepts. Anything absent here is not filterable.
/// </summary>
/// <remarks>
/// Operator sets are inferred from each property's type: the legacy schemas record only
/// whether a property is filterable, not which operators it accepts. The inference errs
/// toward fewer operators, so it can under-report but will not produce a request the
/// server rejects.
/// </remarks>
public sealed class DepartmentFilter
{
    /// <summary>Maps to <c>departmentNumber</c>.</summary>
    [EconomicField("departmentNumber")]
    public NumericField<int> DepartmentNumber { get; } = null!;

    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public TextField Name { get; } = null!;

    /// <summary>Maps to <c>barred</c>.</summary>
    [EconomicField("barred")]
    public BooleanField Barred { get; } = null!;
}

/// <summary>
/// The properties e-conomic will sort <c>Department</c> by.
/// </summary>
public sealed class DepartmentSort
{
    /// <summary>Maps to <c>departmentNumber</c>.</summary>
    [EconomicField("departmentNumber")]
    public EconomicSortField DepartmentNumber { get; } = null!;

    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public EconomicSortField Name { get; } = null!;
}

/// <summary>
/// The properties e-conomic will filter <c>DepartmentalDistributionSummary</c> on, each typed to the
/// operators it accepts. Anything absent here is not filterable.
/// </summary>
/// <remarks>
/// Operator sets are inferred from each property's type: the legacy schemas record only
/// whether a property is filterable, not which operators it accepts. The inference errs
/// toward fewer operators, so it can under-report but will not produce a request the
/// server rejects.
/// </remarks>
public sealed class DepartmentalDistributionSummaryFilter
{
    /// <summary>Maps to <c>departmentalDistributionNumber</c>.</summary>
    [EconomicField("departmentalDistributionNumber")]
    public NumericField<int> DepartmentalDistributionNumber { get; } = null!;

    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public TextField Name { get; } = null!;
}

/// <summary>
/// The properties e-conomic will sort <c>DepartmentalDistributionSummary</c> by.
/// </summary>
public sealed class DepartmentalDistributionSummarySort
{
    /// <summary>Maps to <c>departmentalDistributionNumber</c>.</summary>
    [EconomicField("departmentalDistributionNumber")]
    public EconomicSortField DepartmentalDistributionNumber { get; } = null!;

    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public EconomicSortField Name { get; } = null!;
}

/// <summary>
/// The properties e-conomic will filter <c>Employee</c> on, each typed to the
/// operators it accepts. Anything absent here is not filterable.
/// </summary>
/// <remarks>
/// Operator sets are inferred from each property's type: the legacy schemas record only
/// whether a property is filterable, not which operators it accepts. The inference errs
/// toward fewer operators, so it can under-report but will not produce a request the
/// server rejects.
/// </remarks>
public sealed class EmployeeFilter
{
    /// <summary>Maps to <c>employeeNumber</c>.</summary>
    [EconomicField("employeeNumber")]
    public NumericField<int> EmployeeNumber { get; } = null!;

    /// <summary>Maps to <c>employeeGroup.employeeGroupNumber</c>.</summary>
    [EconomicField("employeeGroup.employeeGroupNumber")]
    public NumericField<int> EmployeeGroupNumber { get; } = null!;

    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public TextField Name { get; } = null!;

    /// <summary>Maps to <c>email</c>.</summary>
    [EconomicField("email")]
    public TextField Email { get; } = null!;

    /// <summary>Maps to <c>phone</c>.</summary>
    [EconomicField("phone")]
    public TextField Phone { get; } = null!;

    /// <summary>Maps to <c>barred</c>.</summary>
    [EconomicField("barred")]
    public BooleanField Barred { get; } = null!;
}

/// <summary>
/// The properties e-conomic will sort <c>Employee</c> by.
/// </summary>
public sealed class EmployeeSort
{
    /// <summary>Maps to <c>employeeNumber</c>.</summary>
    [EconomicField("employeeNumber")]
    public EconomicSortField EmployeeNumber { get; } = null!;

    /// <summary>Maps to <c>employeeGroup.employeeGroupNumber</c>.</summary>
    [EconomicField("employeeGroup.employeeGroupNumber")]
    public EconomicSortField EmployeeGroupNumber { get; } = null!;

    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public EconomicSortField Name { get; } = null!;

    /// <summary>Maps to <c>email</c>.</summary>
    [EconomicField("email")]
    public EconomicSortField Email { get; } = null!;

    /// <summary>Maps to <c>phone</c>.</summary>
    [EconomicField("phone")]
    public EconomicSortField Phone { get; } = null!;
}

/// <summary>
/// The properties e-conomic will filter <c>Journal</c> on, each typed to the
/// operators it accepts. Anything absent here is not filterable.
/// </summary>
/// <remarks>
/// Operator sets are inferred from each property's type: the legacy schemas record only
/// whether a property is filterable, not which operators it accepts. The inference errs
/// toward fewer operators, so it can under-report but will not produce a request the
/// server rejects.
/// </remarks>
public sealed class JournalFilter
{
    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public TextField Name { get; } = null!;

    /// <summary>Maps to <c>journalNumber</c>.</summary>
    [EconomicField("journalNumber")]
    public NumericField<int> JournalNumber { get; } = null!;
}

/// <summary>
/// The properties e-conomic will sort <c>Journal</c> by.
/// </summary>
public sealed class JournalSort
{
    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public EconomicSortField Name { get; } = null!;

    /// <summary>Maps to <c>journalNumber</c>.</summary>
    [EconomicField("journalNumber")]
    public EconomicSortField JournalNumber { get; } = null!;
}

/// <summary>
/// The properties e-conomic will filter <c>Layout</c> on, each typed to the
/// operators it accepts. Anything absent here is not filterable.
/// </summary>
/// <remarks>
/// Operator sets are inferred from each property's type: the legacy schemas record only
/// whether a property is filterable, not which operators it accepts. The inference errs
/// toward fewer operators, so it can under-report but will not produce a request the
/// server rejects.
/// </remarks>
public sealed class LayoutFilter
{
}

/// <summary>
/// The properties e-conomic will sort <c>Layout</c> by.
/// </summary>
public sealed class LayoutSort
{
}

/// <summary>
/// The properties e-conomic will filter <c>PaymentTerms</c> on, each typed to the
/// operators it accepts. Anything absent here is not filterable.
/// </summary>
/// <remarks>
/// Operator sets are inferred from each property's type: the legacy schemas record only
/// whether a property is filterable, not which operators it accepts. The inference errs
/// toward fewer operators, so it can under-report but will not produce a request the
/// server rejects.
/// </remarks>
public sealed class PaymentTermsFilter
{
}

/// <summary>
/// The properties e-conomic will sort <c>PaymentTerms</c> by.
/// </summary>
public sealed class PaymentTermsSort
{
}

/// <summary>
/// The properties e-conomic will filter <c>PaymentType</c> on, each typed to the
/// operators it accepts. Anything absent here is not filterable.
/// </summary>
/// <remarks>
/// Operator sets are inferred from each property's type: the legacy schemas record only
/// whether a property is filterable, not which operators it accepts. The inference errs
/// toward fewer operators, so it can under-report but will not produce a request the
/// server rejects.
/// </remarks>
public sealed class PaymentTypeFilter
{
}

/// <summary>
/// The properties e-conomic will sort <c>PaymentType</c> by.
/// </summary>
public sealed class PaymentTypeSort
{
}

/// <summary>
/// The properties e-conomic will filter <c>Product</c> on, each typed to the
/// operators it accepts. Anything absent here is not filterable.
/// </summary>
/// <remarks>
/// Operator sets are inferred from each property's type: the legacy schemas record only
/// whether a property is filterable, not which operators it accepts. The inference errs
/// toward fewer operators, so it can under-report but will not produce a request the
/// server rejects.
/// </remarks>
public sealed class ProductFilter
{
    /// <summary>Maps to <c>productNumber</c>.</summary>
    [EconomicField("productNumber")]
    public TextField ProductNumber { get; } = null!;

    /// <summary>Maps to <c>description</c>.</summary>
    [EconomicField("description")]
    public TextField Description { get; } = null!;

    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public TextField Name { get; } = null!;

    /// <summary>Maps to <c>costPrice</c>.</summary>
    [EconomicField("costPrice")]
    public NumericField<decimal> CostPrice { get; } = null!;

    /// <summary>Maps to <c>recommendedPrice</c>.</summary>
    [EconomicField("recommendedPrice")]
    public NumericField<decimal> RecommendedPrice { get; } = null!;

    /// <summary>Maps to <c>salesPrice</c>.</summary>
    [EconomicField("salesPrice")]
    public NumericField<decimal> SalesPrice { get; } = null!;

    /// <summary>Maps to <c>barCode</c>.</summary>
    [EconomicField("barCode")]
    public TextField BarCode { get; } = null!;

    /// <summary>Maps to <c>barred</c>.</summary>
    [EconomicField("barred")]
    public BooleanField Barred { get; } = null!;

    /// <summary>Maps to <c>lastUpdated</c>.</summary>
    [EconomicField("lastUpdated")]
    public ComparableField<System.DateTimeOffset> LastUpdated { get; } = null!;

    /// <summary>Maps to <c>inventory.packageVolume</c>.</summary>
    [EconomicField("inventory.packageVolume")]
    public NumericField<decimal> InventoryPackageVolume { get; } = null!;

    /// <summary>Maps to <c>inventory.grossWeight</c>.</summary>
    [EconomicField("inventory.grossWeight")]
    public NumericField<decimal> InventoryGrossWeight { get; } = null!;

    /// <summary>Maps to <c>inventory.netWeight</c>.</summary>
    [EconomicField("inventory.netWeight")]
    public NumericField<decimal> InventoryNetWeight { get; } = null!;

    /// <summary>Maps to <c>inventory.recommendedCostPrice</c>.</summary>
    [EconomicField("inventory.recommendedCostPrice")]
    public NumericField<decimal> InventoryRecommendedCostPrice { get; } = null!;

    /// <summary>Maps to <c>unit.unitNumber</c>.</summary>
    [EconomicField("unit.unitNumber")]
    public NumericField<int> UnitNumber { get; } = null!;

    /// <summary>Maps to <c>productGroup.productGroupNumber</c>.</summary>
    [EconomicField("productGroup.productGroupNumber")]
    public NumericField<int> ProductGroupNumber { get; } = null!;

    /// <summary>Maps to <c>departmentalDistribution.departmentalDistributionNumber</c>.</summary>
    [EconomicField("departmentalDistribution.departmentalDistributionNumber")]
    public NumericField<int> DepartmentalDistributionNumber { get; } = null!;
}

/// <summary>
/// The properties e-conomic will sort <c>Product</c> by.
/// </summary>
public sealed class ProductSort
{
    /// <summary>Maps to <c>productNumber</c>.</summary>
    [EconomicField("productNumber")]
    public EconomicSortField ProductNumber { get; } = null!;

    /// <summary>Maps to <c>description</c>.</summary>
    [EconomicField("description")]
    public EconomicSortField Description { get; } = null!;

    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public EconomicSortField Name { get; } = null!;

    /// <summary>Maps to <c>costPrice</c>.</summary>
    [EconomicField("costPrice")]
    public EconomicSortField CostPrice { get; } = null!;

    /// <summary>Maps to <c>recommendedPrice</c>.</summary>
    [EconomicField("recommendedPrice")]
    public EconomicSortField RecommendedPrice { get; } = null!;

    /// <summary>Maps to <c>salesPrice</c>.</summary>
    [EconomicField("salesPrice")]
    public EconomicSortField SalesPrice { get; } = null!;

    /// <summary>Maps to <c>barCode</c>.</summary>
    [EconomicField("barCode")]
    public EconomicSortField BarCode { get; } = null!;

    /// <summary>Maps to <c>barred</c>.</summary>
    [EconomicField("barred")]
    public EconomicSortField Barred { get; } = null!;

    /// <summary>Maps to <c>lastUpdated</c>.</summary>
    [EconomicField("lastUpdated")]
    public EconomicSortField LastUpdated { get; } = null!;

    /// <summary>Maps to <c>inventory.packageVolume</c>.</summary>
    [EconomicField("inventory.packageVolume")]
    public EconomicSortField InventoryPackageVolume { get; } = null!;

    /// <summary>Maps to <c>inventory.grossWeight</c>.</summary>
    [EconomicField("inventory.grossWeight")]
    public EconomicSortField InventoryGrossWeight { get; } = null!;

    /// <summary>Maps to <c>inventory.netWeight</c>.</summary>
    [EconomicField("inventory.netWeight")]
    public EconomicSortField InventoryNetWeight { get; } = null!;
}

/// <summary>
/// The properties e-conomic will filter <c>ProductGroup</c> on, each typed to the
/// operators it accepts. Anything absent here is not filterable.
/// </summary>
/// <remarks>
/// Operator sets are inferred from each property's type: the legacy schemas record only
/// whether a property is filterable, not which operators it accepts. The inference errs
/// toward fewer operators, so it can under-report but will not produce a request the
/// server rejects.
/// </remarks>
public sealed class ProductGroupFilter
{
}

/// <summary>
/// The properties e-conomic will sort <c>ProductGroup</c> by.
/// </summary>
public sealed class ProductGroupSort
{
}

/// <summary>
/// The properties e-conomic will filter <c>Supplier</c> on, each typed to the
/// operators it accepts. Anything absent here is not filterable.
/// </summary>
/// <remarks>
/// Operator sets are inferred from each property's type: the legacy schemas record only
/// whether a property is filterable, not which operators it accepts. The inference errs
/// toward fewer operators, so it can under-report but will not produce a request the
/// server rejects.
/// </remarks>
public sealed class SupplierFilter
{
    /// <summary>Maps to <c>address</c>.</summary>
    [EconomicField("address")]
    public TextField Address { get; } = null!;

    /// <summary>Maps to <c>bankAccount</c>.</summary>
    [EconomicField("bankAccount")]
    public TextField BankAccount { get; } = null!;

    /// <summary>Maps to <c>barred</c>.</summary>
    [EconomicField("barred")]
    public BooleanField Barred { get; } = null!;

    /// <summary>Maps to <c>city</c>.</summary>
    [EconomicField("city")]
    public TextField City { get; } = null!;

    /// <summary>Maps to <c>corporateIdentificationNumber</c>.</summary>
    [EconomicField("corporateIdentificationNumber")]
    public TextField CorporateIdentificationNumber { get; } = null!;

    /// <summary>Maps to <c>country</c>.</summary>
    [EconomicField("country")]
    public TextField Country { get; } = null!;

    /// <summary>Maps to <c>currency</c>.</summary>
    [EconomicField("currency")]
    public TextField Currency { get; } = null!;

    /// <summary>Maps to <c>defaultInvoiceText</c>.</summary>
    [EconomicField("defaultInvoiceText")]
    public TextField DefaultInvoiceText { get; } = null!;

    /// <summary>Maps to <c>email</c>.</summary>
    [EconomicField("email")]
    public TextField Email { get; } = null!;

    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public TextField Name { get; } = null!;

    /// <summary>Maps to <c>supplierGroup.supplierGroupNumber</c>.</summary>
    [EconomicField("supplierGroup.supplierGroupNumber")]
    public NumericField<int> SupplierGroupNumber { get; } = null!;

    /// <summary>Maps to <c>supplierNumber</c>.</summary>
    [EconomicField("supplierNumber")]
    public NumericField<int> SupplierNumber { get; } = null!;

    /// <summary>Maps to <c>zip</c>.</summary>
    [EconomicField("zip")]
    public TextField Zip { get; } = null!;
}

/// <summary>
/// The properties e-conomic will sort <c>Supplier</c> by.
/// </summary>
public sealed class SupplierSort
{
}

/// <summary>
/// The properties e-conomic will filter <c>Unit</c> on, each typed to the
/// operators it accepts. Anything absent here is not filterable.
/// </summary>
/// <remarks>
/// Operator sets are inferred from each property's type: the legacy schemas record only
/// whether a property is filterable, not which operators it accepts. The inference errs
/// toward fewer operators, so it can under-report but will not produce a request the
/// server rejects.
/// </remarks>
public sealed class UnitFilter
{
}

/// <summary>
/// The properties e-conomic will sort <c>Unit</c> by.
/// </summary>
public sealed class UnitSort
{
}

/// <summary>
/// The properties e-conomic will filter <c>VatAccount</c> on, each typed to the
/// operators it accepts. Anything absent here is not filterable.
/// </summary>
/// <remarks>
/// Operator sets are inferred from each property's type: the legacy schemas record only
/// whether a property is filterable, not which operators it accepts. The inference errs
/// toward fewer operators, so it can under-report but will not produce a request the
/// server rejects.
/// </remarks>
public sealed class VatAccountFilter
{
}

/// <summary>
/// The properties e-conomic will sort <c>VatAccount</c> by.
/// </summary>
public sealed class VatAccountSort
{
}

/// <summary>
/// The properties e-conomic will filter <c>VatType</c> on, each typed to the
/// operators it accepts. Anything absent here is not filterable.
/// </summary>
/// <remarks>
/// Operator sets are inferred from each property's type: the legacy schemas record only
/// whether a property is filterable, not which operators it accepts. The inference errs
/// toward fewer operators, so it can under-report but will not produce a request the
/// server rejects.
/// </remarks>
public sealed class VatTypeFilter
{
}

/// <summary>
/// The properties e-conomic will sort <c>VatType</c> by.
/// </summary>
public sealed class VatTypeSort
{
}

/// <summary>
/// The properties e-conomic will filter <c>VatZone</c> on, each typed to the
/// operators it accepts. Anything absent here is not filterable.
/// </summary>
/// <remarks>
/// Operator sets are inferred from each property's type: the legacy schemas record only
/// whether a property is filterable, not which operators it accepts. The inference errs
/// toward fewer operators, so it can under-report but will not produce a request the
/// server rejects.
/// </remarks>
public sealed class VatZoneFilter
{
}

/// <summary>
/// The properties e-conomic will sort <c>VatZone</c> by.
/// </summary>
public sealed class VatZoneSort
{
}
