// <auto-generated>
//     Generated by tools/EConomic.SpecConverter (open-facade).
//     Regenerate after a spec refresh; do not edit by hand.
// </auto-generated>
#nullable enable

using EConomic.Querying;
using Raw = EConomic.Open.Generated.Accounts;

namespace EConomic.Open;

/// <summary>
/// A resource from <c>/Accounts</c>.
/// </summary>
/// <remarks>
/// The same shape is used to read, create and update: these services describe a resource once
/// and accept it back unchanged. Properties the server maintains are simply left unset.
/// </remarks>
public sealed record Account
{
    /// <summary>The <c>number</c> field.</summary>
    public required int Number { get; init; }

    /// <summary>The <c>name</c> field.</summary>
    public string? Name { get; init; }

    /// <summary>The <c>isBarred</c> field.</summary>
    public required bool IsBarred { get; init; }

    /// <summary>The <c>type</c> field.</summary>
    public required int Type { get; init; }

    /// <summary>The <c>vatAccountNumber</c> field.</summary>
    public int? VatAccountNumber { get; init; }

    /// <summary>The <c>contraAccountNumber</c> field.</summary>
    public int? ContraAccountNumber { get; init; }

    /// <summary>The <c>totalFromAccountNumber</c> field.</summary>
    public int? TotalFromAccountNumber { get; init; }

    /// <summary>The <c>openingAccountNumber</c> field.</summary>
    public int? OpeningAccountNumber { get; init; }

    /// <summary>The <c>realisationAccountNumber</c> field.</summary>
    public int? RealisationAccountNumber { get; init; }

    /// <summary>The <c>totalIntervals</c> field.</summary>
    public string? TotalIntervals { get; init; }

    /// <summary>The <c>isBlockedForDirectEntries</c> field.</summary>
    public required bool IsBlockedForDirectEntries { get; init; }

    /// <summary>The <c>isCredit</c> field.</summary>
    public bool? IsCredit { get; init; }

    /// <summary>The <c>currency</c> field.</summary>
    public string? Currency { get; init; }

    /// <summary>The <c>assetGroupNumber</c> field.</summary>
    public int? AssetGroupNumber { get; init; }

    /// <summary>The <c>displayNumber</c> field.</summary>
    public string? DisplayNumber { get; init; }

    /// <summary>The <c>isDepartmentMandatory</c> field.</summary>
    public required bool IsDepartmentMandatory { get; init; }

    /// <summary>The <c>isUnitMandatory</c> field.</summary>
    public required bool IsUnitMandatory { get; init; }

    /// <summary>The <c>keyFigureCodeNumber</c> field.</summary>
    public int? KeyFigureCodeNumber { get; init; }

    /// <summary>The <c>vatCode</c> field.</summary>
    public string? VatCode { get; init; }

    /// <summary>The <c>lastUpdated</c> field.</summary>
    public System.DateTimeOffset? LastUpdated { get; init; }

    /// <summary>The <c>note</c> field.</summary>
    public string? Note { get; init; }

    /// <summary>The <c>objectVersion</c> field.</summary>
    public string? ObjectVersion { get; init; }
}

/// <summary>
/// What <c>/Accounts</c> can be filtered on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class AccountFilter
{
    /// <summary>Maps to <c>number</c>.</summary>
    [EconomicField("number")]
    public NumericField<int> Number { get; } = null!;

    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public TextField Name { get; } = null!;

    /// <summary>Maps to <c>isBarred</c>.</summary>
    [EconomicField("isBarred")]
    public EqualityField<bool> IsBarred { get; } = null!;

    /// <summary>Maps to <c>isBlockedForDirectEntries</c>.</summary>
    [EconomicField("isBlockedForDirectEntries")]
    public EqualityField<bool> IsBlockedForDirectEntries { get; } = null!;

    /// <summary>Maps to <c>isCredit</c>.</summary>
    [EconomicField("isCredit")]
    public EqualityField<bool> IsCredit { get; } = null!;

    /// <summary>Maps to <c>currency</c>.</summary>
    [EconomicField("currency")]
    public TextField Currency { get; } = null!;

    /// <summary>Maps to <c>displayNumber</c>.</summary>
    [EconomicField("displayNumber")]
    public TextField DisplayNumber { get; } = null!;

    /// <summary>Maps to <c>isUnitMandatory</c>.</summary>
    [EconomicField("isUnitMandatory")]
    public EqualityField<bool> IsUnitMandatory { get; } = null!;

    /// <summary>Maps to <c>vatCode</c>.</summary>
    [EconomicField("vatCode")]
    public EqualityField<string> VatCode { get; } = null!;

    /// <summary>Maps to <c>lastUpdated</c>.</summary>
    [EconomicField("lastUpdated")]
    public ComparableField<System.DateTimeOffset> LastUpdated { get; } = null!;
}

/// <summary>
/// What <c>/Accounts</c> can be sorted on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class AccountSort
{
    /// <summary>Maps to <c>number</c>.</summary>
    [EconomicField("number")]
    public EconomicSortField Number { get; } = null!;

    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public EconomicSortField Name { get; } = null!;

    /// <summary>Maps to <c>currency</c>.</summary>
    [EconomicField("currency")]
    public EconomicSortField Currency { get; } = null!;

    /// <summary>Maps to <c>displayNumber</c>.</summary>
    [EconomicField("displayNumber")]
    public EconomicSortField DisplayNumber { get; } = null!;
}

/// <summary>Fetches <c>/Accounts</c> and maps it to <see cref="Account"/>.</summary>
internal sealed class AccountSource(Raw.AccountsClient client)
    : IEconomicOpenSource<Account>
{
    public async Task<EconomicCursorPage<Account>> GetCursorPageAsync(
        string? cursor, string? filter, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetAllAccountsAsync(cursor: cursor, filter: filter, cancellationToken: cancellationToken),
            "GET /Accounts").ConfigureAwait(false);

        var items = new List<Account>(response.Items?.Count ?? 0);
        foreach (var item in response.Items ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicCursorPage<Account>(items, response.Cursor);
    }

    public async Task<IReadOnlyList<Account>> GetPageAsync(
        string? filter, string? sort, int pageSize, int skipPages, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetPageOfAccountsAsync(filter: filter, sort: sort, pageSize: pageSize, skipPages: skipPages, cancellationToken: cancellationToken),
            "GET /Accounts/paged").ConfigureAwait(false);

        var items = new List<Account>(response?.Count ?? 0);
        foreach (var item in response ?? Array.Empty<Raw.Account>())
        {
            items.Add(Map(item));
        }

        return items;
    }

    public Task<int> CountAsync(string? filter, CancellationToken cancellationToken) =>
        OpenTransport.SendAsync(
            () => client.GetNumberOfAccountsAsync(filter: filter, cancellationToken: cancellationToken),
            "GET /Accounts/count");

    internal static Account Map(Raw.Account source) => new()
    {
        Number = source.Number,
        Name = source.Name,
        IsBarred = source.IsBarred,
        Type = source.Type,
        VatAccountNumber = source.VatAccountNumber,
        ContraAccountNumber = source.ContraAccountNumber,
        TotalFromAccountNumber = source.TotalFromAccountNumber,
        OpeningAccountNumber = source.OpeningAccountNumber,
        RealisationAccountNumber = source.RealisationAccountNumber,
        TotalIntervals = source.TotalIntervals,
        IsBlockedForDirectEntries = source.IsBlockedForDirectEntries,
        IsCredit = source.IsCredit,
        Currency = source.Currency,
        AssetGroupNumber = source.AssetGroupNumber,
        DisplayNumber = source.DisplayNumber,
        IsDepartmentMandatory = source.IsDepartmentMandatory,
        IsUnitMandatory = source.IsUnitMandatory,
        KeyFigureCodeNumber = source.KeyFigureCodeNumber,
        VatCode = source.VatCode,
        LastUpdated = source.LastUpdated,
        Note = source.Note,
        ObjectVersion = source.ObjectVersion,
    };

    internal static Raw.Account ToGenerated(Account source) => new()
    {
        Number = source.Number,
        Name = source.Name,
        IsBarred = source.IsBarred,
        Type = source.Type,
        VatAccountNumber = source.VatAccountNumber,
        ContraAccountNumber = source.ContraAccountNumber,
        TotalFromAccountNumber = source.TotalFromAccountNumber,
        OpeningAccountNumber = source.OpeningAccountNumber,
        RealisationAccountNumber = source.RealisationAccountNumber,
        TotalIntervals = source.TotalIntervals,
        IsBlockedForDirectEntries = source.IsBlockedForDirectEntries,
        IsCredit = source.IsCredit,
        Currency = source.Currency,
        AssetGroupNumber = source.AssetGroupNumber,
        DisplayNumber = source.DisplayNumber,
        IsDepartmentMandatory = source.IsDepartmentMandatory,
        IsUnitMandatory = source.IsUnitMandatory,
        KeyFigureCodeNumber = source.KeyFigureCodeNumber,
        VatCode = source.VatCode,
        LastUpdated = source.LastUpdated,
        Note = source.Note,
        ObjectVersion = source.ObjectVersion,
    };
}

/// <summary>
/// <c>/Accounts</c>, as a query and the writes the service supports.
/// </summary>
public sealed class AccountResource
{
    private readonly Raw.AccountsClient _client;

    internal AccountResource(System.Net.Http.HttpClient httpClient, System.Uri baseAddress)
    {
        _client = new Raw.AccountsClient(httpClient) { BaseUrl = baseAddress.ToString() };
    }

    /// <summary>This collection as a composable query.</summary>
    /// <returns>A query with no filter or ordering.</returns>
    public EconomicOpenQuery<Account, AccountFilter, AccountSort> AsQuery() => new(new AccountSource(_client));

    /// <summary>Restricts what is returned.</summary>
    /// <param name="predicate">A filter over the filterable properties.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<Account, AccountFilter, AccountSort> Where(System.Linq.Expressions.Expression<System.Func<AccountFilter, bool>> predicate) => AsQuery().Where(predicate);

    /// <summary>Restricts what is returned, using e-conomic's filter syntax directly.</summary>
    /// <param name="filter">A filter expression.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<Account, AccountFilter, AccountSort> WhereRaw(string filter) => AsQuery().WhereRaw(filter);

    /// <summary>Orders ascending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<Account, AccountFilter, AccountSort> OrderBy(System.Linq.Expressions.Expression<System.Func<AccountSort, EconomicSortField>> selector) => AsQuery().OrderBy(selector);

    /// <summary>Orders descending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<Account, AccountFilter, AccountSort> OrderByDescending(System.Linq.Expressions.Expression<System.Func<AccountSort, EconomicSortField>> selector) => AsQuery().OrderByDescending(selector);

    /// <summary>Sets how many items are fetched per request.</summary>
    /// <param name="pageSize">Items per page, up to 1000.</param>
    /// <returns>A query using that page size.</returns>
    public EconomicOpenQuery<Account, AccountFilter, AccountSort> WithPageSize(int pageSize) => AsQuery().WithPageSize(pageSize);

    /// <summary>Enumerates everything, following the cursor.</summary>
    /// <param name="cancellationToken">Cancels the enumeration.</param>
    /// <returns>The items.</returns>
    public System.Collections.Generic.IAsyncEnumerable<Account> AsAsyncEnumerable(CancellationToken cancellationToken = default) => AsQuery().AsAsyncEnumerable(cancellationToken);

    /// <summary>Counts everything in the collection.</summary>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The number of records.</returns>
    public Task<int> CountAsync(CancellationToken cancellationToken = default) => AsQuery().CountAsync(cancellationToken);

    /// <summary>Fetches one numbered page.</summary>
    /// <param name="pageIndex">Zero-based page index.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The page.</returns>
    public Task<IReadOnlyList<Account>> GetPageAsync(int pageIndex, CancellationToken cancellationToken = default) => AsQuery().GetPageAsync(pageIndex, cancellationToken);

    /// <summary>Fetches one record.</summary>
    /// <param name="number">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The record.</returns>
    public async Task<Account> GetAsync(int number, CancellationToken cancellationToken = default)
    {
        var response = await OpenTransport.SendAsync(
            () => _client.GetAccountByIdAsync(number: number, cancellationToken: cancellationToken),
            "GET /Accounts/{number}").ConfigureAwait(false);

        return AccountSource.Map(response);
    }

    /// <summary>Creates a record.</summary>
    /// <param name="item">The record to create, whose identifier you supply.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The identifier e-conomic stored it under.</returns>
    /// <remarks>
    /// The response carries the identifier and nothing else, so that is what this returns —
    /// unlike the legacy REST API, whose creates answer with the whole resource. Read it back
    /// with <c>GetAsync</c> if you need the stored record, which also gives you the
    /// <c>objectVersion</c> an update requires.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    public async Task<int?> CreateAsync(Account item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        var response = await OpenTransport.SendAsync(
            () => _client.CreateAccountAsync(body: AccountSource.ToGenerated(item), cancellationToken: cancellationToken),
            "POST /Accounts").ConfigureAwait(false);

        return response.Number;
    }

    /// <summary>Replaces a record.</summary>
    /// <param name="item">The replacement state, carrying the <c>objectVersion</c> that was read.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is replaced.</returns>
    /// <remarks>
    /// Updates are read-modify-write on this surface. The <c>objectVersion</c> from the record
    /// you read has to come back with it; a stale one, or none, is rejected with
    /// <see cref="Exceptions.EconomicConcurrencyException"/> and nothing is written.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    /// <exception cref="Exceptions.EconomicConcurrencyException">The record changed since it was read.</exception>
    public Task UpdateAsync(Account item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        return OpenTransport.SendAsync(
            () => _client.UpdateAccountByIdAsync(body: AccountSource.ToGenerated(item), cancellationToken: cancellationToken),
            "PUT /Accounts");
    }

    /// <summary>Deletes a record.</summary>
    /// <param name="number">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is gone.</returns>
    public Task DeleteAsync(int number, CancellationToken cancellationToken = default) =>
        OpenTransport.SendAsync(
            () => _client.DeleteAccountByIdAsync(number: number, cancellationToken: cancellationToken),
            "DELETE /Accounts/{number}");
}

/// <summary>
/// A resource from <c>/KeyFigureCodes</c>.
/// </summary>
/// <remarks>
/// The same shape is used to read, create and update: these services describe a resource once
/// and accept it back unchanged. Properties the server maintains are simply left unset.
/// </remarks>
public sealed record AccountKeyFigureCode
{
    /// <summary>The <c>number</c> field.</summary>
    public required int Number { get; init; }

    /// <summary>The <c>name</c> field.</summary>
    public required string Name { get; init; }

    /// <summary>The <c>sumFrom1</c> field.</summary>
    public required int SumFrom1 { get; init; }

    /// <summary>The <c>sum1Text</c> field.</summary>
    public required string Sum1Text { get; init; }

    /// <summary>The <c>sumFrom2</c> field.</summary>
    public required int SumFrom2 { get; init; }

    /// <summary>The <c>sum2Text</c> field.</summary>
    public required string Sum2Text { get; init; }

    /// <summary>The <c>isBalance</c> field.</summary>
    public required bool IsBalance { get; init; }
}

/// <summary>
/// What <c>/KeyFigureCodes</c> can be filtered on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class AccountKeyFigureCodeFilter
{
    /// <summary>Maps to <c>number</c>.</summary>
    [EconomicField("number")]
    public NumericField<int> Number { get; } = null!;

    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public TextField Name { get; } = null!;

    /// <summary>Maps to <c>sumFrom1</c>.</summary>
    [EconomicField("sumFrom1")]
    public NumericField<int> SumFrom1 { get; } = null!;

    /// <summary>Maps to <c>sumFrom2</c>.</summary>
    [EconomicField("sumFrom2")]
    public NumericField<int> SumFrom2 { get; } = null!;
}

/// <summary>
/// What <c>/KeyFigureCodes</c> can be sorted on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class AccountKeyFigureCodeSort
{
    /// <summary>Maps to <c>number</c>.</summary>
    [EconomicField("number")]
    public EconomicSortField Number { get; } = null!;

    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public EconomicSortField Name { get; } = null!;

    /// <summary>Maps to <c>sumFrom1</c>.</summary>
    [EconomicField("sumFrom1")]
    public EconomicSortField SumFrom1 { get; } = null!;

    /// <summary>Maps to <c>sumFrom2</c>.</summary>
    [EconomicField("sumFrom2")]
    public EconomicSortField SumFrom2 { get; } = null!;
}

/// <summary>Fetches <c>/KeyFigureCodes</c> and maps it to <see cref="AccountKeyFigureCode"/>.</summary>
internal sealed class AccountKeyFigureCodeSource(Raw.KeyFigureCodesClient client)
    : IEconomicOpenSource<AccountKeyFigureCode>
{
    public async Task<EconomicCursorPage<AccountKeyFigureCode>> GetCursorPageAsync(
        string? cursor, string? filter, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetAllKeyFigureCodeAsync(cursor: cursor, filter: filter, cancellationToken: cancellationToken),
            "GET /KeyFigureCodes").ConfigureAwait(false);

        var items = new List<AccountKeyFigureCode>(response.Items?.Count ?? 0);
        foreach (var item in response.Items ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicCursorPage<AccountKeyFigureCode>(items, response.Cursor);
    }

    public async Task<IReadOnlyList<AccountKeyFigureCode>> GetPageAsync(
        string? filter, string? sort, int pageSize, int skipPages, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetPageOfKeyFigureCodeAsync(filter: filter, sort: sort, pageSize: pageSize, skipPages: skipPages, cancellationToken: cancellationToken),
            "GET /KeyFigureCodes/paged").ConfigureAwait(false);

        var items = new List<AccountKeyFigureCode>(response?.Count ?? 0);
        foreach (var item in response ?? Array.Empty<Raw.KeyFigureCode>())
        {
            items.Add(Map(item));
        }

        return items;
    }

    public Task<int> CountAsync(string? filter, CancellationToken cancellationToken) =>
        OpenTransport.SendAsync(
            () => client.GetNumberOfKeyFigureCodeAsync(filter: filter, cancellationToken: cancellationToken),
            "GET /KeyFigureCodes/count");

    internal static AccountKeyFigureCode Map(Raw.KeyFigureCode source) => new()
    {
        Number = source.Number,
        Name = source.Name,
        SumFrom1 = source.SumFrom1,
        Sum1Text = source.Sum1Text,
        SumFrom2 = source.SumFrom2,
        Sum2Text = source.Sum2Text,
        IsBalance = source.IsBalance,
    };

    internal static Raw.KeyFigureCode ToGenerated(AccountKeyFigureCode source) => new()
    {
        Number = source.Number,
        Name = source.Name,
        SumFrom1 = source.SumFrom1,
        Sum1Text = source.Sum1Text,
        SumFrom2 = source.SumFrom2,
        Sum2Text = source.Sum2Text,
        IsBalance = source.IsBalance,
    };
}

/// <summary>
/// <c>/KeyFigureCodes</c>, as a query and the writes the service supports.
/// </summary>
public sealed class AccountKeyFigureCodeResource
{
    private readonly Raw.KeyFigureCodesClient _client;

    internal AccountKeyFigureCodeResource(System.Net.Http.HttpClient httpClient, System.Uri baseAddress)
    {
        _client = new Raw.KeyFigureCodesClient(httpClient) { BaseUrl = baseAddress.ToString() };
    }

    /// <summary>This collection as a composable query.</summary>
    /// <returns>A query with no filter or ordering.</returns>
    public EconomicOpenQuery<AccountKeyFigureCode, AccountKeyFigureCodeFilter, AccountKeyFigureCodeSort> AsQuery() => new(new AccountKeyFigureCodeSource(_client));

    /// <summary>Restricts what is returned.</summary>
    /// <param name="predicate">A filter over the filterable properties.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<AccountKeyFigureCode, AccountKeyFigureCodeFilter, AccountKeyFigureCodeSort> Where(System.Linq.Expressions.Expression<System.Func<AccountKeyFigureCodeFilter, bool>> predicate) => AsQuery().Where(predicate);

    /// <summary>Restricts what is returned, using e-conomic's filter syntax directly.</summary>
    /// <param name="filter">A filter expression.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<AccountKeyFigureCode, AccountKeyFigureCodeFilter, AccountKeyFigureCodeSort> WhereRaw(string filter) => AsQuery().WhereRaw(filter);

    /// <summary>Orders ascending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<AccountKeyFigureCode, AccountKeyFigureCodeFilter, AccountKeyFigureCodeSort> OrderBy(System.Linq.Expressions.Expression<System.Func<AccountKeyFigureCodeSort, EconomicSortField>> selector) => AsQuery().OrderBy(selector);

    /// <summary>Orders descending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<AccountKeyFigureCode, AccountKeyFigureCodeFilter, AccountKeyFigureCodeSort> OrderByDescending(System.Linq.Expressions.Expression<System.Func<AccountKeyFigureCodeSort, EconomicSortField>> selector) => AsQuery().OrderByDescending(selector);

    /// <summary>Sets how many items are fetched per request.</summary>
    /// <param name="pageSize">Items per page, up to 1000.</param>
    /// <returns>A query using that page size.</returns>
    public EconomicOpenQuery<AccountKeyFigureCode, AccountKeyFigureCodeFilter, AccountKeyFigureCodeSort> WithPageSize(int pageSize) => AsQuery().WithPageSize(pageSize);

    /// <summary>Enumerates everything, following the cursor.</summary>
    /// <param name="cancellationToken">Cancels the enumeration.</param>
    /// <returns>The items.</returns>
    public System.Collections.Generic.IAsyncEnumerable<AccountKeyFigureCode> AsAsyncEnumerable(CancellationToken cancellationToken = default) => AsQuery().AsAsyncEnumerable(cancellationToken);

    /// <summary>Counts everything in the collection.</summary>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The number of records.</returns>
    public Task<int> CountAsync(CancellationToken cancellationToken = default) => AsQuery().CountAsync(cancellationToken);

    /// <summary>Fetches one numbered page.</summary>
    /// <param name="pageIndex">Zero-based page index.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The page.</returns>
    public Task<IReadOnlyList<AccountKeyFigureCode>> GetPageAsync(int pageIndex, CancellationToken cancellationToken = default) => AsQuery().GetPageAsync(pageIndex, cancellationToken);

    /// <summary>Fetches one record.</summary>
    /// <param name="number">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The record.</returns>
    public async Task<AccountKeyFigureCode> GetAsync(int number, CancellationToken cancellationToken = default)
    {
        var response = await OpenTransport.SendAsync(
            () => _client.GetKeyFigureCodeByIdAsync(number: number, cancellationToken: cancellationToken),
            "GET /KeyFigureCodes/{number}").ConfigureAwait(false);

        return AccountKeyFigureCodeSource.Map(response);
    }
}

/// <summary>
/// A resource from <c>/TotalIntervals</c>.
/// </summary>
/// <remarks>
/// The same shape is used to read, create and update: these services describe a resource once
/// and accept it back unchanged. Properties the server maintains are simply left unset.
/// </remarks>
public sealed record AccountTotalInterval
{
    /// <summary>The <c>accountNumber</c> field.</summary>
    public required int AccountNumber { get; init; }

    /// <summary>The <c>fromAccountNumber</c> field.</summary>
    public required int FromAccountNumber { get; init; }

    /// <summary>The <c>toAccountNumber</c> field.</summary>
    public required int ToAccountNumber { get; init; }

    /// <summary>The <c>objectVersion</c> field.</summary>
    public string? ObjectVersion { get; init; }
}

/// <summary>
/// What <c>/TotalIntervals</c> can be filtered on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class AccountTotalIntervalFilter
{
    /// <summary>Maps to <c>accountNumber</c>.</summary>
    [EconomicField("accountNumber")]
    public NumericField<int> AccountNumber { get; } = null!;

    /// <summary>Maps to <c>fromAccountNumber</c>.</summary>
    [EconomicField("fromAccountNumber")]
    public NumericField<int> FromAccountNumber { get; } = null!;

    /// <summary>Maps to <c>toAccountNumber</c>.</summary>
    [EconomicField("toAccountNumber")]
    public NumericField<int> ToAccountNumber { get; } = null!;
}

/// <summary>
/// What <c>/TotalIntervals</c> can be sorted on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class AccountTotalIntervalSort
{
    /// <summary>Maps to <c>accountNumber</c>.</summary>
    [EconomicField("accountNumber")]
    public EconomicSortField AccountNumber { get; } = null!;

    /// <summary>Maps to <c>fromAccountNumber</c>.</summary>
    [EconomicField("fromAccountNumber")]
    public EconomicSortField FromAccountNumber { get; } = null!;

    /// <summary>Maps to <c>toAccountNumber</c>.</summary>
    [EconomicField("toAccountNumber")]
    public EconomicSortField ToAccountNumber { get; } = null!;
}

/// <summary>Fetches <c>/TotalIntervals</c> and maps it to <see cref="AccountTotalInterval"/>.</summary>
internal sealed class AccountTotalIntervalSource(Raw.TotalIntervalsClient client)
    : IEconomicOpenSource<AccountTotalInterval>
{
    public async Task<EconomicCursorPage<AccountTotalInterval>> GetCursorPageAsync(
        string? cursor, string? filter, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetAllTotalIntervalsAsync(cursor: cursor, filter: filter, cancellationToken: cancellationToken),
            "GET /TotalIntervals").ConfigureAwait(false);

        var items = new List<AccountTotalInterval>(response.Items?.Count ?? 0);
        foreach (var item in response.Items ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicCursorPage<AccountTotalInterval>(items, response.Cursor);
    }

    public async Task<IReadOnlyList<AccountTotalInterval>> GetPageAsync(
        string? filter, string? sort, int pageSize, int skipPages, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetPageOfTotalIntervalsAsync(filter: filter, sort: sort, pageSize: pageSize, skipPages: skipPages, cancellationToken: cancellationToken),
            "GET /TotalIntervals/paged").ConfigureAwait(false);

        var items = new List<AccountTotalInterval>(response?.Count ?? 0);
        foreach (var item in response ?? Array.Empty<Raw.TotalInterval>())
        {
            items.Add(Map(item));
        }

        return items;
    }

    public Task<int> CountAsync(string? filter, CancellationToken cancellationToken) =>
        OpenTransport.SendAsync(
            () => client.GetNumberOfTotalIntervalsAsync(filter: filter, cancellationToken: cancellationToken),
            "GET /TotalIntervals/count");

    internal static AccountTotalInterval Map(Raw.TotalInterval source) => new()
    {
        AccountNumber = source.AccountNumber,
        FromAccountNumber = source.FromAccountNumber,
        ToAccountNumber = source.ToAccountNumber,
        ObjectVersion = source.ObjectVersion,
    };

    internal static Raw.TotalInterval ToGenerated(AccountTotalInterval source) => new()
    {
        AccountNumber = source.AccountNumber,
        FromAccountNumber = source.FromAccountNumber,
        ToAccountNumber = source.ToAccountNumber,
        ObjectVersion = source.ObjectVersion,
    };
}

/// <summary>
/// <c>/TotalIntervals</c>, as a query and the writes the service supports.
/// </summary>
public sealed class AccountTotalIntervalResource
{
    private readonly Raw.TotalIntervalsClient _client;

    internal AccountTotalIntervalResource(System.Net.Http.HttpClient httpClient, System.Uri baseAddress)
    {
        _client = new Raw.TotalIntervalsClient(httpClient) { BaseUrl = baseAddress.ToString() };
    }

    /// <summary>This collection as a composable query.</summary>
    /// <returns>A query with no filter or ordering.</returns>
    public EconomicOpenQuery<AccountTotalInterval, AccountTotalIntervalFilter, AccountTotalIntervalSort> AsQuery() => new(new AccountTotalIntervalSource(_client));

    /// <summary>Restricts what is returned.</summary>
    /// <param name="predicate">A filter over the filterable properties.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<AccountTotalInterval, AccountTotalIntervalFilter, AccountTotalIntervalSort> Where(System.Linq.Expressions.Expression<System.Func<AccountTotalIntervalFilter, bool>> predicate) => AsQuery().Where(predicate);

    /// <summary>Restricts what is returned, using e-conomic's filter syntax directly.</summary>
    /// <param name="filter">A filter expression.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<AccountTotalInterval, AccountTotalIntervalFilter, AccountTotalIntervalSort> WhereRaw(string filter) => AsQuery().WhereRaw(filter);

    /// <summary>Orders ascending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<AccountTotalInterval, AccountTotalIntervalFilter, AccountTotalIntervalSort> OrderBy(System.Linq.Expressions.Expression<System.Func<AccountTotalIntervalSort, EconomicSortField>> selector) => AsQuery().OrderBy(selector);

    /// <summary>Orders descending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<AccountTotalInterval, AccountTotalIntervalFilter, AccountTotalIntervalSort> OrderByDescending(System.Linq.Expressions.Expression<System.Func<AccountTotalIntervalSort, EconomicSortField>> selector) => AsQuery().OrderByDescending(selector);

    /// <summary>Sets how many items are fetched per request.</summary>
    /// <param name="pageSize">Items per page, up to 1000.</param>
    /// <returns>A query using that page size.</returns>
    public EconomicOpenQuery<AccountTotalInterval, AccountTotalIntervalFilter, AccountTotalIntervalSort> WithPageSize(int pageSize) => AsQuery().WithPageSize(pageSize);

    /// <summary>Enumerates everything, following the cursor.</summary>
    /// <param name="cancellationToken">Cancels the enumeration.</param>
    /// <returns>The items.</returns>
    public System.Collections.Generic.IAsyncEnumerable<AccountTotalInterval> AsAsyncEnumerable(CancellationToken cancellationToken = default) => AsQuery().AsAsyncEnumerable(cancellationToken);

    /// <summary>Counts everything in the collection.</summary>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The number of records.</returns>
    public Task<int> CountAsync(CancellationToken cancellationToken = default) => AsQuery().CountAsync(cancellationToken);

    /// <summary>Fetches one numbered page.</summary>
    /// <param name="pageIndex">Zero-based page index.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The page.</returns>
    public Task<IReadOnlyList<AccountTotalInterval>> GetPageAsync(int pageIndex, CancellationToken cancellationToken = default) => AsQuery().GetPageAsync(pageIndex, cancellationToken);

    /// <summary>Fetches one record.</summary>
    /// <param name="number">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The record.</returns>
    public async Task<AccountTotalInterval> GetAsync(int number, CancellationToken cancellationToken = default)
    {
        var response = await OpenTransport.SendAsync(
            () => _client.GetAllAsync(number: number, cancellationToken: cancellationToken),
            "GET /TotalIntervals/{number}").ConfigureAwait(false);

        return AccountTotalIntervalSource.Map(response);
    }

    /// <summary>Creates a record.</summary>
    /// <param name="item">The record to create, whose identifier you supply.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The identifier e-conomic stored it under.</returns>
    /// <remarks>
    /// The response carries the identifier and nothing else, so that is what this returns —
    /// unlike the legacy REST API, whose creates answer with the whole resource. Read it back
    /// with <c>GetAsync</c> if you need the stored record, which also gives you the
    /// <c>objectVersion</c> an update requires.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    public async Task<int?> CreateAsync(AccountTotalInterval item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        var response = await OpenTransport.SendAsync(
            () => _client.CreateTotalIntervalAsync(body: AccountTotalIntervalSource.ToGenerated(item), cancellationToken: cancellationToken),
            "POST /TotalIntervals").ConfigureAwait(false);

        return response.AccountNumber;
    }

    /// <summary>Replaces a record.</summary>
    /// <param name="item">The replacement state, carrying the <c>objectVersion</c> that was read.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is replaced.</returns>
    /// <remarks>
    /// Updates are read-modify-write on this surface. The <c>objectVersion</c> from the record
    /// you read has to come back with it; a stale one, or none, is rejected with
    /// <see cref="Exceptions.EconomicConcurrencyException"/> and nothing is written.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    /// <exception cref="Exceptions.EconomicConcurrencyException">The record changed since it was read.</exception>
    public Task UpdateAsync(AccountTotalInterval item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        return OpenTransport.SendAsync(
            () => _client.UpdateTotalIntervalByIdAsync(body: AccountTotalIntervalSource.ToGenerated(item), cancellationToken: cancellationToken),
            "PUT /TotalIntervals");
    }
}
