// <auto-generated>
//     Generated by tools/EConomic.SpecConverter (open-facade).
//     Regenerate after a spec refresh; do not edit by hand.
// </auto-generated>
#nullable enable

using EConomic.Querying;
using Raw = EConomic.Open.Generated.AccountingYears;

namespace EConomic.Open;

/// <summary>
/// A resource from <c>/AccountingYears</c>.
/// </summary>
/// <remarks>
/// The same shape is used to read, create and update: these services describe a resource once
/// and accept it back unchanged. Properties the server maintains are simply left unset.
/// </remarks>
public sealed record AccountingYear
{
    /// <summary>The <c>year</c> field.</summary>
    public string? Year { get; init; }

    /// <summary>The <c>dateFrom</c> field.</summary>
    public required System.DateTimeOffset DateFrom { get; init; }

    /// <summary>The <c>dateTo</c> field.</summary>
    public required System.DateTimeOffset DateTo { get; init; }

    /// <summary>The <c>isClosed</c> field.</summary>
    public required bool IsClosed { get; init; }

    /// <summary>The <c>objectVersion</c> field.</summary>
    public string? ObjectVersion { get; init; }
}

/// <summary>
/// What <c>/AccountingYears</c> can be filtered on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class AccountingYearFilter
{
    /// <summary>Maps to <c>year</c>.</summary>
    [EconomicField("year")]
    public EqualityField<string> Year { get; } = null!;

    /// <summary>Maps to <c>dateFrom</c>.</summary>
    [EconomicField("dateFrom")]
    public ComparableField<System.DateTimeOffset> DateFrom { get; } = null!;

    /// <summary>Maps to <c>dateTo</c>.</summary>
    [EconomicField("dateTo")]
    public ComparableField<System.DateTimeOffset> DateTo { get; } = null!;

    /// <summary>Maps to <c>isClosed</c>.</summary>
    [EconomicField("isClosed")]
    public EqualityField<bool> IsClosed { get; } = null!;
}

/// <summary>
/// What <c>/AccountingYears</c> can be sorted on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class AccountingYearSort
{
    /// <summary>Maps to <c>year</c>.</summary>
    [EconomicField("year")]
    public EconomicSortField Year { get; } = null!;

    /// <summary>Maps to <c>dateFrom</c>.</summary>
    [EconomicField("dateFrom")]
    public EconomicSortField DateFrom { get; } = null!;

    /// <summary>Maps to <c>dateTo</c>.</summary>
    [EconomicField("dateTo")]
    public EconomicSortField DateTo { get; } = null!;
}

/// <summary>Fetches <c>/AccountingYears</c> and maps it to <see cref="AccountingYear"/>.</summary>
internal sealed class AccountingYearSource(Raw.AccountingYearsClient client)
    : IEconomicOpenSource<AccountingYear>
{
    public bool CanCursor => false;

    public bool CanPage => true;

    public async Task<EconomicCursorPage<AccountingYear>> GetCursorPageAsync(
        string? cursor, string? filter, CancellationToken cancellationToken)
    {
        await Task.CompletedTask.ConfigureAwait(false);
        throw new NotSupportedException(
            "e-conomic publishes no cursor listing for /AccountingYears. "
            + "CanCursor reports that, and the query pages classically instead.");
    }

    public async Task<IReadOnlyList<AccountingYear>> GetPageAsync(
        string? filter, string? sort, int pageSize, int skipPages, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetPageOfAccountingYearsAsync(filter: filter, sort: sort, pageSize: pageSize, skipPages: skipPages, cancellationToken: cancellationToken),
            "GET /AccountingYears/paged").ConfigureAwait(false);

        var items = new List<AccountingYear>(response?.Count ?? 0);
        foreach (var item in response ?? Array.Empty<Raw.AccountingYear>())
        {
            items.Add(Map(item));
        }

        return items;
    }

    public Task<int> CountAsync(string? filter, CancellationToken cancellationToken) =>
        OpenTransport.SendAsync(
            () => client.GetNumberOfAccountingYearsAsync(filter: filter, cancellationToken: cancellationToken),
            "GET /AccountingYears/count");

    internal static AccountingYear Map(Raw.AccountingYear source) => new()
    {
        Year = source.Year,
        DateFrom = source.DateFrom,
        DateTo = source.DateTo,
        IsClosed = source.IsClosed,
        ObjectVersion = source.ObjectVersion,
    };

    internal static Raw.AccountingYear ToGenerated(AccountingYear source) => new()
    {
        Year = source.Year,
        DateFrom = source.DateFrom,
        DateTo = source.DateTo,
        IsClosed = source.IsClosed,
        ObjectVersion = source.ObjectVersion,
    };
}

/// <summary>
/// <c>/AccountingYears</c>, as a query and the writes the service supports.
/// </summary>
public sealed class AccountingYearResource
{
    private readonly Raw.AccountingYearsClient _client;

    internal AccountingYearResource(System.Net.Http.HttpClient httpClient, System.Uri baseAddress)
    {
        _client = new Raw.AccountingYearsClient(httpClient) { BaseUrl = baseAddress.ToString() };
    }

    /// <summary>This collection as a composable query.</summary>
    /// <returns>A query with no filter or ordering.</returns>
    public EconomicOpenQuery<AccountingYear, AccountingYearFilter, AccountingYearSort> AsQuery() => new(new AccountingYearSource(_client));

    /// <summary>Restricts what is returned.</summary>
    /// <param name="predicate">A filter over the filterable properties.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<AccountingYear, AccountingYearFilter, AccountingYearSort> Where(System.Linq.Expressions.Expression<System.Func<AccountingYearFilter, bool>> predicate) => AsQuery().Where(predicate);

    /// <summary>Restricts what is returned, using e-conomic's filter syntax directly.</summary>
    /// <param name="filter">A filter expression.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<AccountingYear, AccountingYearFilter, AccountingYearSort> WhereRaw(string filter) => AsQuery().WhereRaw(filter);

    /// <summary>Orders ascending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<AccountingYear, AccountingYearFilter, AccountingYearSort> OrderBy(System.Linq.Expressions.Expression<System.Func<AccountingYearSort, EconomicSortField>> selector) => AsQuery().OrderBy(selector);

    /// <summary>Orders descending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<AccountingYear, AccountingYearFilter, AccountingYearSort> OrderByDescending(System.Linq.Expressions.Expression<System.Func<AccountingYearSort, EconomicSortField>> selector) => AsQuery().OrderByDescending(selector);

    /// <summary>Sets how many items are fetched per request.</summary>
    /// <param name="pageSize">Items per page, up to 1000.</param>
    /// <returns>A query using that page size.</returns>
    public EconomicOpenQuery<AccountingYear, AccountingYearFilter, AccountingYearSort> WithPageSize(int pageSize) => AsQuery().WithPageSize(pageSize);

    /// <summary>Enumerates everything, following the cursor.</summary>
    /// <param name="cancellationToken">Cancels the enumeration.</param>
    /// <returns>The items.</returns>
    public System.Collections.Generic.IAsyncEnumerable<AccountingYear> AsAsyncEnumerable(CancellationToken cancellationToken = default) => AsQuery().AsAsyncEnumerable(cancellationToken);

    /// <summary>Counts everything in the collection.</summary>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The number of records.</returns>
    public Task<int> CountAsync(CancellationToken cancellationToken = default) => AsQuery().CountAsync(cancellationToken);

    /// <summary>Fetches one numbered page.</summary>
    /// <param name="pageIndex">Zero-based page index.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The page.</returns>
    public Task<IReadOnlyList<AccountingYear>> GetPageAsync(int pageIndex, CancellationToken cancellationToken = default) => AsQuery().GetPageAsync(pageIndex, cancellationToken);

    /// <summary>Fetches one record.</summary>
    /// <param name="year">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The record.</returns>
    public async Task<AccountingYear> GetAsync(string year, CancellationToken cancellationToken = default)
    {
        var response = await OpenTransport.SendAsync(
            () => _client.GetSingleAccountingYearAsync(year: year, cancellationToken: cancellationToken),
            "GET /AccountingYears/{year}").ConfigureAwait(false);

        return AccountingYearSource.Map(response);
    }

    /// <summary>Creates a record.</summary>
    /// <param name="item">The record to create, whose identifier you supply.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The identifier e-conomic stored it under.</returns>
    /// <remarks>
    /// The response carries the identifier and nothing else, so that is what this returns —
    /// unlike the legacy REST API, whose creates answer with the whole resource. Read it back
    /// with <c>GetAsync</c> if you need the stored record, which also gives you the
    /// <c>objectVersion</c> an update requires.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    public async Task<string?> CreateAsync(AccountingYear item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        var response = await OpenTransport.SendAsync(
            () => _client.CreateAccountingYearAsync(body: AccountingYearSource.ToGenerated(item), cancellationToken: cancellationToken),
            "POST /AccountingYears").ConfigureAwait(false);

        return response.Year;
    }

    /// <summary>Deletes a record.</summary>
    /// <param name="year">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is gone.</returns>
    public Task DeleteAsync(string year, CancellationToken cancellationToken = default) =>
        OpenTransport.SendAsync(
            () => _client.DeleteAsync(year: year, cancellationToken: cancellationToken),
            "DELETE /AccountingYears/{year}");
}

/// <summary>
/// A resource from <c>/accountingYears/periods</c>.
/// </summary>
/// <remarks>
/// The same shape is used to read, create and update: these services describe a resource once
/// and accept it back unchanged. Properties the server maintains are simply left unset.
/// </remarks>
public sealed record AccountingYearPeriod
{
    /// <summary>The <c>periodNumber</c> field.</summary>
    public required int PeriodNumber { get; init; }

    /// <summary>The <c>year</c> field.</summary>
    public string? Year { get; init; }

    /// <summary>The <c>dateFrom</c> field.</summary>
    public required System.DateTimeOffset DateFrom { get; init; }

    /// <summary>The <c>dateTo</c> field.</summary>
    public required System.DateTimeOffset DateTo { get; init; }

    /// <summary>The <c>isClosed</c> field.</summary>
    public required bool IsClosed { get; init; }

    /// <summary>The <c>isBarred</c> field.</summary>
    public required bool IsBarred { get; init; }

    /// <summary>The <c>objectVersion</c> field.</summary>
    public string? ObjectVersion { get; init; }
}

/// <summary>
/// What <c>/accountingYears/periods</c> can be filtered on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class AccountingYearPeriodFilter
{
    /// <summary>Maps to <c>periodNumber</c>.</summary>
    [EconomicField("periodNumber")]
    public ComparableField<int> PeriodNumber { get; } = null!;

    /// <summary>Maps to <c>year</c>.</summary>
    [EconomicField("year")]
    public EqualityField<string> Year { get; } = null!;

    /// <summary>Maps to <c>dateFrom</c>.</summary>
    [EconomicField("dateFrom")]
    public ComparableField<System.DateTimeOffset> DateFrom { get; } = null!;

    /// <summary>Maps to <c>dateTo</c>.</summary>
    [EconomicField("dateTo")]
    public ComparableField<System.DateTimeOffset> DateTo { get; } = null!;
}

/// <summary>
/// What <c>/accountingYears/periods</c> can be sorted on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class AccountingYearPeriodSort
{
    /// <summary>Maps to <c>periodNumber</c>.</summary>
    [EconomicField("periodNumber")]
    public EconomicSortField PeriodNumber { get; } = null!;

    /// <summary>Maps to <c>year</c>.</summary>
    [EconomicField("year")]
    public EconomicSortField Year { get; } = null!;

    /// <summary>Maps to <c>dateFrom</c>.</summary>
    [EconomicField("dateFrom")]
    public EconomicSortField DateFrom { get; } = null!;

    /// <summary>Maps to <c>dateTo</c>.</summary>
    [EconomicField("dateTo")]
    public EconomicSortField DateTo { get; } = null!;
}

/// <summary>Fetches <c>/accountingYears/periods</c> and maps it to <see cref="AccountingYearPeriod"/>.</summary>
internal sealed class AccountingYearPeriodSource(Raw.AccountingYearPeriodsClient client)
    : IEconomicOpenSource<AccountingYearPeriod>
{
    public bool CanCursor => true;

    public bool CanPage => true;

    public async Task<EconomicCursorPage<AccountingYearPeriod>> GetCursorPageAsync(
        string? cursor, string? filter, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetAllAccountingYearPeriodsAsync(cursor: cursor, filter: filter, cancellationToken: cancellationToken),
            "GET /accountingYears/periods").ConfigureAwait(false);

        var items = new List<AccountingYearPeriod>(response.Items?.Count ?? 0);
        foreach (var item in response.Items ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicCursorPage<AccountingYearPeriod>(items, response.Cursor);
    }

    public async Task<IReadOnlyList<AccountingYearPeriod>> GetPageAsync(
        string? filter, string? sort, int pageSize, int skipPages, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetPageOfAccountingYearPeriodsAsync(filter: filter, sort: sort, pageSize: pageSize, skipPages: skipPages, cancellationToken: cancellationToken),
            "GET /accountingYears/periods/paged").ConfigureAwait(false);

        var items = new List<AccountingYearPeriod>(response?.Count ?? 0);
        foreach (var item in response ?? Array.Empty<Raw.AccountingYearPeriod>())
        {
            items.Add(Map(item));
        }

        return items;
    }

    public Task<int> CountAsync(string? filter, CancellationToken cancellationToken) =>
        OpenTransport.SendAsync(
            () => client.GetNumberOfAccountingYearPeriodsAsync(filter: filter, cancellationToken: cancellationToken),
            "GET /accountingYears/periods/count");

    internal static AccountingYearPeriod Map(Raw.AccountingYearPeriod source) => new()
    {
        PeriodNumber = source.PeriodNumber,
        Year = source.Year,
        DateFrom = source.DateFrom,
        DateTo = source.DateTo,
        IsClosed = source.IsClosed,
        IsBarred = source.IsBarred,
        ObjectVersion = source.ObjectVersion,
    };

    internal static Raw.AccountingYearPeriod ToGenerated(AccountingYearPeriod source) => new()
    {
        PeriodNumber = source.PeriodNumber,
        Year = source.Year,
        DateFrom = source.DateFrom,
        DateTo = source.DateTo,
        IsClosed = source.IsClosed,
        IsBarred = source.IsBarred,
        ObjectVersion = source.ObjectVersion,
    };
}

/// <summary>
/// <c>/accountingYears/periods</c>, as a query and the writes the service supports.
/// </summary>
public sealed class AccountingYearPeriodResource
{
    private readonly Raw.AccountingYearPeriodsClient _client;

    internal AccountingYearPeriodResource(System.Net.Http.HttpClient httpClient, System.Uri baseAddress)
    {
        _client = new Raw.AccountingYearPeriodsClient(httpClient) { BaseUrl = baseAddress.ToString() };
    }

    /// <summary>This collection as a composable query.</summary>
    /// <returns>A query with no filter or ordering.</returns>
    public EconomicOpenQuery<AccountingYearPeriod, AccountingYearPeriodFilter, AccountingYearPeriodSort> AsQuery() => new(new AccountingYearPeriodSource(_client));

    /// <summary>Restricts what is returned.</summary>
    /// <param name="predicate">A filter over the filterable properties.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<AccountingYearPeriod, AccountingYearPeriodFilter, AccountingYearPeriodSort> Where(System.Linq.Expressions.Expression<System.Func<AccountingYearPeriodFilter, bool>> predicate) => AsQuery().Where(predicate);

    /// <summary>Restricts what is returned, using e-conomic's filter syntax directly.</summary>
    /// <param name="filter">A filter expression.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<AccountingYearPeriod, AccountingYearPeriodFilter, AccountingYearPeriodSort> WhereRaw(string filter) => AsQuery().WhereRaw(filter);

    /// <summary>Orders ascending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<AccountingYearPeriod, AccountingYearPeriodFilter, AccountingYearPeriodSort> OrderBy(System.Linq.Expressions.Expression<System.Func<AccountingYearPeriodSort, EconomicSortField>> selector) => AsQuery().OrderBy(selector);

    /// <summary>Orders descending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<AccountingYearPeriod, AccountingYearPeriodFilter, AccountingYearPeriodSort> OrderByDescending(System.Linq.Expressions.Expression<System.Func<AccountingYearPeriodSort, EconomicSortField>> selector) => AsQuery().OrderByDescending(selector);

    /// <summary>Sets how many items are fetched per request.</summary>
    /// <param name="pageSize">Items per page, up to 1000.</param>
    /// <returns>A query using that page size.</returns>
    public EconomicOpenQuery<AccountingYearPeriod, AccountingYearPeriodFilter, AccountingYearPeriodSort> WithPageSize(int pageSize) => AsQuery().WithPageSize(pageSize);

    /// <summary>Enumerates everything, following the cursor.</summary>
    /// <param name="cancellationToken">Cancels the enumeration.</param>
    /// <returns>The items.</returns>
    public System.Collections.Generic.IAsyncEnumerable<AccountingYearPeriod> AsAsyncEnumerable(CancellationToken cancellationToken = default) => AsQuery().AsAsyncEnumerable(cancellationToken);

    /// <summary>Counts everything in the collection.</summary>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The number of records.</returns>
    public Task<int> CountAsync(CancellationToken cancellationToken = default) => AsQuery().CountAsync(cancellationToken);

    /// <summary>Fetches one numbered page.</summary>
    /// <param name="pageIndex">Zero-based page index.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The page.</returns>
    public Task<IReadOnlyList<AccountingYearPeriod>> GetPageAsync(int pageIndex, CancellationToken cancellationToken = default) => AsQuery().GetPageAsync(pageIndex, cancellationToken);

    /// <summary>Fetches one record.</summary>
    /// <param name="number">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The record.</returns>
    public async Task<AccountingYearPeriod> GetAsync(int number, CancellationToken cancellationToken = default)
    {
        var response = await OpenTransport.SendAsync(
            () => _client.GetAccountingYearPeriodByIdAsync(number: number, cancellationToken: cancellationToken),
            "GET /accountingYears/periods/{number}").ConfigureAwait(false);

        return AccountingYearPeriodSource.Map(response);
    }
}
