// <auto-generated>
//     Generated by tools/EConomic.SpecConverter (open-facade).
//     Regenerate after a spec refresh; do not edit by hand.
// </auto-generated>
#nullable enable

using EConomic.Querying;
using Raw = EConomic.Open.Generated.BookedEntries;

namespace EConomic.Open;

/// <summary>
/// A resource from <c>/booked-entries</c>.
/// </summary>
/// <remarks>
/// The same shape is used to read, create and update: these services describe a resource once
/// and accept it back unchanged. Properties the server maintains are simply left unset.
/// </remarks>
public sealed record BookedEntry
{
    /// <summary>The <c>entryNumber</c> field.</summary>
    public required int EntryNumber { get; init; }

    /// <summary>The <c>accountNumber</c> field.</summary>
    public required int AccountNumber { get; init; }

    /// <summary>The <c>projectNumber</c> field.</summary>
    public int? ProjectNumber { get; init; }

    /// <summary>The <c>amount</c> field.</summary>
    public double? Amount { get; init; }

    /// <summary>The <c>amountInBaseCurrency</c> field.</summary>
    public double? AmountInBaseCurrency { get; init; }

    /// <summary>The <c>currencyCode</c> field.</summary>
    public string? CurrencyCode { get; init; }

    /// <summary>The <c>date</c> field.</summary>
    public System.DateTimeOffset? Date { get; init; }

    /// <summary>The <c>dueDate</c> field.</summary>
    public System.DateTimeOffset? DueDate { get; init; }

    /// <summary>The <c>text</c> field.</summary>
    public string? Text { get; init; }

    /// <summary>The <c>type</c> field.</summary>
    /// <remarks>
    /// One of the values e-conomic publishes for it. The specification defines them as
    /// numbers and gives them no names, and the server sends the number, so the number is
    /// what this carries rather than a name invented here.
    /// </remarks>
    public required int Type { get; init; }

    /// <summary>The <c>vatAccountNumber</c> field.</summary>
    public string? VatAccountNumber { get; init; }

    /// <summary>The <c>voucherNumber</c> field.</summary>
    public int? VoucherNumber { get; init; }

    /// <summary>The <c>customerNumber</c> field.</summary>
    public int? CustomerNumber { get; init; }

    /// <summary>The <c>customerInvoiceNumber</c> field.</summary>
    public int? CustomerInvoiceNumber { get; init; }

    /// <summary>The <c>supplierNumber</c> field.</summary>
    public int? SupplierNumber { get; init; }

    /// <summary>The <c>supplierInvoiceNumber</c> field.</summary>
    public string? SupplierInvoiceNumber { get; init; }

    /// <summary>The <c>remainder</c> field.</summary>
    public double? Remainder { get; init; }

    /// <summary>The <c>objectVersion</c> field.</summary>
    public string? ObjectVersion { get; init; }
}

/// <summary>
/// What <c>/booked-entries</c> can be filtered on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class BookedEntryFilter
{
    /// <summary>Maps to <c>entryNumber</c>.</summary>
    [EconomicField("entryNumber")]
    public NumericField<int> EntryNumber { get; } = null!;

    /// <summary>Maps to <c>accountNumber</c>.</summary>
    [EconomicField("accountNumber")]
    public NumericField<int> AccountNumber { get; } = null!;

    /// <summary>Maps to <c>projectNumber</c>.</summary>
    [EconomicField("projectNumber")]
    public NumericField<int> ProjectNumber { get; } = null!;

    /// <summary>Maps to <c>amount</c>.</summary>
    [EconomicField("amount")]
    public ComparableField<double> Amount { get; } = null!;

    /// <summary>Maps to <c>amountInBaseCurrency</c>.</summary>
    [EconomicField("amountInBaseCurrency")]
    public ComparableField<double> AmountInBaseCurrency { get; } = null!;

    /// <summary>Maps to <c>currencyCode</c>.</summary>
    [EconomicField("currencyCode")]
    public EqualityField<string> CurrencyCode { get; } = null!;

    /// <summary>Maps to <c>date</c>.</summary>
    [EconomicField("date")]
    public ComparableField<System.DateTimeOffset> Date { get; } = null!;

    /// <summary>Maps to <c>dueDate</c>.</summary>
    [EconomicField("dueDate")]
    public ComparableField<System.DateTimeOffset> DueDate { get; } = null!;

    /// <summary>Maps to <c>text</c>.</summary>
    [EconomicField("text")]
    public TextField Text { get; } = null!;

    /// <summary>Maps to <c>type</c>.</summary>
    [EconomicField("type")]
    public EqualityField<int> Type { get; } = null!;

    /// <summary>Maps to <c>vatAccountNumber</c>.</summary>
    [EconomicField("vatAccountNumber")]
    public EqualityField<string> VatAccountNumber { get; } = null!;

    /// <summary>Maps to <c>voucherNumber</c>.</summary>
    [EconomicField("voucherNumber")]
    public NumericField<int> VoucherNumber { get; } = null!;

    /// <summary>Maps to <c>customerNumber</c>.</summary>
    [EconomicField("customerNumber")]
    public NumericField<int> CustomerNumber { get; } = null!;

    /// <summary>Maps to <c>customerInvoiceNumber</c>.</summary>
    [EconomicField("customerInvoiceNumber")]
    public NumericField<int> CustomerInvoiceNumber { get; } = null!;

    /// <summary>Maps to <c>supplierNumber</c>.</summary>
    [EconomicField("supplierNumber")]
    public NumericField<int> SupplierNumber { get; } = null!;

    /// <summary>Maps to <c>supplierInvoiceNumber</c>.</summary>
    [EconomicField("supplierInvoiceNumber")]
    public EqualityField<string> SupplierInvoiceNumber { get; } = null!;

    /// <summary>Maps to <c>remainder</c>.</summary>
    [EconomicField("remainder")]
    public NumericField<double> Remainder { get; } = null!;
}

/// <summary>
/// What <c>/booked-entries</c> can be sorted on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class BookedEntrySort
{
    /// <summary>Maps to <c>entryNumber</c>.</summary>
    [EconomicField("entryNumber")]
    public EconomicSortField EntryNumber { get; } = null!;

    /// <summary>Maps to <c>accountNumber</c>.</summary>
    [EconomicField("accountNumber")]
    public EconomicSortField AccountNumber { get; } = null!;

    /// <summary>Maps to <c>projectNumber</c>.</summary>
    [EconomicField("projectNumber")]
    public EconomicSortField ProjectNumber { get; } = null!;

    /// <summary>Maps to <c>amount</c>.</summary>
    [EconomicField("amount")]
    public EconomicSortField Amount { get; } = null!;

    /// <summary>Maps to <c>amountInBaseCurrency</c>.</summary>
    [EconomicField("amountInBaseCurrency")]
    public EconomicSortField AmountInBaseCurrency { get; } = null!;

    /// <summary>Maps to <c>currencyCode</c>.</summary>
    [EconomicField("currencyCode")]
    public EconomicSortField CurrencyCode { get; } = null!;

    /// <summary>Maps to <c>date</c>.</summary>
    [EconomicField("date")]
    public EconomicSortField Date { get; } = null!;

    /// <summary>Maps to <c>dueDate</c>.</summary>
    [EconomicField("dueDate")]
    public EconomicSortField DueDate { get; } = null!;

    /// <summary>Maps to <c>type</c>.</summary>
    [EconomicField("type")]
    public EconomicSortField Type { get; } = null!;

    /// <summary>Maps to <c>vatAccountNumber</c>.</summary>
    [EconomicField("vatAccountNumber")]
    public EconomicSortField VatAccountNumber { get; } = null!;

    /// <summary>Maps to <c>customerNumber</c>.</summary>
    [EconomicField("customerNumber")]
    public EconomicSortField CustomerNumber { get; } = null!;
}

/// <summary>Fetches <c>/booked-entries</c> and maps it to <see cref="BookedEntry"/>.</summary>
internal sealed class BookedEntrySource(Raw.BookedEntriesClient client)
    : IEconomicOpenSource<BookedEntry>
{
    public bool CanCursor => true;

    public bool CanPage => true;

    public async Task<EconomicCursorPage<BookedEntry>> GetCursorPageAsync(
        string? cursor, string? filter, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetAllBookedEntriesAsync(cursor: cursor, filter: filter, cancellationToken: cancellationToken),
            "GET /booked-entries").ConfigureAwait(false);

        var items = new List<BookedEntry>(response.Items?.Count ?? 0);
        foreach (var item in response.Items ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicCursorPage<BookedEntry>(items, response.Cursor);
    }

    public async Task<IReadOnlyList<BookedEntry>> GetPageAsync(
        string? filter, string? sort, int pageSize, int skipPages, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetPageOfBookedEntriesAsync(filter: filter, sort: sort, pageSize: pageSize, skipPages: skipPages, cancellationToken: cancellationToken),
            "GET /booked-entries/paged").ConfigureAwait(false);

        var items = new List<BookedEntry>(response?.Count ?? 0);
        foreach (var item in response ?? Array.Empty<Raw.BookedEntry>())
        {
            items.Add(Map(item));
        }

        return items;
    }

    public Task<int> CountAsync(string? filter, CancellationToken cancellationToken) =>
        OpenTransport.SendAsync(
            () => client.GetNumberOfBookedEntriesAsync(filter: filter, cancellationToken: cancellationToken),
            "GET /booked-entries/count");

    internal static BookedEntry Map(Raw.BookedEntry source) => new()
    {
        EntryNumber = source.EntryNumber,
        AccountNumber = source.AccountNumber,
        ProjectNumber = source.ProjectNumber,
        Amount = source.Amount,
        AmountInBaseCurrency = source.AmountInBaseCurrency,
        CurrencyCode = source.CurrencyCode,
        Date = source.Date,
        DueDate = source.DueDate,
        Text = source.Text,
        Type = (int)source.Type,
        VatAccountNumber = source.VatAccountNumber,
        VoucherNumber = source.VoucherNumber,
        CustomerNumber = source.CustomerNumber,
        CustomerInvoiceNumber = source.CustomerInvoiceNumber,
        SupplierNumber = source.SupplierNumber,
        SupplierInvoiceNumber = source.SupplierInvoiceNumber,
        Remainder = source.Remainder,
        ObjectVersion = source.ObjectVersion,
    };

    internal static Raw.BookedEntry ToGenerated(BookedEntry source) => new()
    {
        EntryNumber = source.EntryNumber,
        AccountNumber = source.AccountNumber,
        ProjectNumber = source.ProjectNumber,
        Amount = source.Amount,
        AmountInBaseCurrency = source.AmountInBaseCurrency,
        CurrencyCode = source.CurrencyCode,
        Date = source.Date,
        DueDate = source.DueDate,
        Text = source.Text,
        Type = (Raw.EntryTypeNames)source.Type,
        VatAccountNumber = source.VatAccountNumber,
        VoucherNumber = source.VoucherNumber,
        CustomerNumber = source.CustomerNumber,
        CustomerInvoiceNumber = source.CustomerInvoiceNumber,
        SupplierNumber = source.SupplierNumber,
        SupplierInvoiceNumber = source.SupplierInvoiceNumber,
        Remainder = source.Remainder,
        ObjectVersion = source.ObjectVersion,
    };
}

/// <summary>
/// <c>/booked-entries</c>, as a query and the writes the service supports.
/// </summary>
public sealed class BookedEntryResource
{
    private readonly Raw.BookedEntriesClient _client;

    internal BookedEntryResource(System.Net.Http.HttpClient httpClient, System.Uri baseAddress)
    {
        _client = new Raw.BookedEntriesClient(httpClient) { BaseUrl = baseAddress.ToString() };
    }

    /// <summary>This collection as a composable query.</summary>
    /// <returns>A query with no filter or ordering.</returns>
    public EconomicOpenQuery<BookedEntry, BookedEntryFilter, BookedEntrySort> AsQuery() => new(new BookedEntrySource(_client));

    /// <summary>Restricts what is returned.</summary>
    /// <param name="predicate">A filter over the filterable properties.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<BookedEntry, BookedEntryFilter, BookedEntrySort> Where(System.Linq.Expressions.Expression<System.Func<BookedEntryFilter, bool>> predicate) => AsQuery().Where(predicate);

    /// <summary>Restricts what is returned, using e-conomic's filter syntax directly.</summary>
    /// <param name="filter">A filter expression.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<BookedEntry, BookedEntryFilter, BookedEntrySort> WhereRaw(string filter) => AsQuery().WhereRaw(filter);

    /// <summary>Orders ascending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<BookedEntry, BookedEntryFilter, BookedEntrySort> OrderBy(System.Linq.Expressions.Expression<System.Func<BookedEntrySort, EconomicSortField>> selector) => AsQuery().OrderBy(selector);

    /// <summary>Orders descending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<BookedEntry, BookedEntryFilter, BookedEntrySort> OrderByDescending(System.Linq.Expressions.Expression<System.Func<BookedEntrySort, EconomicSortField>> selector) => AsQuery().OrderByDescending(selector);

    /// <summary>Sets how many items are fetched per request.</summary>
    /// <param name="pageSize">Items per page, up to 1000.</param>
    /// <returns>A query using that page size.</returns>
    public EconomicOpenQuery<BookedEntry, BookedEntryFilter, BookedEntrySort> WithPageSize(int pageSize) => AsQuery().WithPageSize(pageSize);

    /// <summary>Enumerates everything, following the cursor.</summary>
    /// <param name="cancellationToken">Cancels the enumeration.</param>
    /// <returns>The items.</returns>
    public System.Collections.Generic.IAsyncEnumerable<BookedEntry> AsAsyncEnumerable(CancellationToken cancellationToken = default) => AsQuery().AsAsyncEnumerable(cancellationToken);

    /// <summary>Counts everything in the collection.</summary>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The number of records.</returns>
    public Task<int> CountAsync(CancellationToken cancellationToken = default) => AsQuery().CountAsync(cancellationToken);

    /// <summary>Fetches one numbered page.</summary>
    /// <param name="pageIndex">Zero-based page index.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The page.</returns>
    public Task<IReadOnlyList<BookedEntry>> GetPageAsync(int pageIndex, CancellationToken cancellationToken = default) => AsQuery().GetPageAsync(pageIndex, cancellationToken);
}

/// <summary>
/// A resource from <c>/booked-entries/matched-pairs</c>.
/// </summary>
/// <remarks>
/// The same shape is used to read, create and update: these services describe a resource once
/// and accept it back unchanged. Properties the server maintains are simply left unset.
/// </remarks>
public sealed record MatchedBookedEntriesPair
{
    /// <summary>The <c>fromEntry</c> field.</summary>
    public int? FromEntry { get; init; }

    /// <summary>The <c>fromEntryDate</c> field.</summary>
    public System.DateTimeOffset? FromEntryDate { get; init; }

    /// <summary>The <c>fromEntryAmount</c> field.</summary>
    public double? FromEntryAmount { get; init; }

    /// <summary>The <c>fromEntryAmountDKK</c> field.</summary>
    public double? FromEntryAmountDKK { get; init; }

    /// <summary>The <c>toEntry</c> field.</summary>
    public int? ToEntry { get; init; }

    /// <summary>The <c>toEntryDate</c> field.</summary>
    public System.DateTimeOffset? ToEntryDate { get; init; }

    /// <summary>The <c>toEntryAmount</c> field.</summary>
    public double? ToEntryAmount { get; init; }

    /// <summary>The <c>toEntryAmountDKK</c> field.</summary>
    public double? ToEntryAmountDKK { get; init; }
}

/// <summary>
/// What <c>/booked-entries/matched-pairs</c> can be filtered on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class MatchedBookedEntriesPairFilter
{
    /// <summary>Maps to <c>fromEntry</c>.</summary>
    [EconomicField("fromEntry")]
    public NumericField<int> FromEntry { get; } = null!;

    /// <summary>Maps to <c>fromEntryDate</c>.</summary>
    [EconomicField("fromEntryDate")]
    public ComparableField<System.DateTimeOffset> FromEntryDate { get; } = null!;

    /// <summary>Maps to <c>toEntry</c>.</summary>
    [EconomicField("toEntry")]
    public NumericField<int> ToEntry { get; } = null!;

    /// <summary>Maps to <c>toEntryDate</c>.</summary>
    [EconomicField("toEntryDate")]
    public ComparableField<System.DateTimeOffset> ToEntryDate { get; } = null!;
}

/// <summary>
/// What <c>/booked-entries/matched-pairs</c> can be sorted on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class MatchedBookedEntriesPairSort
{
}

/// <summary>Fetches <c>/booked-entries/matched-pairs</c> and maps it to <see cref="MatchedBookedEntriesPair"/>.</summary>
internal sealed class MatchedBookedEntriesPairSource(Raw.MatchedBookedEntriesPairsClient client)
    : IEconomicOpenSource<MatchedBookedEntriesPair>
{
    public bool CanCursor => true;

    public bool CanPage => false;

    public async Task<EconomicCursorPage<MatchedBookedEntriesPair>> GetCursorPageAsync(
        string? cursor, string? filter, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetMatchedBookedEntriesAsync(cursor: cursor, filter: filter, cancellationToken: cancellationToken),
            "GET /booked-entries/matched-pairs").ConfigureAwait(false);

        var items = new List<MatchedBookedEntriesPair>(response.Items?.Count ?? 0);
        foreach (var item in response.Items ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicCursorPage<MatchedBookedEntriesPair>(items, response.Cursor);
    }

    public async Task<IReadOnlyList<MatchedBookedEntriesPair>> GetPageAsync(
        string? filter, string? sort, int pageSize, int skipPages, CancellationToken cancellationToken)
    {
        await Task.CompletedTask.ConfigureAwait(false);
        throw new NotSupportedException(
            "e-conomic publishes no paged listing for /booked-entries/matched-pairs, so it cannot be "
            + "paged or sorted. Enumerate it with AsAsyncEnumerable, which follows the cursor.");
    }

    public Task<int> CountAsync(string? filter, CancellationToken cancellationToken) =>
        throw new NotSupportedException(
            "e-conomic publishes no count endpoint for /booked-entries/matched-pairs, so this collection "
            + "cannot be counted. Enumerate it, or count a collection that publishes one.");

    internal static MatchedBookedEntriesPair Map(Raw.MatchedBookedEntriesPair source) => new()
    {
        FromEntry = source.FromEntry,
        FromEntryDate = source.FromEntryDate,
        FromEntryAmount = source.FromEntryAmount,
        FromEntryAmountDKK = source.FromEntryAmountDKK,
        ToEntry = source.ToEntry,
        ToEntryDate = source.ToEntryDate,
        ToEntryAmount = source.ToEntryAmount,
        ToEntryAmountDKK = source.ToEntryAmountDKK,
    };

    internal static Raw.MatchedBookedEntriesPair ToGenerated(MatchedBookedEntriesPair source) => new()
    {
        FromEntry = source.FromEntry,
        FromEntryDate = source.FromEntryDate,
        FromEntryAmount = source.FromEntryAmount,
        FromEntryAmountDKK = source.FromEntryAmountDKK,
        ToEntry = source.ToEntry,
        ToEntryDate = source.ToEntryDate,
        ToEntryAmount = source.ToEntryAmount,
        ToEntryAmountDKK = source.ToEntryAmountDKK,
    };
}

/// <summary>
/// <c>/booked-entries/matched-pairs</c>, as a query and the writes the service supports.
/// </summary>
public sealed class MatchedBookedEntriesPairResource
{
    private readonly Raw.MatchedBookedEntriesPairsClient _client;

    internal MatchedBookedEntriesPairResource(System.Net.Http.HttpClient httpClient, System.Uri baseAddress)
    {
        _client = new Raw.MatchedBookedEntriesPairsClient(httpClient) { BaseUrl = baseAddress.ToString() };
    }

    /// <summary>This collection as a composable query.</summary>
    /// <returns>A query with no filter or ordering.</returns>
    public EconomicOpenQuery<MatchedBookedEntriesPair, MatchedBookedEntriesPairFilter, MatchedBookedEntriesPairSort> AsQuery() => new(new MatchedBookedEntriesPairSource(_client));

    /// <summary>Restricts what is returned.</summary>
    /// <param name="predicate">A filter over the filterable properties.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<MatchedBookedEntriesPair, MatchedBookedEntriesPairFilter, MatchedBookedEntriesPairSort> Where(System.Linq.Expressions.Expression<System.Func<MatchedBookedEntriesPairFilter, bool>> predicate) => AsQuery().Where(predicate);

    /// <summary>Restricts what is returned, using e-conomic's filter syntax directly.</summary>
    /// <param name="filter">A filter expression.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<MatchedBookedEntriesPair, MatchedBookedEntriesPairFilter, MatchedBookedEntriesPairSort> WhereRaw(string filter) => AsQuery().WhereRaw(filter);

    /// <summary>Sets how many items are fetched per request.</summary>
    /// <param name="pageSize">Items per page, up to 1000.</param>
    /// <returns>A query using that page size.</returns>
    public EconomicOpenQuery<MatchedBookedEntriesPair, MatchedBookedEntriesPairFilter, MatchedBookedEntriesPairSort> WithPageSize(int pageSize) => AsQuery().WithPageSize(pageSize);

    /// <summary>Enumerates everything, following the cursor.</summary>
    /// <param name="cancellationToken">Cancels the enumeration.</param>
    /// <returns>The items.</returns>
    public System.Collections.Generic.IAsyncEnumerable<MatchedBookedEntriesPair> AsAsyncEnumerable(CancellationToken cancellationToken = default) => AsQuery().AsAsyncEnumerable(cancellationToken);
}
