// <auto-generated>
//     Generated by tools/EConomic.SpecConverter (open-facade).
//     Regenerate after a spec refresh; do not edit by hand.
// </auto-generated>
#nullable enable

using EConomic.Querying;
using Raw = EConomic.Open.Generated.Budgets;

namespace EConomic.Open;

/// <summary>
/// A resource from <c>/budget-figures</c>.
/// </summary>
/// <remarks>
/// The same shape is used to read, create and update: these services describe a resource once
/// and accept it back unchanged. Properties the server maintains are simply left unset.
/// </remarks>
public sealed record BudgetFigure
{
    /// <summary>The <c>number</c> field.</summary>
    public int? Number { get; init; }

    /// <summary>The <c>accountNumber</c> field.</summary>
    public required int AccountNumber { get; init; }

    /// <summary>The <c>fromDate</c> field.</summary>
    public required System.DateTimeOffset FromDate { get; init; }

    /// <summary>The <c>toDate</c> field.</summary>
    public required System.DateTimeOffset ToDate { get; init; }

    /// <summary>The <c>amountDefaultCurrency</c> field.</summary>
    public required double AmountDefaultCurrency { get; init; }

    /// <summary>The <c>text</c> field.</summary>
    public string? Text { get; init; }

    /// <summary>The <c>objectVersion</c> field.</summary>
    public string? ObjectVersion { get; init; }
}

/// <summary>
/// What <c>/budget-figures</c> can be filtered on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class BudgetFigureFilter
{
    /// <summary>Maps to <c>number</c>.</summary>
    [EconomicField("number")]
    public NumericField<int> Number { get; } = null!;

    /// <summary>Maps to <c>accountNumber</c>.</summary>
    [EconomicField("accountNumber")]
    public NumericField<int> AccountNumber { get; } = null!;

    /// <summary>Maps to <c>fromDate</c>.</summary>
    [EconomicField("fromDate")]
    public ComparableField<System.DateTimeOffset> FromDate { get; } = null!;

    /// <summary>Maps to <c>toDate</c>.</summary>
    [EconomicField("toDate")]
    public ComparableField<System.DateTimeOffset> ToDate { get; } = null!;

    /// <summary>Maps to <c>amountDefaultCurrency</c>.</summary>
    [EconomicField("amountDefaultCurrency")]
    public NumericField<double> AmountDefaultCurrency { get; } = null!;
}

/// <summary>
/// What <c>/budget-figures</c> can be sorted on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class BudgetFigureSort
{
    /// <summary>Maps to <c>number</c>.</summary>
    [EconomicField("number")]
    public EconomicSortField Number { get; } = null!;
}

/// <summary>Fetches <c>/budget-figures</c> and maps it to <see cref="BudgetFigure"/>.</summary>
internal sealed class BudgetFigureSource(Raw.BudgetFiguresClient client)
    : IEconomicOpenSource<BudgetFigure>
{
    public bool CanCursor => true;

    public bool CanPage => true;

    public async Task<EconomicCursorPage<BudgetFigure>> GetCursorPageAsync(
        string? cursor, string? filter, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetAllBudgetFiguresAsync(cursor: cursor, filter: filter, cancellationToken: cancellationToken),
            "GET /budget-figures").ConfigureAwait(false);

        var items = new List<BudgetFigure>(response.Items?.Count ?? 0);
        foreach (var item in response.Items ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicCursorPage<BudgetFigure>(items, response.Cursor);
    }

    public async Task<IReadOnlyList<BudgetFigure>> GetPageAsync(
        string? filter, string? sort, int pageSize, int skipPages, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetPageOfBudgetFiguresAsync(filter: filter, sort: sort, pageSize: pageSize, skipPages: skipPages, cancellationToken: cancellationToken),
            "GET /budget-figures/paged").ConfigureAwait(false);

        var items = new List<BudgetFigure>(response?.Count ?? 0);
        foreach (var item in response ?? Array.Empty<Raw.BudgetFigure>())
        {
            items.Add(Map(item));
        }

        return items;
    }

    public Task<int> CountAsync(string? filter, CancellationToken cancellationToken) =>
        OpenTransport.SendAsync(
            () => client.GetNumberOfBudgetFiguresAsync(filter: filter, cancellationToken: cancellationToken),
            "GET /budget-figures/count");

    internal static BudgetFigure Map(Raw.BudgetFigure source) => new()
    {
        Number = source.Number,
        AccountNumber = source.AccountNumber,
        FromDate = source.FromDate,
        ToDate = source.ToDate,
        AmountDefaultCurrency = source.AmountDefaultCurrency,
        Text = source.Text,
        ObjectVersion = source.ObjectVersion,
    };

    internal static Raw.BudgetFigure ToGenerated(BudgetFigure source) => new()
    {
        Number = source.Number,
        AccountNumber = source.AccountNumber,
        FromDate = source.FromDate,
        ToDate = source.ToDate,
        AmountDefaultCurrency = source.AmountDefaultCurrency,
        Text = source.Text,
        ObjectVersion = source.ObjectVersion,
    };
}

/// <summary>
/// <c>/budget-figures</c>, as a query and the writes the service supports.
/// </summary>
public sealed class BudgetFigureResource
{
    private readonly Raw.BudgetFiguresClient _client;

    internal BudgetFigureResource(System.Net.Http.HttpClient httpClient, System.Uri baseAddress)
    {
        _client = new Raw.BudgetFiguresClient(httpClient) { BaseUrl = baseAddress.ToString() };
    }

    /// <summary>This collection as a composable query.</summary>
    /// <returns>A query with no filter or ordering.</returns>
    public EconomicOpenQuery<BudgetFigure, BudgetFigureFilter, BudgetFigureSort> AsQuery() => new(new BudgetFigureSource(_client));

    /// <summary>Restricts what is returned.</summary>
    /// <param name="predicate">A filter over the filterable properties.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<BudgetFigure, BudgetFigureFilter, BudgetFigureSort> Where(System.Linq.Expressions.Expression<System.Func<BudgetFigureFilter, bool>> predicate) => AsQuery().Where(predicate);

    /// <summary>Restricts what is returned, using e-conomic's filter syntax directly.</summary>
    /// <param name="filter">A filter expression.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<BudgetFigure, BudgetFigureFilter, BudgetFigureSort> WhereRaw(string filter) => AsQuery().WhereRaw(filter);

    /// <summary>Orders ascending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<BudgetFigure, BudgetFigureFilter, BudgetFigureSort> OrderBy(System.Linq.Expressions.Expression<System.Func<BudgetFigureSort, EconomicSortField>> selector) => AsQuery().OrderBy(selector);

    /// <summary>Orders descending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<BudgetFigure, BudgetFigureFilter, BudgetFigureSort> OrderByDescending(System.Linq.Expressions.Expression<System.Func<BudgetFigureSort, EconomicSortField>> selector) => AsQuery().OrderByDescending(selector);

    /// <summary>Sets how many items are fetched per request.</summary>
    /// <param name="pageSize">Items per page, up to 1000.</param>
    /// <returns>A query using that page size.</returns>
    public EconomicOpenQuery<BudgetFigure, BudgetFigureFilter, BudgetFigureSort> WithPageSize(int pageSize) => AsQuery().WithPageSize(pageSize);

    /// <summary>Enumerates everything, following the cursor.</summary>
    /// <param name="cancellationToken">Cancels the enumeration.</param>
    /// <returns>The items.</returns>
    public System.Collections.Generic.IAsyncEnumerable<BudgetFigure> AsAsyncEnumerable(CancellationToken cancellationToken = default) => AsQuery().AsAsyncEnumerable(cancellationToken);

    /// <summary>Counts everything in the collection.</summary>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The number of records.</returns>
    public Task<int> CountAsync(CancellationToken cancellationToken = default) => AsQuery().CountAsync(cancellationToken);

    /// <summary>Fetches one numbered page.</summary>
    /// <param name="pageIndex">Zero-based page index.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The page.</returns>
    public Task<IReadOnlyList<BudgetFigure>> GetPageAsync(int pageIndex, CancellationToken cancellationToken = default) => AsQuery().GetPageAsync(pageIndex, cancellationToken);

    /// <summary>Fetches one record.</summary>
    /// <param name="number">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The record.</returns>
    public async Task<BudgetFigure> GetAsync(int number, CancellationToken cancellationToken = default)
    {
        var response = await OpenTransport.SendAsync(
            () => _client.GetBudgetFigureByIdAsync(number: number, cancellationToken: cancellationToken),
            "GET /budget-figures/{number}").ConfigureAwait(false);

        return BudgetFigureSource.Map(response);
    }

    /// <summary>Creates a record.</summary>
    /// <param name="item">The record to create, whose identifier you supply.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The identifier e-conomic stored it under.</returns>
    /// <remarks>
    /// The response carries the identifier and nothing else, so that is what this returns —
    /// unlike the legacy REST API, whose creates answer with the whole resource. Read it back
    /// with <c>GetAsync</c> if you need the stored record, which also gives you the
    /// <c>objectVersion</c> an update requires.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    public async Task<int?> CreateAsync(BudgetFigure item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        var response = await OpenTransport.SendAsync(
            () => _client.CreateBudgetFigureAsync(body: BudgetFigureSource.ToGenerated(item), cancellationToken: cancellationToken),
            "POST /budget-figures").ConfigureAwait(false);

        return response.Number;
    }

    /// <summary>Replaces a record.</summary>
    /// <param name="item">The replacement state, carrying the <c>objectVersion</c> that was read.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is replaced.</returns>
    /// <remarks>
    /// Updates are read-modify-write on this surface. The <c>objectVersion</c> from the record
    /// you read has to come back with it; a stale one, or none, is rejected with
    /// <see cref="Exceptions.EconomicConcurrencyException"/> and nothing is written.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    /// <exception cref="Exceptions.EconomicConcurrencyException">The record changed since it was read.</exception>
    public Task UpdateAsync(BudgetFigure item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        return OpenTransport.SendAsync(
            () => _client.UpdateBudgetFigureByIdAsync(body: BudgetFigureSource.ToGenerated(item), cancellationToken: cancellationToken),
            "PUT /budget-figures");
    }

    /// <summary>Deletes a record.</summary>
    /// <param name="number">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is gone.</returns>
    public Task DeleteAsync(int number, CancellationToken cancellationToken = default) =>
        OpenTransport.SendAsync(
            () => _client.DeleteBudgetFigureByIdAsync(number: number, cancellationToken: cancellationToken),
            "DELETE /budget-figures/{number}");
}
