// <auto-generated>
//     Generated by tools/EConomic.SpecConverter (open-facade).
//     Regenerate after a spec refresh; do not edit by hand.
// </auto-generated>
#nullable enable

using EConomic.Querying;
using Raw = EConomic.Open.Generated.Customers;

namespace EConomic.Open;

/// <summary>
/// A resource from <c>/Contacts</c>.
/// </summary>
/// <remarks>
/// The same shape is used to read, create and update: these services describe a resource once
/// and accept it back unchanged. Properties the server maintains are simply left unset.
/// </remarks>
public sealed record CustomerContact
{
    /// <summary>The <c>number</c> field.</summary>
    public int? Number { get; init; }

    /// <summary>The <c>customerNumber</c> field.</summary>
    public required int CustomerNumber { get; init; }

    /// <summary>The <c>userInterfaceNumber</c> field.</summary>
    public int? UserInterfaceNumber { get; init; }

    /// <summary>The <c>name</c> field.</summary>
    public required string Name { get; init; }

    /// <summary>The <c>email</c> field.</summary>
    public string? Email { get; init; }

    /// <summary>The <c>phone</c> field.</summary>
    public string? Phone { get; init; }

    /// <summary>The <c>notes</c> field.</summary>
    public string? Notes { get; init; }

    /// <summary>The <c>eInvoiceId</c> field.</summary>
    public string? EInvoiceId { get; init; }

    /// <summary>The <c>lastUpdated</c> field.</summary>
    public System.DateTimeOffset? LastUpdated { get; init; }

    /// <summary>The <c>receiveQuotes</c> field.</summary>
    public bool? ReceiveQuotes { get; init; }

    /// <summary>The <c>receiveOrders</c> field.</summary>
    public bool? ReceiveOrders { get; init; }

    /// <summary>The <c>receiveInvoices</c> field.</summary>
    public bool? ReceiveInvoices { get; init; }

    /// <summary>The <c>receiveEInvoices</c> field.</summary>
    public bool? ReceiveEInvoices { get; init; }

    /// <summary>The <c>receiveStatementOfAccounts</c> field.</summary>
    public bool? ReceiveStatementOfAccounts { get; init; }

    /// <summary>The <c>receiveReminders</c> field.</summary>
    public bool? ReceiveReminders { get; init; }

    /// <summary>The <c>objectVersion</c> field.</summary>
    public string? ObjectVersion { get; init; }

    /// <summary>The <c>isDeleted</c> field.</summary>
    public bool? IsDeleted { get; init; }

    /// <summary>The <c>active</c> field.</summary>
    public bool? Active { get; init; }
}

/// <summary>
/// What <c>/Contacts</c> can be filtered on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class CustomerContactFilter
{
    /// <summary>Maps to <c>number</c>.</summary>
    [EconomicField("number")]
    public NumericField<int> Number { get; } = null!;

    /// <summary>Maps to <c>customerNumber</c>.</summary>
    [EconomicField("customerNumber")]
    public NumericField<int> CustomerNumber { get; } = null!;

    /// <summary>Maps to <c>userInterfaceNumber</c>.</summary>
    [EconomicField("userInterfaceNumber")]
    public NumericField<int> UserInterfaceNumber { get; } = null!;

    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public TextField Name { get; } = null!;

    /// <summary>Maps to <c>email</c>.</summary>
    [EconomicField("email")]
    public TextField Email { get; } = null!;

    /// <summary>Maps to <c>eInvoiceId</c>.</summary>
    [EconomicField("eInvoiceId")]
    public EqualityField<string> EInvoiceId { get; } = null!;

    /// <summary>Maps to <c>lastUpdated</c>.</summary>
    [EconomicField("lastUpdated")]
    public ComparableField<System.DateTimeOffset> LastUpdated { get; } = null!;

    /// <summary>Maps to <c>isDeleted</c>.</summary>
    [EconomicField("isDeleted")]
    public EqualityField<bool> IsDeleted { get; } = null!;

    /// <summary>Maps to <c>active</c>.</summary>
    [EconomicField("active")]
    public EqualityField<bool> Active { get; } = null!;
}

/// <summary>
/// What <c>/Contacts</c> can be sorted on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class CustomerContactSort
{
    /// <summary>Maps to <c>number</c>.</summary>
    [EconomicField("number")]
    public EconomicSortField Number { get; } = null!;

    /// <summary>Maps to <c>customerNumber</c>.</summary>
    [EconomicField("customerNumber")]
    public EconomicSortField CustomerNumber { get; } = null!;
}

/// <summary>Fetches <c>/Contacts</c> and maps it to <see cref="CustomerContact"/>.</summary>
internal sealed class CustomerContactSource(Raw.ContactsClient client)
    : IEconomicOpenSource<CustomerContact>
{
    public async Task<EconomicCursorPage<CustomerContact>> GetCursorPageAsync(
        string? cursor, string? filter, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetAllContactsAsync(cursor: cursor, filter: filter, cancellationToken: cancellationToken),
            "GET /Contacts").ConfigureAwait(false);

        var items = new List<CustomerContact>(response.Items?.Count ?? 0);
        foreach (var item in response.Items ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicCursorPage<CustomerContact>(items, response.Cursor);
    }

    public async Task<IReadOnlyList<CustomerContact>> GetPageAsync(
        string? filter, string? sort, int pageSize, int skipPages, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetPageOfContactsAsync(filter: filter, sort: sort, pageSize: pageSize, skipPages: skipPages, cancellationToken: cancellationToken),
            "GET /Contacts/paged").ConfigureAwait(false);

        var items = new List<CustomerContact>(response?.Count ?? 0);
        foreach (var item in response ?? Array.Empty<Raw.Contact>())
        {
            items.Add(Map(item));
        }

        return items;
    }

    public Task<int> CountAsync(string? filter, CancellationToken cancellationToken) =>
        OpenTransport.SendAsync(
            () => client.GetNumberOfContactsAsync(filter: filter, cancellationToken: cancellationToken),
            "GET /Contacts/count");

    internal static CustomerContact Map(Raw.Contact source) => new()
    {
        Number = source.Number,
        CustomerNumber = source.CustomerNumber,
        UserInterfaceNumber = source.UserInterfaceNumber,
        Name = source.Name,
        Email = source.Email,
        Phone = source.Phone,
        Notes = source.Notes,
        EInvoiceId = source.EInvoiceId,
        LastUpdated = source.LastUpdated,
        ReceiveQuotes = source.ReceiveQuotes,
        ReceiveOrders = source.ReceiveOrders,
        ReceiveInvoices = source.ReceiveInvoices,
        ReceiveEInvoices = source.ReceiveEInvoices,
        ReceiveStatementOfAccounts = source.ReceiveStatementOfAccounts,
        ReceiveReminders = source.ReceiveReminders,
        ObjectVersion = source.ObjectVersion,
        IsDeleted = source.IsDeleted,
        Active = source.Active,
    };

    internal static Raw.Contact ToGenerated(CustomerContact source) => new()
    {
        Number = source.Number,
        CustomerNumber = source.CustomerNumber,
        UserInterfaceNumber = source.UserInterfaceNumber,
        Name = source.Name,
        Email = source.Email,
        Phone = source.Phone,
        Notes = source.Notes,
        EInvoiceId = source.EInvoiceId,
        LastUpdated = source.LastUpdated,
        ReceiveQuotes = source.ReceiveQuotes,
        ReceiveOrders = source.ReceiveOrders,
        ReceiveInvoices = source.ReceiveInvoices,
        ReceiveEInvoices = source.ReceiveEInvoices,
        ReceiveStatementOfAccounts = source.ReceiveStatementOfAccounts,
        ReceiveReminders = source.ReceiveReminders,
        ObjectVersion = source.ObjectVersion,
        IsDeleted = source.IsDeleted,
        Active = source.Active,
    };
}

/// <summary>
/// <c>/Contacts</c>, as a query and the writes the service supports.
/// </summary>
public sealed class CustomerContactResource
{
    private readonly Raw.ContactsClient _client;

    internal CustomerContactResource(System.Net.Http.HttpClient httpClient, System.Uri baseAddress)
    {
        _client = new Raw.ContactsClient(httpClient) { BaseUrl = baseAddress.ToString() };
    }

    /// <summary>This collection as a composable query.</summary>
    /// <returns>A query with no filter or ordering.</returns>
    public EconomicOpenQuery<CustomerContact, CustomerContactFilter, CustomerContactSort> AsQuery() => new(new CustomerContactSource(_client));

    /// <summary>Restricts what is returned.</summary>
    /// <param name="predicate">A filter over the filterable properties.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<CustomerContact, CustomerContactFilter, CustomerContactSort> Where(System.Linq.Expressions.Expression<System.Func<CustomerContactFilter, bool>> predicate) => AsQuery().Where(predicate);

    /// <summary>Restricts what is returned, using e-conomic's filter syntax directly.</summary>
    /// <param name="filter">A filter expression.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<CustomerContact, CustomerContactFilter, CustomerContactSort> WhereRaw(string filter) => AsQuery().WhereRaw(filter);

    /// <summary>Orders ascending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<CustomerContact, CustomerContactFilter, CustomerContactSort> OrderBy(System.Linq.Expressions.Expression<System.Func<CustomerContactSort, EconomicSortField>> selector) => AsQuery().OrderBy(selector);

    /// <summary>Orders descending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<CustomerContact, CustomerContactFilter, CustomerContactSort> OrderByDescending(System.Linq.Expressions.Expression<System.Func<CustomerContactSort, EconomicSortField>> selector) => AsQuery().OrderByDescending(selector);

    /// <summary>Sets how many items are fetched per request.</summary>
    /// <param name="pageSize">Items per page, up to 1000.</param>
    /// <returns>A query using that page size.</returns>
    public EconomicOpenQuery<CustomerContact, CustomerContactFilter, CustomerContactSort> WithPageSize(int pageSize) => AsQuery().WithPageSize(pageSize);

    /// <summary>Enumerates everything, following the cursor.</summary>
    /// <param name="cancellationToken">Cancels the enumeration.</param>
    /// <returns>The items.</returns>
    public System.Collections.Generic.IAsyncEnumerable<CustomerContact> AsAsyncEnumerable(CancellationToken cancellationToken = default) => AsQuery().AsAsyncEnumerable(cancellationToken);

    /// <summary>Counts everything in the collection.</summary>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The number of records.</returns>
    public Task<int> CountAsync(CancellationToken cancellationToken = default) => AsQuery().CountAsync(cancellationToken);

    /// <summary>Fetches one numbered page.</summary>
    /// <param name="pageIndex">Zero-based page index.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The page.</returns>
    public Task<IReadOnlyList<CustomerContact>> GetPageAsync(int pageIndex, CancellationToken cancellationToken = default) => AsQuery().GetPageAsync(pageIndex, cancellationToken);

    /// <summary>Fetches one record.</summary>
    /// <param name="number">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The record.</returns>
    public async Task<CustomerContact> GetAsync(int number, CancellationToken cancellationToken = default)
    {
        var response = await OpenTransport.SendAsync(
            () => _client.GetContactByIdAsync(number: number, cancellationToken: cancellationToken),
            "GET /Contacts/{number}").ConfigureAwait(false);

        return CustomerContactSource.Map(response);
    }

    /// <summary>Creates a record.</summary>
    /// <param name="item">The record to create, whose identifier you supply.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The identifier e-conomic stored it under.</returns>
    /// <remarks>
    /// The response carries the identifier and nothing else, so that is what this returns —
    /// unlike the legacy REST API, whose creates answer with the whole resource. Read it back
    /// with <c>GetAsync</c> if you need the stored record, which also gives you the
    /// <c>objectVersion</c> an update requires.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    public async Task<int?> CreateAsync(CustomerContact item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        var response = await OpenTransport.SendAsync(
            () => _client.CreateContactAsync(body: CustomerContactSource.ToGenerated(item), cancellationToken: cancellationToken),
            "POST /Contacts").ConfigureAwait(false);

        return response.Number;
    }

    /// <summary>Replaces a record.</summary>
    /// <param name="item">The replacement state, carrying the <c>objectVersion</c> that was read.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is replaced.</returns>
    /// <remarks>
    /// Updates are read-modify-write on this surface. The <c>objectVersion</c> from the record
    /// you read has to come back with it; a stale one, or none, is rejected with
    /// <see cref="Exceptions.EconomicConcurrencyException"/> and nothing is written.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    /// <exception cref="Exceptions.EconomicConcurrencyException">The record changed since it was read.</exception>
    public Task UpdateAsync(CustomerContact item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        return OpenTransport.SendAsync(
            () => _client.UpdateContactByIdAsync(body: CustomerContactSource.ToGenerated(item), cancellationToken: cancellationToken),
            "PUT /Contacts");
    }

    /// <summary>Deletes a record.</summary>
    /// <param name="number">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is gone.</returns>
    public Task DeleteAsync(int number, CancellationToken cancellationToken = default) =>
        OpenTransport.SendAsync(
            () => _client.DeleteContactByIdAsync(number: number, cancellationToken: cancellationToken),
            "DELETE /Contacts/{number}");
}

/// <summary>
/// A resource from <c>/Customers</c>.
/// </summary>
/// <remarks>
/// The same shape is used to read, create and update: these services describe a resource once
/// and accept it back unchanged. Properties the server maintains are simply left unset.
/// </remarks>
public sealed record Customer
{
    /// <summary>The <c>customerNumber</c> field.</summary>
    public int? CustomerNumber { get; init; }

    /// <summary>The <c>customerGroupNumber</c> field.</summary>
    public int? CustomerGroupNumber { get; init; }

    /// <summary>The <c>zone</c> field.</summary>
    public int? Zone { get; init; }

    /// <summary>The <c>currency</c> field.</summary>
    public string? Currency { get; init; }

    /// <summary>The <c>access</c> field.</summary>
    public bool? Access { get; init; }

    /// <summary>The <c>name</c> field.</summary>
    public string? Name { get; init; }

    /// <summary>The <c>address1</c> field.</summary>
    public string? Address1 { get; init; }

    /// <summary>The <c>address2</c> field.</summary>
    public string? Address2 { get; init; }

    /// <summary>The <c>postCode</c> field.</summary>
    public string? PostCode { get; init; }

    /// <summary>The <c>city</c> field.</summary>
    public string? City { get; init; }

    /// <summary>The <c>country</c> field.</summary>
    public string? Country { get; init; }

    /// <summary>The <c>contactPerson</c> field.</summary>
    public string? ContactPerson { get; init; }

    /// <summary>The <c>phone</c> field.</summary>
    public string? Phone { get; init; }

    /// <summary>The <c>email</c> field.</summary>
    public string? Email { get; init; }

    /// <summary>The <c>paymentDays</c> field.</summary>
    public int? PaymentDays { get; init; }

    /// <summary>The <c>bankAccount</c> field.</summary>
    public string? BankAccount { get; init; }

    /// <summary>The <c>cvrNo</c> field.</summary>
    public string? CvrNo { get; init; }

    /// <summary>The <c>ourRef</c> field.</summary>
    public int? OurRef { get; init; }

    /// <summary>The <c>layoutGroup</c> field.</summary>
    public int? LayoutGroup { get; init; }

    /// <summary>The <c>paymentTermId</c> field.</summary>
    public int? PaymentTermId { get; init; }

    /// <summary>The <c>homepage</c> field.</summary>
    public string? Homepage { get; init; }

    /// <summary>The <c>defaultTheirRef</c> field.</summary>
    public int? DefaultTheirRef { get; init; }

    /// <summary>The <c>defaultAttention</c> field.</summary>
    public int? DefaultAttention { get; init; }

    /// <summary>The <c>layoutGroupPrint</c> field.</summary>
    public int? LayoutGroupPrint { get; init; }

    /// <summary>The <c>language</c> field.</summary>
    public int? Language { get; init; }

    /// <summary>The <c>discountGroupNumber</c> field.</summary>
    public int? DiscountGroupNumber { get; init; }

    /// <summary>The <c>priceGroupNumber</c> field.</summary>
    public int? PriceGroupNumber { get; init; }

    /// <summary>The <c>defaultDeliveryLocation</c> field.</summary>
    public int? DefaultDeliveryLocation { get; init; }

    /// <summary>The <c>eanLocationNumber</c> field.</summary>
    public string? EanLocationNumber { get; init; }

    /// <summary>The <c>voucherNumber</c> field.</summary>
    public string? VoucherNumber { get; init; }

    /// <summary>The <c>county</c> field.</summary>
    public string? County { get; init; }

    /// <summary>The <c>vatNo</c> field.</summary>
    public string? VatNo { get; init; }

    /// <summary>The <c>creditMaximum</c> field.</summary>
    public double? CreditMaximum { get; init; }

    /// <summary>The <c>recipientPeppol</c> field.</summary>
    public string? RecipientPeppol { get; init; }

    /// <summary>The <c>defaultDiscountPct</c> field.</summary>
    public double? DefaultDiscountPct { get; init; }

    /// <summary>The <c>bankGiroNumber</c> field.</summary>
    public string? BankGiroNumber { get; init; }

    /// <summary>The <c>iban</c> field.</summary>
    public string? Iban { get; init; }

    /// <summary>The <c>swift</c> field.</summary>
    public string? Swift { get; init; }

    /// <summary>The <c>directDebitMandateDate</c> field.</summary>
    public System.DateTimeOffset? DirectDebitMandateDate { get; init; }

    /// <summary>The <c>pnr</c> field.</summary>
    public string? Pnr { get; init; }

    /// <summary>The <c>nemHandelReceiverType</c> field.</summary>
    public int? NemHandelReceiverType { get; init; }

    /// <summary>The <c>mobilePhone</c> field.</summary>
    public string? MobilePhone { get; init; }

    /// <summary>The <c>emailAttachmentLanguage</c> field.</summary>
    public int? EmailAttachmentLanguage { get; init; }

    /// <summary>The <c>defaultDisableEInvoicing</c> field.</summary>
    public bool? DefaultDisableEInvoicing { get; init; }

    /// <summary>The <c>defaultInvoiceRecipient</c> field.</summary>
    public string? DefaultInvoiceRecipient { get; init; }

    /// <summary>The <c>defaultInvoiceTemplate</c> field.</summary>
    public int? DefaultInvoiceTemplate { get; init; }

    /// <summary>The <c>defaultOrderRecipient</c> field.</summary>
    public string? DefaultOrderRecipient { get; init; }

    /// <summary>The <c>defaultOrderTemplate</c> field.</summary>
    public int? DefaultOrderTemplate { get; init; }

    /// <summary>The <c>defaultQuoteRecipient</c> field.</summary>
    public string? DefaultQuoteRecipient { get; init; }

    /// <summary>The <c>defaultQuoteTemplate</c> field.</summary>
    public int? DefaultQuoteTemplate { get; init; }

    /// <summary>The <c>defaultReminderRecipient</c> field.</summary>
    public string? DefaultReminderRecipient { get; init; }

    /// <summary>The <c>defaultReminderTemplate</c> field.</summary>
    public int? DefaultReminderTemplate { get; init; }

    /// <summary>The <c>defaultStatementOfAccountRecipient</c> field.</summary>
    public string? DefaultStatementOfAccountRecipient { get; init; }

    /// <summary>The <c>defaultStatementOfAccountTemplate</c> field.</summary>
    public int? DefaultStatementOfAccountTemplate { get; init; }

    /// <summary>The <c>objectVersion</c> field.</summary>
    public string? ObjectVersion { get; init; }
}

/// <summary>
/// What <c>/Customers</c> can be filtered on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class CustomerFilter
{
    /// <summary>Maps to <c>customerNumber</c>.</summary>
    [EconomicField("customerNumber")]
    public NumericField<int> CustomerNumber { get; } = null!;
}

/// <summary>
/// What <c>/Customers</c> can be sorted on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class CustomerSort
{
    /// <summary>Maps to <c>customerNumber</c>.</summary>
    [EconomicField("customerNumber")]
    public EconomicSortField CustomerNumber { get; } = null!;
}

/// <summary>Fetches <c>/Customers</c> and maps it to <see cref="Customer"/>.</summary>
internal sealed class CustomerSource(Raw.CustomersClient client)
    : IEconomicOpenSource<Customer>
{
    public async Task<EconomicCursorPage<Customer>> GetCursorPageAsync(
        string? cursor, string? filter, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetAllCustomersAsync(cursor: cursor, filter: filter, cancellationToken: cancellationToken),
            "GET /Customers").ConfigureAwait(false);

        var items = new List<Customer>(response.Items?.Count ?? 0);
        foreach (var item in response.Items ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicCursorPage<Customer>(items, response.Cursor);
    }

    public async Task<IReadOnlyList<Customer>> GetPageAsync(
        string? filter, string? sort, int pageSize, int skipPages, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetPageOfCustomersAsync(filter: filter, sort: sort, pageSize: pageSize, skipPages: skipPages, cancellationToken: cancellationToken),
            "GET /Customers/paged").ConfigureAwait(false);

        var items = new List<Customer>(response?.Count ?? 0);
        foreach (var item in response ?? Array.Empty<Raw.Customer>())
        {
            items.Add(Map(item));
        }

        return items;
    }

    public Task<int> CountAsync(string? filter, CancellationToken cancellationToken) =>
        OpenTransport.SendAsync(
            () => client.GetNumberOfCustomersAsync(filter: filter, cancellationToken: cancellationToken),
            "GET /Customers/count");

    internal static Customer Map(Raw.Customer source) => new()
    {
        CustomerNumber = source.CustomerNumber,
        CustomerGroupNumber = source.CustomerGroupNumber,
        Zone = source.Zone,
        Currency = source.Currency,
        Access = source.Access,
        Name = source.Name,
        Address1 = source.Address1,
        Address2 = source.Address2,
        PostCode = source.PostCode,
        City = source.City,
        Country = source.Country,
        ContactPerson = source.ContactPerson,
        Phone = source.Phone,
        Email = source.Email,
        PaymentDays = source.PaymentDays,
        BankAccount = source.BankAccount,
        CvrNo = source.CvrNo,
        OurRef = source.OurRef,
        LayoutGroup = source.LayoutGroup,
        PaymentTermId = source.PaymentTermId,
        Homepage = source.Homepage,
        DefaultTheirRef = source.DefaultTheirRef,
        DefaultAttention = source.DefaultAttention,
        LayoutGroupPrint = source.LayoutGroupPrint,
        Language = source.Language,
        DiscountGroupNumber = source.DiscountGroupNumber,
        PriceGroupNumber = source.PriceGroupNumber,
        DefaultDeliveryLocation = source.DefaultDeliveryLocation,
        EanLocationNumber = source.EanLocationNumber,
        VoucherNumber = source.VoucherNumber,
        County = source.County,
        VatNo = source.VatNo,
        CreditMaximum = source.CreditMaximum,
        RecipientPeppol = source.RecipientPeppol,
        DefaultDiscountPct = source.DefaultDiscountPct,
        BankGiroNumber = source.BankGiroNumber,
        Iban = source.Iban,
        Swift = source.Swift,
        DirectDebitMandateDate = source.DirectDebitMandateDate,
        Pnr = source.Pnr,
        NemHandelReceiverType = source.NemHandelReceiverType,
        MobilePhone = source.MobilePhone,
        EmailAttachmentLanguage = source.EmailAttachmentLanguage,
        DefaultDisableEInvoicing = source.DefaultDisableEInvoicing,
        DefaultInvoiceRecipient = source.DefaultInvoiceRecipient,
        DefaultInvoiceTemplate = source.DefaultInvoiceTemplate,
        DefaultOrderRecipient = source.DefaultOrderRecipient,
        DefaultOrderTemplate = source.DefaultOrderTemplate,
        DefaultQuoteRecipient = source.DefaultQuoteRecipient,
        DefaultQuoteTemplate = source.DefaultQuoteTemplate,
        DefaultReminderRecipient = source.DefaultReminderRecipient,
        DefaultReminderTemplate = source.DefaultReminderTemplate,
        DefaultStatementOfAccountRecipient = source.DefaultStatementOfAccountRecipient,
        DefaultStatementOfAccountTemplate = source.DefaultStatementOfAccountTemplate,
        ObjectVersion = source.ObjectVersion,
    };

    internal static Raw.Customer ToGenerated(Customer source) => new()
    {
        CustomerNumber = source.CustomerNumber,
        CustomerGroupNumber = source.CustomerGroupNumber,
        Zone = source.Zone,
        Currency = source.Currency,
        Access = source.Access,
        Name = source.Name,
        Address1 = source.Address1,
        Address2 = source.Address2,
        PostCode = source.PostCode,
        City = source.City,
        Country = source.Country,
        ContactPerson = source.ContactPerson,
        Phone = source.Phone,
        Email = source.Email,
        PaymentDays = source.PaymentDays,
        BankAccount = source.BankAccount,
        CvrNo = source.CvrNo,
        OurRef = source.OurRef,
        LayoutGroup = source.LayoutGroup,
        PaymentTermId = source.PaymentTermId,
        Homepage = source.Homepage,
        DefaultTheirRef = source.DefaultTheirRef,
        DefaultAttention = source.DefaultAttention,
        LayoutGroupPrint = source.LayoutGroupPrint,
        Language = source.Language,
        DiscountGroupNumber = source.DiscountGroupNumber,
        PriceGroupNumber = source.PriceGroupNumber,
        DefaultDeliveryLocation = source.DefaultDeliveryLocation,
        EanLocationNumber = source.EanLocationNumber,
        VoucherNumber = source.VoucherNumber,
        County = source.County,
        VatNo = source.VatNo,
        CreditMaximum = source.CreditMaximum,
        RecipientPeppol = source.RecipientPeppol,
        DefaultDiscountPct = source.DefaultDiscountPct,
        BankGiroNumber = source.BankGiroNumber,
        Iban = source.Iban,
        Swift = source.Swift,
        DirectDebitMandateDate = source.DirectDebitMandateDate,
        Pnr = source.Pnr,
        NemHandelReceiverType = source.NemHandelReceiverType,
        MobilePhone = source.MobilePhone,
        EmailAttachmentLanguage = source.EmailAttachmentLanguage,
        DefaultDisableEInvoicing = source.DefaultDisableEInvoicing,
        DefaultInvoiceRecipient = source.DefaultInvoiceRecipient,
        DefaultInvoiceTemplate = source.DefaultInvoiceTemplate,
        DefaultOrderRecipient = source.DefaultOrderRecipient,
        DefaultOrderTemplate = source.DefaultOrderTemplate,
        DefaultQuoteRecipient = source.DefaultQuoteRecipient,
        DefaultQuoteTemplate = source.DefaultQuoteTemplate,
        DefaultReminderRecipient = source.DefaultReminderRecipient,
        DefaultReminderTemplate = source.DefaultReminderTemplate,
        DefaultStatementOfAccountRecipient = source.DefaultStatementOfAccountRecipient,
        DefaultStatementOfAccountTemplate = source.DefaultStatementOfAccountTemplate,
        ObjectVersion = source.ObjectVersion,
    };
}

/// <summary>
/// <c>/Customers</c>, as a query and the writes the service supports.
/// </summary>
public sealed class CustomerResource
{
    private readonly Raw.CustomersClient _client;

    internal CustomerResource(System.Net.Http.HttpClient httpClient, System.Uri baseAddress)
    {
        _client = new Raw.CustomersClient(httpClient) { BaseUrl = baseAddress.ToString() };
    }

    /// <summary>This collection as a composable query.</summary>
    /// <returns>A query with no filter or ordering.</returns>
    public EconomicOpenQuery<Customer, CustomerFilter, CustomerSort> AsQuery() => new(new CustomerSource(_client));

    /// <summary>Restricts what is returned.</summary>
    /// <param name="predicate">A filter over the filterable properties.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<Customer, CustomerFilter, CustomerSort> Where(System.Linq.Expressions.Expression<System.Func<CustomerFilter, bool>> predicate) => AsQuery().Where(predicate);

    /// <summary>Restricts what is returned, using e-conomic's filter syntax directly.</summary>
    /// <param name="filter">A filter expression.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<Customer, CustomerFilter, CustomerSort> WhereRaw(string filter) => AsQuery().WhereRaw(filter);

    /// <summary>Orders ascending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<Customer, CustomerFilter, CustomerSort> OrderBy(System.Linq.Expressions.Expression<System.Func<CustomerSort, EconomicSortField>> selector) => AsQuery().OrderBy(selector);

    /// <summary>Orders descending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<Customer, CustomerFilter, CustomerSort> OrderByDescending(System.Linq.Expressions.Expression<System.Func<CustomerSort, EconomicSortField>> selector) => AsQuery().OrderByDescending(selector);

    /// <summary>Sets how many items are fetched per request.</summary>
    /// <param name="pageSize">Items per page, up to 1000.</param>
    /// <returns>A query using that page size.</returns>
    public EconomicOpenQuery<Customer, CustomerFilter, CustomerSort> WithPageSize(int pageSize) => AsQuery().WithPageSize(pageSize);

    /// <summary>Enumerates everything, following the cursor.</summary>
    /// <param name="cancellationToken">Cancels the enumeration.</param>
    /// <returns>The items.</returns>
    public System.Collections.Generic.IAsyncEnumerable<Customer> AsAsyncEnumerable(CancellationToken cancellationToken = default) => AsQuery().AsAsyncEnumerable(cancellationToken);

    /// <summary>Counts everything in the collection.</summary>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The number of records.</returns>
    public Task<int> CountAsync(CancellationToken cancellationToken = default) => AsQuery().CountAsync(cancellationToken);

    /// <summary>Fetches one numbered page.</summary>
    /// <param name="pageIndex">Zero-based page index.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The page.</returns>
    public Task<IReadOnlyList<Customer>> GetPageAsync(int pageIndex, CancellationToken cancellationToken = default) => AsQuery().GetPageAsync(pageIndex, cancellationToken);

    /// <summary>Fetches one record.</summary>
    /// <param name="number">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The record.</returns>
    public async Task<Customer> GetAsync(int number, CancellationToken cancellationToken = default)
    {
        var response = await OpenTransport.SendAsync(
            () => _client.GetOneCustomerAsync(number: number, cancellationToken: cancellationToken),
            "GET /Customers/{number}").ConfigureAwait(false);

        return CustomerSource.Map(response);
    }

    /// <summary>Creates a record.</summary>
    /// <param name="item">The record to create, whose identifier you supply.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The identifier e-conomic stored it under.</returns>
    /// <remarks>
    /// The response carries the identifier and nothing else, so that is what this returns —
    /// unlike the legacy REST API, whose creates answer with the whole resource. Read it back
    /// with <c>GetAsync</c> if you need the stored record, which also gives you the
    /// <c>objectVersion</c> an update requires.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    public async Task<int?> CreateAsync(Customer item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        var response = await OpenTransport.SendAsync(
            () => _client.CreateCustomerAsync(body: CustomerSource.ToGenerated(item), cancellationToken: cancellationToken),
            "POST /Customers").ConfigureAwait(false);

        return response.CustomerNumber;
    }

    /// <summary>Replaces a record.</summary>
    /// <param name="number">The record to replace.</param>
    /// <param name="item">The replacement state, carrying the <c>objectVersion</c> that was read.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is replaced.</returns>
    /// <remarks>
    /// Updates are read-modify-write on this surface. The <c>objectVersion</c> from the record
    /// you read has to come back with it; a stale one, or none, is rejected with
    /// <see cref="Exceptions.EconomicConcurrencyException"/> and nothing is written.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    /// <exception cref="Exceptions.EconomicConcurrencyException">The record changed since it was read.</exception>
    public Task UpdateAsync(int number, Customer item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        return OpenTransport.SendAsync(
            () => _client.UpdateCustomerByIdAsync(number: number, body: CustomerSource.ToGenerated(item), cancellationToken: cancellationToken),
            "PUT /Customers");
    }

    /// <summary>Deletes a record.</summary>
    /// <param name="number">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is gone.</returns>
    public Task DeleteAsync(int number, CancellationToken cancellationToken = default) =>
        OpenTransport.SendAsync(
            () => _client.DeleteCustomerByIdAsync(number: number, cancellationToken: cancellationToken),
            "DELETE /Customers/{number}");
}

/// <summary>
/// A resource from <c>/DeliveryLocations</c>.
/// </summary>
/// <remarks>
/// The same shape is used to read, create and update: these services describe a resource once
/// and accept it back unchanged. Properties the server maintains are simply left unset.
/// </remarks>
public sealed record CustomerDeliveryLocation
{
    /// <summary>The <c>number</c> field.</summary>
    public int? Number { get; init; }

    /// <summary>The <c>customerNumber</c> field.</summary>
    public required int CustomerNumber { get; init; }

    /// <summary>The <c>userInterfaceNumber</c> field.</summary>
    public int? UserInterfaceNumber { get; init; }

    /// <summary>The <c>address</c> field.</summary>
    public string? Address { get; init; }

    /// <summary>The <c>city</c> field.</summary>
    public string? City { get; init; }

    /// <summary>The <c>country</c> field.</summary>
    public string? Country { get; init; }

    /// <summary>The <c>postalCode</c> field.</summary>
    public string? PostalCode { get; init; }

    /// <summary>The <c>termsOfDelivery</c> field.</summary>
    public string? TermsOfDelivery { get; init; }

    /// <summary>The <c>eInvoiceId</c> field.</summary>
    public string? EInvoiceId { get; init; }

    /// <summary>The <c>isBarred</c> field.</summary>
    public bool? IsBarred { get; init; }

    /// <summary>The <c>lastUpdated</c> field.</summary>
    public System.DateTimeOffset? LastUpdated { get; init; }

    /// <summary>The <c>objectVersion</c> field.</summary>
    public string? ObjectVersion { get; init; }
}

/// <summary>
/// What <c>/DeliveryLocations</c> can be filtered on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class CustomerDeliveryLocationFilter
{
    /// <summary>Maps to <c>number</c>.</summary>
    [EconomicField("number")]
    public NumericField<int> Number { get; } = null!;

    /// <summary>Maps to <c>customerNumber</c>.</summary>
    [EconomicField("customerNumber")]
    public NumericField<int> CustomerNumber { get; } = null!;

    /// <summary>Maps to <c>userInterfaceNumber</c>.</summary>
    [EconomicField("userInterfaceNumber")]
    public NumericField<int> UserInterfaceNumber { get; } = null!;

    /// <summary>Maps to <c>city</c>.</summary>
    [EconomicField("city")]
    public EqualityField<string> City { get; } = null!;

    /// <summary>Maps to <c>country</c>.</summary>
    [EconomicField("country")]
    public EqualityField<string> Country { get; } = null!;

    /// <summary>Maps to <c>eInvoiceId</c>.</summary>
    [EconomicField("eInvoiceId")]
    public EqualityField<string> EInvoiceId { get; } = null!;

    /// <summary>Maps to <c>isBarred</c>.</summary>
    [EconomicField("isBarred")]
    public EqualityField<bool> IsBarred { get; } = null!;

    /// <summary>Maps to <c>lastUpdated</c>.</summary>
    [EconomicField("lastUpdated")]
    public ComparableField<System.DateTimeOffset> LastUpdated { get; } = null!;
}

/// <summary>
/// What <c>/DeliveryLocations</c> can be sorted on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class CustomerDeliveryLocationSort
{
    /// <summary>Maps to <c>number</c>.</summary>
    [EconomicField("number")]
    public EconomicSortField Number { get; } = null!;

    /// <summary>Maps to <c>customerNumber</c>.</summary>
    [EconomicField("customerNumber")]
    public EconomicSortField CustomerNumber { get; } = null!;
}

/// <summary>Fetches <c>/DeliveryLocations</c> and maps it to <see cref="CustomerDeliveryLocation"/>.</summary>
internal sealed class CustomerDeliveryLocationSource(Raw.DeliveryLocationsClient client)
    : IEconomicOpenSource<CustomerDeliveryLocation>
{
    public async Task<EconomicCursorPage<CustomerDeliveryLocation>> GetCursorPageAsync(
        string? cursor, string? filter, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetAllDeliveryLocationsAsync(cursor: cursor, filter: filter, cancellationToken: cancellationToken),
            "GET /DeliveryLocations").ConfigureAwait(false);

        var items = new List<CustomerDeliveryLocation>(response.Items?.Count ?? 0);
        foreach (var item in response.Items ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicCursorPage<CustomerDeliveryLocation>(items, response.Cursor);
    }

    public async Task<IReadOnlyList<CustomerDeliveryLocation>> GetPageAsync(
        string? filter, string? sort, int pageSize, int skipPages, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetPageOfDeliveryLocationsAsync(filter: filter, sort: sort, pageSize: pageSize, skipPages: skipPages, cancellationToken: cancellationToken),
            "GET /DeliveryLocations/paged").ConfigureAwait(false);

        var items = new List<CustomerDeliveryLocation>(response?.Count ?? 0);
        foreach (var item in response ?? Array.Empty<Raw.DeliveryLocation>())
        {
            items.Add(Map(item));
        }

        return items;
    }

    public Task<int> CountAsync(string? filter, CancellationToken cancellationToken) =>
        OpenTransport.SendAsync(
            () => client.GetNumberOfDeliveryLocationsAsync(filter: filter, cancellationToken: cancellationToken),
            "GET /DeliveryLocations/count");

    internal static CustomerDeliveryLocation Map(Raw.DeliveryLocation source) => new()
    {
        Number = source.Number,
        CustomerNumber = source.CustomerNumber,
        UserInterfaceNumber = source.UserInterfaceNumber,
        Address = source.Address,
        City = source.City,
        Country = source.Country,
        PostalCode = source.PostalCode,
        TermsOfDelivery = source.TermsOfDelivery,
        EInvoiceId = source.EInvoiceId,
        IsBarred = source.IsBarred,
        LastUpdated = source.LastUpdated,
        ObjectVersion = source.ObjectVersion,
    };

    internal static Raw.DeliveryLocation ToGenerated(CustomerDeliveryLocation source) => new()
    {
        Number = source.Number,
        CustomerNumber = source.CustomerNumber,
        UserInterfaceNumber = source.UserInterfaceNumber,
        Address = source.Address,
        City = source.City,
        Country = source.Country,
        PostalCode = source.PostalCode,
        TermsOfDelivery = source.TermsOfDelivery,
        EInvoiceId = source.EInvoiceId,
        IsBarred = source.IsBarred,
        LastUpdated = source.LastUpdated,
        ObjectVersion = source.ObjectVersion,
    };
}

/// <summary>
/// <c>/DeliveryLocations</c>, as a query and the writes the service supports.
/// </summary>
public sealed class CustomerDeliveryLocationResource
{
    private readonly Raw.DeliveryLocationsClient _client;

    internal CustomerDeliveryLocationResource(System.Net.Http.HttpClient httpClient, System.Uri baseAddress)
    {
        _client = new Raw.DeliveryLocationsClient(httpClient) { BaseUrl = baseAddress.ToString() };
    }

    /// <summary>This collection as a composable query.</summary>
    /// <returns>A query with no filter or ordering.</returns>
    public EconomicOpenQuery<CustomerDeliveryLocation, CustomerDeliveryLocationFilter, CustomerDeliveryLocationSort> AsQuery() => new(new CustomerDeliveryLocationSource(_client));

    /// <summary>Restricts what is returned.</summary>
    /// <param name="predicate">A filter over the filterable properties.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<CustomerDeliveryLocation, CustomerDeliveryLocationFilter, CustomerDeliveryLocationSort> Where(System.Linq.Expressions.Expression<System.Func<CustomerDeliveryLocationFilter, bool>> predicate) => AsQuery().Where(predicate);

    /// <summary>Restricts what is returned, using e-conomic's filter syntax directly.</summary>
    /// <param name="filter">A filter expression.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<CustomerDeliveryLocation, CustomerDeliveryLocationFilter, CustomerDeliveryLocationSort> WhereRaw(string filter) => AsQuery().WhereRaw(filter);

    /// <summary>Orders ascending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<CustomerDeliveryLocation, CustomerDeliveryLocationFilter, CustomerDeliveryLocationSort> OrderBy(System.Linq.Expressions.Expression<System.Func<CustomerDeliveryLocationSort, EconomicSortField>> selector) => AsQuery().OrderBy(selector);

    /// <summary>Orders descending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<CustomerDeliveryLocation, CustomerDeliveryLocationFilter, CustomerDeliveryLocationSort> OrderByDescending(System.Linq.Expressions.Expression<System.Func<CustomerDeliveryLocationSort, EconomicSortField>> selector) => AsQuery().OrderByDescending(selector);

    /// <summary>Sets how many items are fetched per request.</summary>
    /// <param name="pageSize">Items per page, up to 1000.</param>
    /// <returns>A query using that page size.</returns>
    public EconomicOpenQuery<CustomerDeliveryLocation, CustomerDeliveryLocationFilter, CustomerDeliveryLocationSort> WithPageSize(int pageSize) => AsQuery().WithPageSize(pageSize);

    /// <summary>Enumerates everything, following the cursor.</summary>
    /// <param name="cancellationToken">Cancels the enumeration.</param>
    /// <returns>The items.</returns>
    public System.Collections.Generic.IAsyncEnumerable<CustomerDeliveryLocation> AsAsyncEnumerable(CancellationToken cancellationToken = default) => AsQuery().AsAsyncEnumerable(cancellationToken);

    /// <summary>Counts everything in the collection.</summary>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The number of records.</returns>
    public Task<int> CountAsync(CancellationToken cancellationToken = default) => AsQuery().CountAsync(cancellationToken);

    /// <summary>Fetches one numbered page.</summary>
    /// <param name="pageIndex">Zero-based page index.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The page.</returns>
    public Task<IReadOnlyList<CustomerDeliveryLocation>> GetPageAsync(int pageIndex, CancellationToken cancellationToken = default) => AsQuery().GetPageAsync(pageIndex, cancellationToken);

    /// <summary>Fetches one record.</summary>
    /// <param name="number">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The record.</returns>
    public async Task<CustomerDeliveryLocation> GetAsync(int number, CancellationToken cancellationToken = default)
    {
        var response = await OpenTransport.SendAsync(
            () => _client.GetDeliveryLocationByIdAsync(number: number, cancellationToken: cancellationToken),
            "GET /DeliveryLocations/{number}").ConfigureAwait(false);

        return CustomerDeliveryLocationSource.Map(response);
    }

    /// <summary>Creates a record.</summary>
    /// <param name="item">The record to create, whose identifier you supply.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The identifier e-conomic stored it under.</returns>
    /// <remarks>
    /// The response carries the identifier and nothing else, so that is what this returns —
    /// unlike the legacy REST API, whose creates answer with the whole resource. Read it back
    /// with <c>GetAsync</c> if you need the stored record, which also gives you the
    /// <c>objectVersion</c> an update requires.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    public async Task<int?> CreateAsync(CustomerDeliveryLocation item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        var response = await OpenTransport.SendAsync(
            () => _client.CreateDeliveryLocationAsync(body: CustomerDeliveryLocationSource.ToGenerated(item), cancellationToken: cancellationToken),
            "POST /DeliveryLocations").ConfigureAwait(false);

        return response.Number;
    }

    /// <summary>Replaces a record.</summary>
    /// <param name="item">The replacement state, carrying the <c>objectVersion</c> that was read.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is replaced.</returns>
    /// <remarks>
    /// Updates are read-modify-write on this surface. The <c>objectVersion</c> from the record
    /// you read has to come back with it; a stale one, or none, is rejected with
    /// <see cref="Exceptions.EconomicConcurrencyException"/> and nothing is written.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    /// <exception cref="Exceptions.EconomicConcurrencyException">The record changed since it was read.</exception>
    public Task UpdateAsync(CustomerDeliveryLocation item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        return OpenTransport.SendAsync(
            () => _client.UpdateDeliveryLocationByIdAsync(body: CustomerDeliveryLocationSource.ToGenerated(item), cancellationToken: cancellationToken),
            "PUT /DeliveryLocations");
    }

    /// <summary>Deletes a record.</summary>
    /// <param name="number">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is gone.</returns>
    public Task DeleteAsync(int number, CancellationToken cancellationToken = default) =>
        OpenTransport.SendAsync(
            () => _client.DeleteDeliveryLocationByIdAsync(number: number, cancellationToken: cancellationToken),
            "DELETE /DeliveryLocations/{number}");
}
