// <auto-generated>
//     Generated by tools/EConomic.SpecConverter (open-facade).
//     Regenerate after a spec refresh; do not edit by hand.
// </auto-generated>
#nullable enable

using EConomic.Querying;
using Raw = EConomic.Open.Generated.Products;

namespace EConomic.Open;

/// <summary>
/// A resource from <c>/pricegroups</c>.
/// </summary>
/// <remarks>
/// The same shape is used to read, create and update: these services describe a resource once
/// and accept it back unchanged. Properties the server maintains are simply left unset.
/// </remarks>
public sealed record ProductPriceGroup
{
    /// <summary>The <c>number</c> field.</summary>
    public required int Number { get; init; }

    /// <summary>The <c>name</c> field.</summary>
    public required string Name { get; init; }

    /// <summary>The <c>objectVersion</c> field.</summary>
    public string? ObjectVersion { get; init; }
}

/// <summary>
/// What <c>/pricegroups</c> can be filtered on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class ProductPriceGroupFilter
{
    /// <summary>Maps to <c>number</c>.</summary>
    [EconomicField("number")]
    public NumericField<int> Number { get; } = null!;

    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public EqualityField<string> Name { get; } = null!;
}

/// <summary>
/// What <c>/pricegroups</c> can be sorted on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class ProductPriceGroupSort
{
    /// <summary>Maps to <c>number</c>.</summary>
    [EconomicField("number")]
    public EconomicSortField Number { get; } = null!;

    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public EconomicSortField Name { get; } = null!;
}

/// <summary>Fetches <c>/pricegroups</c> and maps it to <see cref="ProductPriceGroup"/>.</summary>
internal sealed class ProductPriceGroupSource(Raw.PriceGroupsClient client)
    : IEconomicOpenSource<ProductPriceGroup>
{
    public async Task<EconomicCursorPage<ProductPriceGroup>> GetCursorPageAsync(
        string? cursor, string? filter, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetAllPriceGroupsAsync(cursor: cursor, filter: filter, cancellationToken: cancellationToken),
            "GET /pricegroups").ConfigureAwait(false);

        var items = new List<ProductPriceGroup>(response.Items?.Count ?? 0);
        foreach (var item in response.Items ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicCursorPage<ProductPriceGroup>(items, response.Cursor);
    }

    public async Task<IReadOnlyList<ProductPriceGroup>> GetPageAsync(
        string? filter, string? sort, int pageSize, int skipPages, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetPageOfPriceGroupsAsync(filter: filter, sort: sort, pageSize: pageSize, skipPages: skipPages, cancellationToken: cancellationToken),
            "GET /pricegroups/paged").ConfigureAwait(false);

        var items = new List<ProductPriceGroup>(response?.Count ?? 0);
        foreach (var item in response ?? Array.Empty<Raw.PriceGroup>())
        {
            items.Add(Map(item));
        }

        return items;
    }

    public Task<int> CountAsync(string? filter, CancellationToken cancellationToken) =>
        OpenTransport.SendAsync(
            () => client.GetNumberOfPriceGroupsAsync(filter: filter, cancellationToken: cancellationToken),
            "GET /pricegroups/count");

    internal static ProductPriceGroup Map(Raw.PriceGroup source) => new()
    {
        Number = source.Number,
        Name = source.Name,
        ObjectVersion = source.ObjectVersion,
    };

    internal static Raw.PriceGroup ToGenerated(ProductPriceGroup source) => new()
    {
        Number = source.Number,
        Name = source.Name,
        ObjectVersion = source.ObjectVersion,
    };
}

/// <summary>
/// <c>/pricegroups</c>, as a query and the writes the service supports.
/// </summary>
public sealed class ProductPriceGroupResource
{
    private readonly Raw.PriceGroupsClient _client;

    internal ProductPriceGroupResource(System.Net.Http.HttpClient httpClient, System.Uri baseAddress)
    {
        _client = new Raw.PriceGroupsClient(httpClient) { BaseUrl = baseAddress.ToString() };
    }

    /// <summary>This collection as a composable query.</summary>
    /// <returns>A query with no filter or ordering.</returns>
    public EconomicOpenQuery<ProductPriceGroup, ProductPriceGroupFilter, ProductPriceGroupSort> AsQuery() => new(new ProductPriceGroupSource(_client));

    /// <summary>Restricts what is returned.</summary>
    /// <param name="predicate">A filter over the filterable properties.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<ProductPriceGroup, ProductPriceGroupFilter, ProductPriceGroupSort> Where(System.Linq.Expressions.Expression<System.Func<ProductPriceGroupFilter, bool>> predicate) => AsQuery().Where(predicate);

    /// <summary>Restricts what is returned, using e-conomic's filter syntax directly.</summary>
    /// <param name="filter">A filter expression.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<ProductPriceGroup, ProductPriceGroupFilter, ProductPriceGroupSort> WhereRaw(string filter) => AsQuery().WhereRaw(filter);

    /// <summary>Orders ascending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<ProductPriceGroup, ProductPriceGroupFilter, ProductPriceGroupSort> OrderBy(System.Linq.Expressions.Expression<System.Func<ProductPriceGroupSort, EconomicSortField>> selector) => AsQuery().OrderBy(selector);

    /// <summary>Orders descending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<ProductPriceGroup, ProductPriceGroupFilter, ProductPriceGroupSort> OrderByDescending(System.Linq.Expressions.Expression<System.Func<ProductPriceGroupSort, EconomicSortField>> selector) => AsQuery().OrderByDescending(selector);

    /// <summary>Sets how many items are fetched per request.</summary>
    /// <param name="pageSize">Items per page, up to 1000.</param>
    /// <returns>A query using that page size.</returns>
    public EconomicOpenQuery<ProductPriceGroup, ProductPriceGroupFilter, ProductPriceGroupSort> WithPageSize(int pageSize) => AsQuery().WithPageSize(pageSize);

    /// <summary>Enumerates everything, following the cursor.</summary>
    /// <param name="cancellationToken">Cancels the enumeration.</param>
    /// <returns>The items.</returns>
    public System.Collections.Generic.IAsyncEnumerable<ProductPriceGroup> AsAsyncEnumerable(CancellationToken cancellationToken = default) => AsQuery().AsAsyncEnumerable(cancellationToken);

    /// <summary>Counts everything in the collection.</summary>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The number of records.</returns>
    public Task<int> CountAsync(CancellationToken cancellationToken = default) => AsQuery().CountAsync(cancellationToken);

    /// <summary>Fetches one numbered page.</summary>
    /// <param name="pageIndex">Zero-based page index.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The page.</returns>
    public Task<IReadOnlyList<ProductPriceGroup>> GetPageAsync(int pageIndex, CancellationToken cancellationToken = default) => AsQuery().GetPageAsync(pageIndex, cancellationToken);

    /// <summary>Fetches one record.</summary>
    /// <param name="number">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The record.</returns>
    public async Task<ProductPriceGroup> GetAsync(int number, CancellationToken cancellationToken = default)
    {
        var response = await OpenTransport.SendAsync(
            () => _client.GetOnePriceGroupAsync(number: number, cancellationToken: cancellationToken),
            "GET /pricegroups/{number}").ConfigureAwait(false);

        return ProductPriceGroupSource.Map(response);
    }

    /// <summary>Creates a record.</summary>
    /// <param name="item">The record to create, whose identifier you supply.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The identifier e-conomic stored it under.</returns>
    /// <remarks>
    /// The response carries the identifier and nothing else, so that is what this returns —
    /// unlike the legacy REST API, whose creates answer with the whole resource. Read it back
    /// with <c>GetAsync</c> if you need the stored record, which also gives you the
    /// <c>objectVersion</c> an update requires.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    public async Task<int?> CreateAsync(ProductPriceGroup item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        var response = await OpenTransport.SendAsync(
            () => _client.CreatePriceGroupAsync(body: ProductPriceGroupSource.ToGenerated(item), cancellationToken: cancellationToken),
            "POST /pricegroups").ConfigureAwait(false);

        return response.Number;
    }

    /// <summary>Replaces a record.</summary>
    /// <param name="item">The replacement state, carrying the <c>objectVersion</c> that was read.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is replaced.</returns>
    /// <remarks>
    /// Updates are read-modify-write on this surface. The <c>objectVersion</c> from the record
    /// you read has to come back with it; a stale one, or none, is rejected with
    /// <see cref="Exceptions.EconomicConcurrencyException"/> and nothing is written.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    /// <exception cref="Exceptions.EconomicConcurrencyException">The record changed since it was read.</exception>
    public Task UpdateAsync(ProductPriceGroup item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        return OpenTransport.SendAsync(
            () => _client.UpdatePriceGroupByIdAsync(body: ProductPriceGroupSource.ToGenerated(item), cancellationToken: cancellationToken),
            "PUT /pricegroups");
    }

    /// <summary>Deletes a record.</summary>
    /// <param name="number">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is gone.</returns>
    public Task DeleteAsync(int number, CancellationToken cancellationToken = default) =>
        OpenTransport.SendAsync(
            () => _client.DeletePriceGroupByIdAsync(number: number, cancellationToken: cancellationToken),
            "DELETE /pricegroups/{number}");
}

/// <summary>
/// A resource from <c>/products</c>.
/// </summary>
/// <remarks>
/// The same shape is used to read, create and update: these services describe a resource once
/// and accept it back unchanged. Properties the server maintains are simply left unset.
/// </remarks>
public sealed record Product
{
    /// <summary>The <c>productNumber</c> field.</summary>
    public required string ProductNumber { get; init; }

    /// <summary>The <c>productGroupId</c> field.</summary>
    public required int ProductGroupId { get; init; }

    /// <summary>The <c>name</c> field.</summary>
    public required string Name { get; init; }

    /// <summary>The <c>description</c> field.</summary>
    public string? Description { get; init; }

    /// <summary>The <c>barCode</c> field.</summary>
    public string? BarCode { get; init; }

    /// <summary>The <c>salesPrice</c> field.</summary>
    public double? SalesPrice { get; init; }

    /// <summary>The <c>costPrice</c> field.</summary>
    public double? CostPrice { get; init; }

    /// <summary>The <c>recommendedPrice</c> field.</summary>
    public double? RecommendedPrice { get; init; }

    /// <summary>The <c>unitId</c> field.</summary>
    public int? UnitId { get; init; }

    /// <summary>The <c>unit2Id</c> field.</summary>
    public int? Unit2Id { get; init; }

    /// <summary>The <c>isAccessible</c> field.</summary>
    public required bool IsAccessible { get; init; }

    /// <summary>The <c>lastUpdated</c> field.</summary>
    public System.DateTimeOffset? LastUpdated { get; init; }

    /// <summary>The <c>objectVersion</c> field.</summary>
    public string? ObjectVersion { get; init; }
}

/// <summary>
/// What <c>/products</c> can be filtered on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class ProductFilter
{
    /// <summary>Maps to <c>productNumber</c>.</summary>
    [EconomicField("productNumber")]
    public TextField ProductNumber { get; } = null!;

    /// <summary>Maps to <c>productGroupId</c>.</summary>
    [EconomicField("productGroupId")]
    public ComparableField<int> ProductGroupId { get; } = null!;

    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public TextField Name { get; } = null!;

    /// <summary>Maps to <c>isAccessible</c>.</summary>
    [EconomicField("isAccessible")]
    public EqualityField<bool> IsAccessible { get; } = null!;

    /// <summary>Maps to <c>lastUpdated</c>.</summary>
    [EconomicField("lastUpdated")]
    public ComparableField<System.DateTimeOffset> LastUpdated { get; } = null!;
}

/// <summary>
/// What <c>/products</c> can be sorted on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class ProductSort
{
    /// <summary>Maps to <c>productNumber</c>.</summary>
    [EconomicField("productNumber")]
    public EconomicSortField ProductNumber { get; } = null!;

    /// <summary>Maps to <c>productGroupId</c>.</summary>
    [EconomicField("productGroupId")]
    public EconomicSortField ProductGroupId { get; } = null!;

    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public EconomicSortField Name { get; } = null!;

    /// <summary>Maps to <c>lastUpdated</c>.</summary>
    [EconomicField("lastUpdated")]
    public EconomicSortField LastUpdated { get; } = null!;
}

/// <summary>Fetches <c>/products</c> and maps it to <see cref="Product"/>.</summary>
internal sealed class ProductSource(Raw.ProductsClient client)
    : IEconomicOpenSource<Product>
{
    public async Task<EconomicCursorPage<Product>> GetCursorPageAsync(
        string? cursor, string? filter, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetAllProductsAsync(cursor: cursor, filter: filter, cancellationToken: cancellationToken),
            "GET /products").ConfigureAwait(false);

        var items = new List<Product>(response.Items?.Count ?? 0);
        foreach (var item in response.Items ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicCursorPage<Product>(items, response.Cursor);
    }

    public async Task<IReadOnlyList<Product>> GetPageAsync(
        string? filter, string? sort, int pageSize, int skipPages, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetPageOfProductsAsync(filter: filter, sort: sort, pageSize: pageSize, skipPages: skipPages, cancellationToken: cancellationToken),
            "GET /productspaged/paged").ConfigureAwait(false);

        var items = new List<Product>(response?.Count ?? 0);
        foreach (var item in response ?? Array.Empty<Raw.Product>())
        {
            items.Add(Map(item));
        }

        return items;
    }

    public Task<int> CountAsync(string? filter, CancellationToken cancellationToken) =>
        throw new NotSupportedException(
            "e-conomic publishes no count endpoint for /products, so this collection "
            + "cannot be counted. Enumerate it, or count a collection that publishes one.");

    internal static Product Map(Raw.Product source) => new()
    {
        ProductNumber = source.ProductNumber,
        ProductGroupId = source.ProductGroupId,
        Name = source.Name,
        Description = source.Description,
        BarCode = source.BarCode,
        SalesPrice = source.SalesPrice,
        CostPrice = source.CostPrice,
        RecommendedPrice = source.RecommendedPrice,
        UnitId = source.UnitId,
        Unit2Id = source.Unit2Id,
        IsAccessible = source.IsAccessible,
        LastUpdated = source.LastUpdated,
        ObjectVersion = source.ObjectVersion,
    };

    internal static Raw.Product ToGenerated(Product source) => new()
    {
        ProductNumber = source.ProductNumber,
        ProductGroupId = source.ProductGroupId,
        Name = source.Name,
        Description = source.Description,
        BarCode = source.BarCode,
        SalesPrice = source.SalesPrice,
        CostPrice = source.CostPrice,
        RecommendedPrice = source.RecommendedPrice,
        UnitId = source.UnitId,
        Unit2Id = source.Unit2Id,
        IsAccessible = source.IsAccessible,
        LastUpdated = source.LastUpdated,
        ObjectVersion = source.ObjectVersion,
    };
}

/// <summary>
/// <c>/products</c>, as a query and the writes the service supports.
/// </summary>
public sealed class ProductResource
{
    private readonly Raw.ProductsClient _client;

    internal ProductResource(System.Net.Http.HttpClient httpClient, System.Uri baseAddress)
    {
        _client = new Raw.ProductsClient(httpClient) { BaseUrl = baseAddress.ToString() };
    }

    /// <summary>This collection as a composable query.</summary>
    /// <returns>A query with no filter or ordering.</returns>
    public EconomicOpenQuery<Product, ProductFilter, ProductSort> AsQuery() => new(new ProductSource(_client));

    /// <summary>Restricts what is returned.</summary>
    /// <param name="predicate">A filter over the filterable properties.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<Product, ProductFilter, ProductSort> Where(System.Linq.Expressions.Expression<System.Func<ProductFilter, bool>> predicate) => AsQuery().Where(predicate);

    /// <summary>Restricts what is returned, using e-conomic's filter syntax directly.</summary>
    /// <param name="filter">A filter expression.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<Product, ProductFilter, ProductSort> WhereRaw(string filter) => AsQuery().WhereRaw(filter);

    /// <summary>Orders ascending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<Product, ProductFilter, ProductSort> OrderBy(System.Linq.Expressions.Expression<System.Func<ProductSort, EconomicSortField>> selector) => AsQuery().OrderBy(selector);

    /// <summary>Orders descending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<Product, ProductFilter, ProductSort> OrderByDescending(System.Linq.Expressions.Expression<System.Func<ProductSort, EconomicSortField>> selector) => AsQuery().OrderByDescending(selector);

    /// <summary>Sets how many items are fetched per request.</summary>
    /// <param name="pageSize">Items per page, up to 1000.</param>
    /// <returns>A query using that page size.</returns>
    public EconomicOpenQuery<Product, ProductFilter, ProductSort> WithPageSize(int pageSize) => AsQuery().WithPageSize(pageSize);

    /// <summary>Enumerates everything, following the cursor.</summary>
    /// <param name="cancellationToken">Cancels the enumeration.</param>
    /// <returns>The items.</returns>
    public System.Collections.Generic.IAsyncEnumerable<Product> AsAsyncEnumerable(CancellationToken cancellationToken = default) => AsQuery().AsAsyncEnumerable(cancellationToken);

    /// <summary>Fetches one numbered page.</summary>
    /// <param name="pageIndex">Zero-based page index.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The page.</returns>
    public Task<IReadOnlyList<Product>> GetPageAsync(int pageIndex, CancellationToken cancellationToken = default) => AsQuery().GetPageAsync(pageIndex, cancellationToken);

    /// <summary>Fetches one record.</summary>
    /// <param name="productNumber">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The record.</returns>
    public async Task<Product> GetAsync(string productNumber, CancellationToken cancellationToken = default)
    {
        var response = await OpenTransport.SendAsync(
            () => _client.GetOneProductAsync(productNumber: productNumber, cancellationToken: cancellationToken),
            "GET /products/{productNumber}").ConfigureAwait(false);

        return ProductSource.Map(response);
    }

    /// <summary>Creates a record.</summary>
    /// <param name="item">The record to create, whose identifier you supply.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The identifier e-conomic stored it under.</returns>
    /// <remarks>
    /// The response carries the identifier and nothing else, so that is what this returns —
    /// unlike the legacy REST API, whose creates answer with the whole resource. Read it back
    /// with <c>GetAsync</c> if you need the stored record, which also gives you the
    /// <c>objectVersion</c> an update requires.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    public async Task<string?> CreateAsync(Product item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        var response = await OpenTransport.SendAsync(
            () => _client.CreateProductAsync(body: ProductSource.ToGenerated(item), cancellationToken: cancellationToken),
            "POST /products").ConfigureAwait(false);

        return response.ProductNumber;
    }

    /// <summary>Replaces a record.</summary>
    /// <param name="productNumber">The record to replace.</param>
    /// <param name="item">The replacement state, carrying the <c>objectVersion</c> that was read.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is replaced.</returns>
    /// <remarks>
    /// Updates are read-modify-write on this surface. The <c>objectVersion</c> from the record
    /// you read has to come back with it; a stale one, or none, is rejected with
    /// <see cref="Exceptions.EconomicConcurrencyException"/> and nothing is written.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    /// <exception cref="Exceptions.EconomicConcurrencyException">The record changed since it was read.</exception>
    public Task UpdateAsync(string productNumber, Product item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        return OpenTransport.SendAsync(
            () => _client.UpdateProductByIdAsync(productNumber: productNumber, body: ProductSource.ToGenerated(item), cancellationToken: cancellationToken),
            "PUT /products");
    }

    /// <summary>Deletes a record.</summary>
    /// <param name="productNumber">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is gone.</returns>
    public Task DeleteAsync(string productNumber, CancellationToken cancellationToken = default) =>
        OpenTransport.SendAsync(
            () => _client.DeleteProductByIdAsync(productNumber: productNumber, cancellationToken: cancellationToken),
            "DELETE /products/{productNumber}");
}

/// <summary>
/// A resource from <c>/productgroups</c>.
/// </summary>
/// <remarks>
/// The same shape is used to read, create and update: these services describe a resource once
/// and accept it back unchanged. Properties the server maintains are simply left unset.
/// </remarks>
public sealed record ProductGroup
{
    /// <summary>The <c>id</c> field.</summary>
    public required int Id { get; init; }

    /// <summary>The <c>name</c> field.</summary>
    public required string Name { get; init; }

    /// <summary>The <c>domesticAccountId</c> field.</summary>
    public required int DomesticAccountId { get; init; }

    /// <summary>The <c>objectVersion</c> field.</summary>
    public string? ObjectVersion { get; init; }
}

/// <summary>
/// What <c>/productgroups</c> can be filtered on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class ProductGroupFilter
{
    /// <summary>Maps to <c>id</c>.</summary>
    [EconomicField("id")]
    public NumericField<int> Id { get; } = null!;

    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public TextField Name { get; } = null!;
}

/// <summary>
/// What <c>/productgroups</c> can be sorted on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class ProductGroupSort
{
    /// <summary>Maps to <c>id</c>.</summary>
    [EconomicField("id")]
    public EconomicSortField Id { get; } = null!;

    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public EconomicSortField Name { get; } = null!;
}

/// <summary>Fetches <c>/productgroups</c> and maps it to <see cref="ProductGroup"/>.</summary>
internal sealed class ProductGroupSource(Raw.ProductGroupsClient client)
    : IEconomicOpenSource<ProductGroup>
{
    public async Task<EconomicCursorPage<ProductGroup>> GetCursorPageAsync(
        string? cursor, string? filter, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetAllProductGroupsAsync(cursor: cursor, filter: filter, cancellationToken: cancellationToken),
            "GET /productgroups").ConfigureAwait(false);

        var items = new List<ProductGroup>(response.Items?.Count ?? 0);
        foreach (var item in response.Items ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicCursorPage<ProductGroup>(items, response.Cursor);
    }

    public async Task<IReadOnlyList<ProductGroup>> GetPageAsync(
        string? filter, string? sort, int pageSize, int skipPages, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetPageOfProductGroupsAsync(filter: filter, sort: sort, pageSize: pageSize, skipPages: skipPages, cancellationToken: cancellationToken),
            "GET /productgroups/paged").ConfigureAwait(false);

        var items = new List<ProductGroup>(response?.Count ?? 0);
        foreach (var item in response ?? Array.Empty<Raw.ProductGroup>())
        {
            items.Add(Map(item));
        }

        return items;
    }

    public Task<int> CountAsync(string? filter, CancellationToken cancellationToken) =>
        OpenTransport.SendAsync(
            () => client.GetNumberOfProductGroupsAsync(filter: filter, cancellationToken: cancellationToken),
            "GET /productgroups/count");

    internal static ProductGroup Map(Raw.ProductGroup source) => new()
    {
        Id = source.Id,
        Name = source.Name,
        DomesticAccountId = source.DomesticAccountId,
        ObjectVersion = source.ObjectVersion,
    };

    internal static Raw.ProductGroup ToGenerated(ProductGroup source) => new()
    {
        Id = source.Id,
        Name = source.Name,
        DomesticAccountId = source.DomesticAccountId,
        ObjectVersion = source.ObjectVersion,
    };
}

/// <summary>
/// <c>/productgroups</c>, as a query and the writes the service supports.
/// </summary>
public sealed class ProductGroupResource
{
    private readonly Raw.ProductGroupsClient _client;

    internal ProductGroupResource(System.Net.Http.HttpClient httpClient, System.Uri baseAddress)
    {
        _client = new Raw.ProductGroupsClient(httpClient) { BaseUrl = baseAddress.ToString() };
    }

    /// <summary>This collection as a composable query.</summary>
    /// <returns>A query with no filter or ordering.</returns>
    public EconomicOpenQuery<ProductGroup, ProductGroupFilter, ProductGroupSort> AsQuery() => new(new ProductGroupSource(_client));

    /// <summary>Restricts what is returned.</summary>
    /// <param name="predicate">A filter over the filterable properties.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<ProductGroup, ProductGroupFilter, ProductGroupSort> Where(System.Linq.Expressions.Expression<System.Func<ProductGroupFilter, bool>> predicate) => AsQuery().Where(predicate);

    /// <summary>Restricts what is returned, using e-conomic's filter syntax directly.</summary>
    /// <param name="filter">A filter expression.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<ProductGroup, ProductGroupFilter, ProductGroupSort> WhereRaw(string filter) => AsQuery().WhereRaw(filter);

    /// <summary>Orders ascending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<ProductGroup, ProductGroupFilter, ProductGroupSort> OrderBy(System.Linq.Expressions.Expression<System.Func<ProductGroupSort, EconomicSortField>> selector) => AsQuery().OrderBy(selector);

    /// <summary>Orders descending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<ProductGroup, ProductGroupFilter, ProductGroupSort> OrderByDescending(System.Linq.Expressions.Expression<System.Func<ProductGroupSort, EconomicSortField>> selector) => AsQuery().OrderByDescending(selector);

    /// <summary>Sets how many items are fetched per request.</summary>
    /// <param name="pageSize">Items per page, up to 1000.</param>
    /// <returns>A query using that page size.</returns>
    public EconomicOpenQuery<ProductGroup, ProductGroupFilter, ProductGroupSort> WithPageSize(int pageSize) => AsQuery().WithPageSize(pageSize);

    /// <summary>Enumerates everything, following the cursor.</summary>
    /// <param name="cancellationToken">Cancels the enumeration.</param>
    /// <returns>The items.</returns>
    public System.Collections.Generic.IAsyncEnumerable<ProductGroup> AsAsyncEnumerable(CancellationToken cancellationToken = default) => AsQuery().AsAsyncEnumerable(cancellationToken);

    /// <summary>Counts everything in the collection.</summary>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The number of records.</returns>
    public Task<int> CountAsync(CancellationToken cancellationToken = default) => AsQuery().CountAsync(cancellationToken);

    /// <summary>Fetches one numbered page.</summary>
    /// <param name="pageIndex">Zero-based page index.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The page.</returns>
    public Task<IReadOnlyList<ProductGroup>> GetPageAsync(int pageIndex, CancellationToken cancellationToken = default) => AsQuery().GetPageAsync(pageIndex, cancellationToken);

    /// <summary>Fetches one record.</summary>
    /// <param name="number">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The record.</returns>
    public async Task<ProductGroup> GetAsync(int number, CancellationToken cancellationToken = default)
    {
        var response = await OpenTransport.SendAsync(
            () => _client.GetProductGroupByIdAsync(number: number, cancellationToken: cancellationToken),
            "GET /productgroups/{number}").ConfigureAwait(false);

        return ProductGroupSource.Map(response);
    }

    /// <summary>Creates a record.</summary>
    /// <param name="item">The record to create, whose identifier you supply.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The identifier e-conomic stored it under.</returns>
    /// <remarks>
    /// The response carries the identifier and nothing else, so that is what this returns —
    /// unlike the legacy REST API, whose creates answer with the whole resource. Read it back
    /// with <c>GetAsync</c> if you need the stored record, which also gives you the
    /// <c>objectVersion</c> an update requires.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    public async Task<int?> CreateAsync(ProductGroup item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        var response = await OpenTransport.SendAsync(
            () => _client.CreateProductGroupAsync(body: ProductGroupSource.ToGenerated(item), cancellationToken: cancellationToken),
            "POST /productgroups").ConfigureAwait(false);

        return response.Id;
    }

    /// <summary>Replaces a record.</summary>
    /// <param name="item">The replacement state, carrying the <c>objectVersion</c> that was read.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is replaced.</returns>
    /// <remarks>
    /// Updates are read-modify-write on this surface. The <c>objectVersion</c> from the record
    /// you read has to come back with it; a stale one, or none, is rejected with
    /// <see cref="Exceptions.EconomicConcurrencyException"/> and nothing is written.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    /// <exception cref="Exceptions.EconomicConcurrencyException">The record changed since it was read.</exception>
    public Task UpdateAsync(ProductGroup item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        return OpenTransport.SendAsync(
            () => _client.UpdateProductGroupByIdAsync(body: ProductGroupSource.ToGenerated(item), cancellationToken: cancellationToken),
            "PUT /productgroups");
    }

    /// <summary>Deletes a record.</summary>
    /// <param name="number">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is gone.</returns>
    public Task DeleteAsync(int number, CancellationToken cancellationToken = default) =>
        OpenTransport.SendAsync(
            () => _client.DeleteProductGroupByIdAsync(number: number, cancellationToken: cancellationToken),
            "DELETE /productgroups/{number}");
}

/// <summary>
/// A resource from <c>/salespriceincurrencies</c>.
/// </summary>
/// <remarks>
/// The same shape is used to read, create and update: these services describe a resource once
/// and accept it back unchanged. Properties the server maintains are simply left unset.
/// </remarks>
public sealed record ProductSalesPriceInCurrency
{
    /// <summary>The <c>productNumber</c> field.</summary>
    public string? ProductNumber { get; init; }

    /// <summary>The <c>currency</c> field.</summary>
    public required string Currency { get; init; }

    /// <summary>The <c>salesPrice</c> field.</summary>
    public required double SalesPrice { get; init; }

    /// <summary>The <c>objectVersion</c> field.</summary>
    public string? ObjectVersion { get; init; }
}

/// <summary>
/// What <c>/salespriceincurrencies</c> can be filtered on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class ProductSalesPriceInCurrencyFilter
{
    /// <summary>Maps to <c>productNumber</c>.</summary>
    [EconomicField("productNumber")]
    public EqualityField<string> ProductNumber { get; } = null!;

    /// <summary>Maps to <c>currency</c>.</summary>
    [EconomicField("currency")]
    public EqualityField<string> Currency { get; } = null!;
}

/// <summary>
/// What <c>/salespriceincurrencies</c> can be sorted on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class ProductSalesPriceInCurrencySort
{
    /// <summary>Maps to <c>productNumber</c>.</summary>
    [EconomicField("productNumber")]
    public EconomicSortField ProductNumber { get; } = null!;

    /// <summary>Maps to <c>currency</c>.</summary>
    [EconomicField("currency")]
    public EconomicSortField Currency { get; } = null!;
}

/// <summary>Fetches <c>/salespriceincurrencies</c> and maps it to <see cref="ProductSalesPriceInCurrency"/>.</summary>
internal sealed class ProductSalesPriceInCurrencySource(Raw.ProductSalesPriceInCurrenciesClient client)
    : IEconomicOpenSource<ProductSalesPriceInCurrency>
{
    public async Task<EconomicCursorPage<ProductSalesPriceInCurrency>> GetCursorPageAsync(
        string? cursor, string? filter, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetAllProductSalesPriceInCurrenciesAsync(cursor: cursor, filter: filter, cancellationToken: cancellationToken),
            "GET /salespriceincurrencies").ConfigureAwait(false);

        var items = new List<ProductSalesPriceInCurrency>(response.Items?.Count ?? 0);
        foreach (var item in response.Items ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicCursorPage<ProductSalesPriceInCurrency>(items, response.Cursor);
    }

    public async Task<IReadOnlyList<ProductSalesPriceInCurrency>> GetPageAsync(
        string? filter, string? sort, int pageSize, int skipPages, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetPageOfProductSalesPriceInCurrenciesAsync(filter: filter, sort: sort, pageSize: pageSize, skipPages: skipPages, cancellationToken: cancellationToken),
            "GET /salespriceincurrencies/paged").ConfigureAwait(false);

        var items = new List<ProductSalesPriceInCurrency>(response?.Count ?? 0);
        foreach (var item in response ?? Array.Empty<Raw.ProductSalesPriceInCurrency>())
        {
            items.Add(Map(item));
        }

        return items;
    }

    public Task<int> CountAsync(string? filter, CancellationToken cancellationToken) =>
        OpenTransport.SendAsync(
            () => client.GetNumberOfProductSalesPriceInCurrenciesAsync(filter: filter, cancellationToken: cancellationToken),
            "GET /salespriceincurrencies/count");

    internal static ProductSalesPriceInCurrency Map(Raw.ProductSalesPriceInCurrency source) => new()
    {
        ProductNumber = source.ProductNumber,
        Currency = source.Currency,
        SalesPrice = source.SalesPrice,
        ObjectVersion = source.ObjectVersion,
    };

    internal static Raw.ProductSalesPriceInCurrency ToGenerated(ProductSalesPriceInCurrency source) => new()
    {
        ProductNumber = source.ProductNumber,
        Currency = source.Currency,
        SalesPrice = source.SalesPrice,
        ObjectVersion = source.ObjectVersion,
    };
}

/// <summary>
/// <c>/salespriceincurrencies</c>, as a query and the writes the service supports.
/// </summary>
public sealed class ProductSalesPriceInCurrencyResource
{
    private readonly Raw.ProductSalesPriceInCurrenciesClient _client;

    internal ProductSalesPriceInCurrencyResource(System.Net.Http.HttpClient httpClient, System.Uri baseAddress)
    {
        _client = new Raw.ProductSalesPriceInCurrenciesClient(httpClient) { BaseUrl = baseAddress.ToString() };
    }

    /// <summary>This collection as a composable query.</summary>
    /// <returns>A query with no filter or ordering.</returns>
    public EconomicOpenQuery<ProductSalesPriceInCurrency, ProductSalesPriceInCurrencyFilter, ProductSalesPriceInCurrencySort> AsQuery() => new(new ProductSalesPriceInCurrencySource(_client));

    /// <summary>Restricts what is returned.</summary>
    /// <param name="predicate">A filter over the filterable properties.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<ProductSalesPriceInCurrency, ProductSalesPriceInCurrencyFilter, ProductSalesPriceInCurrencySort> Where(System.Linq.Expressions.Expression<System.Func<ProductSalesPriceInCurrencyFilter, bool>> predicate) => AsQuery().Where(predicate);

    /// <summary>Restricts what is returned, using e-conomic's filter syntax directly.</summary>
    /// <param name="filter">A filter expression.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<ProductSalesPriceInCurrency, ProductSalesPriceInCurrencyFilter, ProductSalesPriceInCurrencySort> WhereRaw(string filter) => AsQuery().WhereRaw(filter);

    /// <summary>Orders ascending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<ProductSalesPriceInCurrency, ProductSalesPriceInCurrencyFilter, ProductSalesPriceInCurrencySort> OrderBy(System.Linq.Expressions.Expression<System.Func<ProductSalesPriceInCurrencySort, EconomicSortField>> selector) => AsQuery().OrderBy(selector);

    /// <summary>Orders descending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<ProductSalesPriceInCurrency, ProductSalesPriceInCurrencyFilter, ProductSalesPriceInCurrencySort> OrderByDescending(System.Linq.Expressions.Expression<System.Func<ProductSalesPriceInCurrencySort, EconomicSortField>> selector) => AsQuery().OrderByDescending(selector);

    /// <summary>Sets how many items are fetched per request.</summary>
    /// <param name="pageSize">Items per page, up to 1000.</param>
    /// <returns>A query using that page size.</returns>
    public EconomicOpenQuery<ProductSalesPriceInCurrency, ProductSalesPriceInCurrencyFilter, ProductSalesPriceInCurrencySort> WithPageSize(int pageSize) => AsQuery().WithPageSize(pageSize);

    /// <summary>Enumerates everything, following the cursor.</summary>
    /// <param name="cancellationToken">Cancels the enumeration.</param>
    /// <returns>The items.</returns>
    public System.Collections.Generic.IAsyncEnumerable<ProductSalesPriceInCurrency> AsAsyncEnumerable(CancellationToken cancellationToken = default) => AsQuery().AsAsyncEnumerable(cancellationToken);

    /// <summary>Counts everything in the collection.</summary>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The number of records.</returns>
    public Task<int> CountAsync(CancellationToken cancellationToken = default) => AsQuery().CountAsync(cancellationToken);

    /// <summary>Fetches one numbered page.</summary>
    /// <param name="pageIndex">Zero-based page index.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The page.</returns>
    public Task<IReadOnlyList<ProductSalesPriceInCurrency>> GetPageAsync(int pageIndex, CancellationToken cancellationToken = default) => AsQuery().GetPageAsync(pageIndex, cancellationToken);
}

/// <summary>
/// A resource from <c>/pricegroups/{priceGroupNumber}/specialprices</c>.
/// </summary>
/// <remarks>
/// The same shape is used to read, create and update: these services describe a resource once
/// and accept it back unchanged. Properties the server maintains are simply left unset.
/// </remarks>
public sealed record ProductSpecialPrice
{
    /// <summary>The <c>number</c> field.</summary>
    public int? Number { get; init; }

    /// <summary>The <c>productNumber</c> field.</summary>
    public required string ProductNumber { get; init; }

    /// <summary>The <c>salesPriceBaseCurrency</c> field.</summary>
    public double? SalesPriceBaseCurrency { get; init; }

    /// <summary>The <c>discountPercentage</c> field.</summary>
    public double? DiscountPercentage { get; init; }

    /// <summary>The <c>objectVersion</c> field.</summary>
    public string? ObjectVersion { get; init; }
}

/// <summary>
/// What <c>/pricegroups/{priceGroupNumber}/specialprices</c> can be filtered on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class ProductSpecialPriceFilter
{
    /// <summary>Maps to <c>number</c>.</summary>
    [EconomicField("number")]
    public NumericField<int> Number { get; } = null!;

    /// <summary>Maps to <c>productNumber</c>.</summary>
    [EconomicField("productNumber")]
    public EqualityField<string> ProductNumber { get; } = null!;
}

/// <summary>
/// What <c>/pricegroups/{priceGroupNumber}/specialprices</c> can be sorted on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class ProductSpecialPriceSort
{
    /// <summary>Maps to <c>number</c>.</summary>
    [EconomicField("number")]
    public EconomicSortField Number { get; } = null!;
}

/// <summary>Fetches <c>/pricegroups/{priceGroupNumber}/specialprices</c> and maps it to <see cref="ProductSpecialPrice"/>.</summary>
internal sealed class ProductSpecialPriceSource(Raw.ProductSpecialPricesClient client, int priceGroupNumber)
    : IEconomicOpenSource<ProductSpecialPrice>
{
    public async Task<EconomicCursorPage<ProductSpecialPrice>> GetCursorPageAsync(
        string? cursor, string? filter, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetAllProductSpecialPricesAsync(priceGroupNumber: priceGroupNumber, cursor: cursor, filter: filter, cancellationToken: cancellationToken),
            "GET /pricegroups/{priceGroupNumber}/specialprices").ConfigureAwait(false);

        var items = new List<ProductSpecialPrice>(response.Items?.Count ?? 0);
        foreach (var item in response.Items ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicCursorPage<ProductSpecialPrice>(items, response.Cursor);
    }

    public async Task<IReadOnlyList<ProductSpecialPrice>> GetPageAsync(
        string? filter, string? sort, int pageSize, int skipPages, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetPageOfProductSpecialPricesAsync(priceGroupNumber: priceGroupNumber, filter: filter, sort: sort, pageSize: pageSize, skipPages: skipPages, cancellationToken: cancellationToken),
            "GET /pricegroups/{priceGroupNumber}/specialprices/paged").ConfigureAwait(false);

        var items = new List<ProductSpecialPrice>(response?.Count ?? 0);
        foreach (var item in response ?? Array.Empty<Raw.ProductSpecialPrice>())
        {
            items.Add(Map(item));
        }

        return items;
    }

    public Task<int> CountAsync(string? filter, CancellationToken cancellationToken) =>
        OpenTransport.SendAsync(
            () => client.GetNumberOfProductSpecialPricesAsync(priceGroupNumber: priceGroupNumber, filter: filter, cancellationToken: cancellationToken),
            "GET /pricegroups/{priceGroupNumber}/specialprices/count");

    internal static ProductSpecialPrice Map(Raw.ProductSpecialPrice source) => new()
    {
        Number = source.Number,
        ProductNumber = source.ProductNumber,
        SalesPriceBaseCurrency = source.SalesPriceBaseCurrency,
        DiscountPercentage = source.DiscountPercentage,
        ObjectVersion = source.ObjectVersion,
    };

    internal static Raw.ProductSpecialPrice ToGenerated(ProductSpecialPrice source) => new()
    {
        Number = source.Number,
        ProductNumber = source.ProductNumber,
        SalesPriceBaseCurrency = source.SalesPriceBaseCurrency,
        DiscountPercentage = source.DiscountPercentage,
        ObjectVersion = source.ObjectVersion,
    };
}

/// <summary>
/// <c>/pricegroups/{priceGroupNumber}/specialprices</c>, as a query and the writes the service supports.
/// </summary>
public sealed class ProductSpecialPriceResource
{
    private readonly Raw.ProductSpecialPricesClient _client;
    private readonly int _priceGroupNumber;

    internal ProductSpecialPriceResource(System.Net.Http.HttpClient httpClient, System.Uri baseAddress, int priceGroupNumber)
    {
        _client = new Raw.ProductSpecialPricesClient(httpClient) { BaseUrl = baseAddress.ToString() };
        _priceGroupNumber = priceGroupNumber;
    }

    /// <summary>This collection as a composable query.</summary>
    /// <returns>A query with no filter or ordering.</returns>
    public EconomicOpenQuery<ProductSpecialPrice, ProductSpecialPriceFilter, ProductSpecialPriceSort> AsQuery() => new(new ProductSpecialPriceSource(_client, _priceGroupNumber));

    /// <summary>Restricts what is returned.</summary>
    /// <param name="predicate">A filter over the filterable properties.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<ProductSpecialPrice, ProductSpecialPriceFilter, ProductSpecialPriceSort> Where(System.Linq.Expressions.Expression<System.Func<ProductSpecialPriceFilter, bool>> predicate) => AsQuery().Where(predicate);

    /// <summary>Restricts what is returned, using e-conomic's filter syntax directly.</summary>
    /// <param name="filter">A filter expression.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<ProductSpecialPrice, ProductSpecialPriceFilter, ProductSpecialPriceSort> WhereRaw(string filter) => AsQuery().WhereRaw(filter);

    /// <summary>Orders ascending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<ProductSpecialPrice, ProductSpecialPriceFilter, ProductSpecialPriceSort> OrderBy(System.Linq.Expressions.Expression<System.Func<ProductSpecialPriceSort, EconomicSortField>> selector) => AsQuery().OrderBy(selector);

    /// <summary>Orders descending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<ProductSpecialPrice, ProductSpecialPriceFilter, ProductSpecialPriceSort> OrderByDescending(System.Linq.Expressions.Expression<System.Func<ProductSpecialPriceSort, EconomicSortField>> selector) => AsQuery().OrderByDescending(selector);

    /// <summary>Sets how many items are fetched per request.</summary>
    /// <param name="pageSize">Items per page, up to 1000.</param>
    /// <returns>A query using that page size.</returns>
    public EconomicOpenQuery<ProductSpecialPrice, ProductSpecialPriceFilter, ProductSpecialPriceSort> WithPageSize(int pageSize) => AsQuery().WithPageSize(pageSize);

    /// <summary>Enumerates everything, following the cursor.</summary>
    /// <param name="cancellationToken">Cancels the enumeration.</param>
    /// <returns>The items.</returns>
    public System.Collections.Generic.IAsyncEnumerable<ProductSpecialPrice> AsAsyncEnumerable(CancellationToken cancellationToken = default) => AsQuery().AsAsyncEnumerable(cancellationToken);

    /// <summary>Counts everything in the collection.</summary>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The number of records.</returns>
    public Task<int> CountAsync(CancellationToken cancellationToken = default) => AsQuery().CountAsync(cancellationToken);

    /// <summary>Fetches one numbered page.</summary>
    /// <param name="pageIndex">Zero-based page index.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The page.</returns>
    public Task<IReadOnlyList<ProductSpecialPrice>> GetPageAsync(int pageIndex, CancellationToken cancellationToken = default) => AsQuery().GetPageAsync(pageIndex, cancellationToken);

    /// <summary>Fetches one record.</summary>
    /// <param name="number">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The record.</returns>
    public async Task<ProductSpecialPrice> GetAsync(int number, CancellationToken cancellationToken = default)
    {
        var response = await OpenTransport.SendAsync(
            () => _client.GetOneProductSpecialPriceAsync(priceGroupNumber: _priceGroupNumber, number: number, cancellationToken: cancellationToken),
            "GET /pricegroups/{priceGroupNumber}/specialprices/{number}").ConfigureAwait(false);

        return ProductSpecialPriceSource.Map(response);
    }

    /// <summary>Creates a record.</summary>
    /// <param name="item">The record to create, whose identifier you supply.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The identifier e-conomic stored it under.</returns>
    /// <remarks>
    /// The response carries the identifier and nothing else, so that is what this returns —
    /// unlike the legacy REST API, whose creates answer with the whole resource. Read it back
    /// with <c>GetAsync</c> if you need the stored record, which also gives you the
    /// <c>objectVersion</c> an update requires.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    public async Task<int?> CreateAsync(ProductSpecialPrice item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        var response = await OpenTransport.SendAsync(
            () => _client.CreateProductSpecialPriceAsync(priceGroupNumber: _priceGroupNumber, body: ProductSpecialPriceSource.ToGenerated(item), cancellationToken: cancellationToken),
            "POST /pricegroups/{priceGroupNumber}/specialprices").ConfigureAwait(false);

        return response.Number;
    }

    /// <summary>Replaces a record.</summary>
    /// <param name="item">The replacement state, carrying the <c>objectVersion</c> that was read.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is replaced.</returns>
    /// <remarks>
    /// Updates are read-modify-write on this surface. The <c>objectVersion</c> from the record
    /// you read has to come back with it; a stale one, or none, is rejected with
    /// <see cref="Exceptions.EconomicConcurrencyException"/> and nothing is written.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    /// <exception cref="Exceptions.EconomicConcurrencyException">The record changed since it was read.</exception>
    public Task UpdateAsync(ProductSpecialPrice item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        return OpenTransport.SendAsync(
            () => _client.UpdateProductSpecialPriceByIdAsync(priceGroupNumber: _priceGroupNumber, body: ProductSpecialPriceSource.ToGenerated(item), cancellationToken: cancellationToken),
            "PUT /pricegroups/{priceGroupNumber}/specialprices");
    }

    /// <summary>Deletes a record.</summary>
    /// <param name="number">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is gone.</returns>
    public Task DeleteAsync(int number, CancellationToken cancellationToken = default) =>
        OpenTransport.SendAsync(
            () => _client.DeleteProductSpecialPriceByIdAsync(priceGroupNumber: _priceGroupNumber, number: number, cancellationToken: cancellationToken),
            "DELETE /pricegroups/{priceGroupNumber}/specialprices/{number}");
}

/// <summary>
/// A resource from <c>/specialprices/{productSpecialPriceNumber}/specialpricesincurrency</c>.
/// </summary>
/// <remarks>
/// The same shape is used to read, create and update: these services describe a resource once
/// and accept it back unchanged. Properties the server maintains are simply left unset.
/// </remarks>
public sealed record ProductSpecialPriceInCurrency
{
    /// <summary>The <c>currency</c> field.</summary>
    public required string Currency { get; init; }

    /// <summary>The <c>salesPrice</c> field.</summary>
    public required double SalesPrice { get; init; }

    /// <summary>The <c>objectVersion</c> field.</summary>
    public string? ObjectVersion { get; init; }
}

/// <summary>
/// What <c>/specialprices/{productSpecialPriceNumber}/specialpricesincurrency</c> can be filtered on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class ProductSpecialPriceInCurrencyFilter
{
    /// <summary>Maps to <c>currency</c>.</summary>
    [EconomicField("currency")]
    public EqualityField<string> Currency { get; } = null!;
}

/// <summary>
/// What <c>/specialprices/{productSpecialPriceNumber}/specialpricesincurrency</c> can be sorted on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class ProductSpecialPriceInCurrencySort
{
    /// <summary>Maps to <c>currency</c>.</summary>
    [EconomicField("currency")]
    public EconomicSortField Currency { get; } = null!;
}

/// <summary>Fetches <c>/specialprices/{productSpecialPriceNumber}/specialpricesincurrency</c> and maps it to <see cref="ProductSpecialPriceInCurrency"/>.</summary>
internal sealed class ProductSpecialPriceInCurrencySource(Raw.ProductSpecialPricesInCurrencyClient client, int productSpecialPriceNumber)
    : IEconomicOpenSource<ProductSpecialPriceInCurrency>
{
    public async Task<EconomicCursorPage<ProductSpecialPriceInCurrency>> GetCursorPageAsync(
        string? cursor, string? filter, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetAllProductSpecialPricesInCurrencyAsync(productSpecialPriceNumber: productSpecialPriceNumber, cursor: cursor, filter: filter, cancellationToken: cancellationToken),
            "GET /specialprices/{productSpecialPriceNumber}/specialpricesincurrency").ConfigureAwait(false);

        var items = new List<ProductSpecialPriceInCurrency>(response.Items?.Count ?? 0);
        foreach (var item in response.Items ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicCursorPage<ProductSpecialPriceInCurrency>(items, response.Cursor);
    }

    public async Task<IReadOnlyList<ProductSpecialPriceInCurrency>> GetPageAsync(
        string? filter, string? sort, int pageSize, int skipPages, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetPageOfProductSpecialPricesInCurrencyAsync(productSpecialPriceNumber: productSpecialPriceNumber, filter: filter, sort: sort, pageSize: pageSize, skipPages: skipPages, cancellationToken: cancellationToken),
            "GET /specialprices/{productSpecialPriceNumber}/specialpricesincurrency/paged").ConfigureAwait(false);

        var items = new List<ProductSpecialPriceInCurrency>(response?.Count ?? 0);
        foreach (var item in response ?? Array.Empty<Raw.ProductSpecialPriceInCurrency>())
        {
            items.Add(Map(item));
        }

        return items;
    }

    public Task<int> CountAsync(string? filter, CancellationToken cancellationToken) =>
        OpenTransport.SendAsync(
            () => client.GetNumberOfProductSpecialPricesInCurrencyAsync(productSpecialPriceNumber: productSpecialPriceNumber, filter: filter, cancellationToken: cancellationToken),
            "GET /specialprices/{productSpecialPriceNumber}/specialpricesincurrency/count");

    internal static ProductSpecialPriceInCurrency Map(Raw.ProductSpecialPriceInCurrency source) => new()
    {
        Currency = source.Currency,
        SalesPrice = source.SalesPrice,
        ObjectVersion = source.ObjectVersion,
    };

    internal static Raw.ProductSpecialPriceInCurrency ToGenerated(ProductSpecialPriceInCurrency source) => new()
    {
        Currency = source.Currency,
        SalesPrice = source.SalesPrice,
        ObjectVersion = source.ObjectVersion,
    };
}

/// <summary>
/// <c>/specialprices/{productSpecialPriceNumber}/specialpricesincurrency</c>, as a query and the writes the service supports.
/// </summary>
public sealed class ProductSpecialPriceInCurrencyResource
{
    private readonly Raw.ProductSpecialPricesInCurrencyClient _client;
    private readonly int _productSpecialPriceNumber;

    internal ProductSpecialPriceInCurrencyResource(System.Net.Http.HttpClient httpClient, System.Uri baseAddress, int productSpecialPriceNumber)
    {
        _client = new Raw.ProductSpecialPricesInCurrencyClient(httpClient) { BaseUrl = baseAddress.ToString() };
        _productSpecialPriceNumber = productSpecialPriceNumber;
    }

    /// <summary>This collection as a composable query.</summary>
    /// <returns>A query with no filter or ordering.</returns>
    public EconomicOpenQuery<ProductSpecialPriceInCurrency, ProductSpecialPriceInCurrencyFilter, ProductSpecialPriceInCurrencySort> AsQuery() => new(new ProductSpecialPriceInCurrencySource(_client, _productSpecialPriceNumber));

    /// <summary>Restricts what is returned.</summary>
    /// <param name="predicate">A filter over the filterable properties.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<ProductSpecialPriceInCurrency, ProductSpecialPriceInCurrencyFilter, ProductSpecialPriceInCurrencySort> Where(System.Linq.Expressions.Expression<System.Func<ProductSpecialPriceInCurrencyFilter, bool>> predicate) => AsQuery().Where(predicate);

    /// <summary>Restricts what is returned, using e-conomic's filter syntax directly.</summary>
    /// <param name="filter">A filter expression.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<ProductSpecialPriceInCurrency, ProductSpecialPriceInCurrencyFilter, ProductSpecialPriceInCurrencySort> WhereRaw(string filter) => AsQuery().WhereRaw(filter);

    /// <summary>Orders ascending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<ProductSpecialPriceInCurrency, ProductSpecialPriceInCurrencyFilter, ProductSpecialPriceInCurrencySort> OrderBy(System.Linq.Expressions.Expression<System.Func<ProductSpecialPriceInCurrencySort, EconomicSortField>> selector) => AsQuery().OrderBy(selector);

    /// <summary>Orders descending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<ProductSpecialPriceInCurrency, ProductSpecialPriceInCurrencyFilter, ProductSpecialPriceInCurrencySort> OrderByDescending(System.Linq.Expressions.Expression<System.Func<ProductSpecialPriceInCurrencySort, EconomicSortField>> selector) => AsQuery().OrderByDescending(selector);

    /// <summary>Sets how many items are fetched per request.</summary>
    /// <param name="pageSize">Items per page, up to 1000.</param>
    /// <returns>A query using that page size.</returns>
    public EconomicOpenQuery<ProductSpecialPriceInCurrency, ProductSpecialPriceInCurrencyFilter, ProductSpecialPriceInCurrencySort> WithPageSize(int pageSize) => AsQuery().WithPageSize(pageSize);

    /// <summary>Enumerates everything, following the cursor.</summary>
    /// <param name="cancellationToken">Cancels the enumeration.</param>
    /// <returns>The items.</returns>
    public System.Collections.Generic.IAsyncEnumerable<ProductSpecialPriceInCurrency> AsAsyncEnumerable(CancellationToken cancellationToken = default) => AsQuery().AsAsyncEnumerable(cancellationToken);

    /// <summary>Counts everything in the collection.</summary>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The number of records.</returns>
    public Task<int> CountAsync(CancellationToken cancellationToken = default) => AsQuery().CountAsync(cancellationToken);

    /// <summary>Fetches one numbered page.</summary>
    /// <param name="pageIndex">Zero-based page index.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The page.</returns>
    public Task<IReadOnlyList<ProductSpecialPriceInCurrency>> GetPageAsync(int pageIndex, CancellationToken cancellationToken = default) => AsQuery().GetPageAsync(pageIndex, cancellationToken);

    /// <summary>Fetches one record.</summary>
    /// <param name="currency">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The record.</returns>
    public async Task<ProductSpecialPriceInCurrency> GetAsync(string currency, CancellationToken cancellationToken = default)
    {
        var response = await OpenTransport.SendAsync(
            () => _client.GetOneProductSpecialPriceInCurrencyAsync(productSpecialPriceNumber: _productSpecialPriceNumber, currency: currency, cancellationToken: cancellationToken),
            "GET /specialprices/{productSpecialPriceNumber}/specialpricesincurrency/{currency}").ConfigureAwait(false);

        return ProductSpecialPriceInCurrencySource.Map(response);
    }

    /// <summary>Creates a record.</summary>
    /// <param name="item">The record to create, whose identifier you supply.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The identifier e-conomic stored it under.</returns>
    /// <remarks>
    /// The response carries the identifier and nothing else, so that is what this returns —
    /// unlike the legacy REST API, whose creates answer with the whole resource. Read it back
    /// with <c>GetAsync</c> if you need the stored record, which also gives you the
    /// <c>objectVersion</c> an update requires.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    public async Task<string?> CreateAsync(ProductSpecialPriceInCurrency item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        var response = await OpenTransport.SendAsync(
            () => _client.CreateProductSpecialPriceInCurrencyAsync(productSpecialPriceNumber: _productSpecialPriceNumber, body: ProductSpecialPriceInCurrencySource.ToGenerated(item), cancellationToken: cancellationToken),
            "POST /specialprices/{productSpecialPriceNumber}/specialpricesincurrency").ConfigureAwait(false);

        return response.Currency;
    }

    /// <summary>Replaces a record.</summary>
    /// <param name="item">The replacement state, carrying the <c>objectVersion</c> that was read.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is replaced.</returns>
    /// <remarks>
    /// Updates are read-modify-write on this surface. The <c>objectVersion</c> from the record
    /// you read has to come back with it; a stale one, or none, is rejected with
    /// <see cref="Exceptions.EconomicConcurrencyException"/> and nothing is written.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    /// <exception cref="Exceptions.EconomicConcurrencyException">The record changed since it was read.</exception>
    public Task UpdateAsync(ProductSpecialPriceInCurrency item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        return OpenTransport.SendAsync(
            () => _client.UpdateProductSpecialPriceInCurrencyByIdAsync(productSpecialPriceNumber: _productSpecialPriceNumber, body: ProductSpecialPriceInCurrencySource.ToGenerated(item), cancellationToken: cancellationToken),
            "PUT /specialprices/{productSpecialPriceNumber}/specialpricesincurrency");
    }

    /// <summary>Deletes a record.</summary>
    /// <param name="currency">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is gone.</returns>
    public Task DeleteAsync(string currency, CancellationToken cancellationToken = default) =>
        OpenTransport.SendAsync(
            () => _client.DeleteProductSpecialPriceInCurrencyByIdAsync(productSpecialPriceNumber: _productSpecialPriceNumber, currency: currency, cancellationToken: cancellationToken),
            "DELETE /specialprices/{productSpecialPriceNumber}/specialpricesincurrency/{currency}");
}

/// <summary>
/// A resource from <c>/productgroups/{productGroupNumber}/zones</c>.
/// </summary>
/// <remarks>
/// The same shape is used to read, create and update: these services describe a resource once
/// and accept it back unchanged. Properties the server maintains are simply left unset.
/// </remarks>
public sealed record ProductZone
{
    /// <summary>The <c>id</c> field.</summary>
    public required int Id { get; init; }

    /// <summary>The <c>accountId</c> field.</summary>
    public required int AccountId { get; init; }

    /// <summary>The <c>objectVersion</c> field.</summary>
    public string? ObjectVersion { get; init; }
}

/// <summary>
/// What <c>/productgroups/{productGroupNumber}/zones</c> can be filtered on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class ProductZoneFilter
{
    /// <summary>Maps to <c>id</c>.</summary>
    [EconomicField("id")]
    public NumericField<int> Id { get; } = null!;

    /// <summary>Maps to <c>accountId</c>.</summary>
    [EconomicField("accountId")]
    public NumericField<int> AccountId { get; } = null!;
}

/// <summary>
/// What <c>/productgroups/{productGroupNumber}/zones</c> can be sorted on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class ProductZoneSort
{
    /// <summary>Maps to <c>id</c>.</summary>
    [EconomicField("id")]
    public EconomicSortField Id { get; } = null!;

    /// <summary>Maps to <c>accountId</c>.</summary>
    [EconomicField("accountId")]
    public EconomicSortField AccountId { get; } = null!;
}

/// <summary>Fetches <c>/productgroups/{productGroupNumber}/zones</c> and maps it to <see cref="ProductZone"/>.</summary>
internal sealed class ProductZoneSource(Raw.ZonesClient client, int productGroupNumber)
    : IEconomicOpenSource<ProductZone>
{
    public async Task<EconomicCursorPage<ProductZone>> GetCursorPageAsync(
        string? cursor, string? filter, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetAllZonesAsync(productGroupNumber: productGroupNumber, cursor: cursor, filter: filter, cancellationToken: cancellationToken),
            "GET /productgroups/{productGroupNumber}/zones").ConfigureAwait(false);

        var items = new List<ProductZone>(response.Items?.Count ?? 0);
        foreach (var item in response.Items ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicCursorPage<ProductZone>(items, response.Cursor);
    }

    public async Task<IReadOnlyList<ProductZone>> GetPageAsync(
        string? filter, string? sort, int pageSize, int skipPages, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetPageOfZonesAsync(productGroupNumber: productGroupNumber, filter: filter, sort: sort, pageSize: pageSize, skipPages: skipPages, cancellationToken: cancellationToken),
            "GET /productgroups/{productGroupNumber}/zones/paged").ConfigureAwait(false);

        var items = new List<ProductZone>(response?.Count ?? 0);
        foreach (var item in response ?? Array.Empty<Raw.Zone>())
        {
            items.Add(Map(item));
        }

        return items;
    }

    public Task<int> CountAsync(string? filter, CancellationToken cancellationToken) =>
        OpenTransport.SendAsync(
            () => client.GetNumberOfZonesAsync(productGroupNumber: productGroupNumber, filter: filter, cancellationToken: cancellationToken),
            "GET /productgroups/{productGroupNumber}/zones/count");

    internal static ProductZone Map(Raw.Zone source) => new()
    {
        Id = source.Id,
        AccountId = source.AccountId,
        ObjectVersion = source.ObjectVersion,
    };

    internal static Raw.Zone ToGenerated(ProductZone source) => new()
    {
        Id = source.Id,
        AccountId = source.AccountId,
        ObjectVersion = source.ObjectVersion,
    };
}

/// <summary>
/// <c>/productgroups/{productGroupNumber}/zones</c>, as a query and the writes the service supports.
/// </summary>
public sealed class ProductZoneResource
{
    private readonly Raw.ZonesClient _client;
    private readonly int _productGroupNumber;

    internal ProductZoneResource(System.Net.Http.HttpClient httpClient, System.Uri baseAddress, int productGroupNumber)
    {
        _client = new Raw.ZonesClient(httpClient) { BaseUrl = baseAddress.ToString() };
        _productGroupNumber = productGroupNumber;
    }

    /// <summary>This collection as a composable query.</summary>
    /// <returns>A query with no filter or ordering.</returns>
    public EconomicOpenQuery<ProductZone, ProductZoneFilter, ProductZoneSort> AsQuery() => new(new ProductZoneSource(_client, _productGroupNumber));

    /// <summary>Restricts what is returned.</summary>
    /// <param name="predicate">A filter over the filterable properties.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<ProductZone, ProductZoneFilter, ProductZoneSort> Where(System.Linq.Expressions.Expression<System.Func<ProductZoneFilter, bool>> predicate) => AsQuery().Where(predicate);

    /// <summary>Restricts what is returned, using e-conomic's filter syntax directly.</summary>
    /// <param name="filter">A filter expression.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<ProductZone, ProductZoneFilter, ProductZoneSort> WhereRaw(string filter) => AsQuery().WhereRaw(filter);

    /// <summary>Orders ascending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<ProductZone, ProductZoneFilter, ProductZoneSort> OrderBy(System.Linq.Expressions.Expression<System.Func<ProductZoneSort, EconomicSortField>> selector) => AsQuery().OrderBy(selector);

    /// <summary>Orders descending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<ProductZone, ProductZoneFilter, ProductZoneSort> OrderByDescending(System.Linq.Expressions.Expression<System.Func<ProductZoneSort, EconomicSortField>> selector) => AsQuery().OrderByDescending(selector);

    /// <summary>Sets how many items are fetched per request.</summary>
    /// <param name="pageSize">Items per page, up to 1000.</param>
    /// <returns>A query using that page size.</returns>
    public EconomicOpenQuery<ProductZone, ProductZoneFilter, ProductZoneSort> WithPageSize(int pageSize) => AsQuery().WithPageSize(pageSize);

    /// <summary>Enumerates everything, following the cursor.</summary>
    /// <param name="cancellationToken">Cancels the enumeration.</param>
    /// <returns>The items.</returns>
    public System.Collections.Generic.IAsyncEnumerable<ProductZone> AsAsyncEnumerable(CancellationToken cancellationToken = default) => AsQuery().AsAsyncEnumerable(cancellationToken);

    /// <summary>Counts everything in the collection.</summary>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The number of records.</returns>
    public Task<int> CountAsync(CancellationToken cancellationToken = default) => AsQuery().CountAsync(cancellationToken);

    /// <summary>Fetches one numbered page.</summary>
    /// <param name="pageIndex">Zero-based page index.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The page.</returns>
    public Task<IReadOnlyList<ProductZone>> GetPageAsync(int pageIndex, CancellationToken cancellationToken = default) => AsQuery().GetPageAsync(pageIndex, cancellationToken);

    /// <summary>Fetches one record.</summary>
    /// <param name="number">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The record.</returns>
    public async Task<ProductZone> GetAsync(int number, CancellationToken cancellationToken = default)
    {
        var response = await OpenTransport.SendAsync(
            () => _client.GetZoneByIdAsync(productGroupNumber: _productGroupNumber, number: number, cancellationToken: cancellationToken),
            "GET /productgroups/{productGroupNumber}/zones/{number}").ConfigureAwait(false);

        return ProductZoneSource.Map(response);
    }

    /// <summary>Creates a record.</summary>
    /// <param name="item">The record to create, whose identifier you supply.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The identifier e-conomic stored it under.</returns>
    /// <remarks>
    /// The response carries the identifier and nothing else, so that is what this returns —
    /// unlike the legacy REST API, whose creates answer with the whole resource. Read it back
    /// with <c>GetAsync</c> if you need the stored record, which also gives you the
    /// <c>objectVersion</c> an update requires.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    public async Task<int?> CreateAsync(ProductZone item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        var response = await OpenTransport.SendAsync(
            () => _client.CreateZoneAsync(productGroupNumber: _productGroupNumber, body: ProductZoneSource.ToGenerated(item), cancellationToken: cancellationToken),
            "POST /productgroups/{productGroupNumber}/zones").ConfigureAwait(false);

        return response.Id;
    }

    /// <summary>Replaces a record.</summary>
    /// <param name="item">The replacement state, carrying the <c>objectVersion</c> that was read.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is replaced.</returns>
    /// <remarks>
    /// Updates are read-modify-write on this surface. The <c>objectVersion</c> from the record
    /// you read has to come back with it; a stale one, or none, is rejected with
    /// <see cref="Exceptions.EconomicConcurrencyException"/> and nothing is written.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    /// <exception cref="Exceptions.EconomicConcurrencyException">The record changed since it was read.</exception>
    public Task UpdateAsync(ProductZone item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        return OpenTransport.SendAsync(
            () => _client.UpdateZoneByIdAsync(productGroupNumber: _productGroupNumber, body: ProductZoneSource.ToGenerated(item), cancellationToken: cancellationToken),
            "PUT /productgroups/{productGroupNumber}/zones");
    }

    /// <summary>Deletes a record.</summary>
    /// <param name="number">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is gone.</returns>
    public Task DeleteAsync(int number, CancellationToken cancellationToken = default) =>
        OpenTransport.SendAsync(
            () => _client.DeleteZoneByIdAsync(productGroupNumber: _productGroupNumber, number: number, cancellationToken: cancellationToken),
            "DELETE /productgroups/{productGroupNumber}/zones/{number}");
}
