// <auto-generated>
//     Generated by tools/EConomic.SpecConverter (open-facade).
//     Regenerate after a spec refresh; do not edit by hand.
// </auto-generated>
#nullable enable

using EConomic.Querying;
using Raw = EConomic.Open.Generated.Q2C;

namespace EConomic.Open;

/// <summary>
/// A resource from <c>/invoices/booked/lines</c>.
/// </summary>
/// <remarks>
/// The same shape is used to read, create and update: these services describe a resource once
/// and accept it back unchanged. Properties the server maintains are simply left unset.
/// </remarks>
public sealed record SalesBookedInvoiceLine
{
    /// <summary>The <c>documentId</c> field.</summary>
    public int? DocumentId { get; init; }

    /// <summary>The <c>number</c> field.</summary>
    public int? Number { get; init; }

    /// <summary>The <c>userInterfaceNumber</c> field.</summary>
    public int? UserInterfaceNumber { get; init; }

    /// <summary>The <c>productNumber</c> field.</summary>
    public string? ProductNumber { get; init; }

    /// <summary>The <c>description</c> field.</summary>
    public string? Description { get; init; }

    /// <summary>The <c>quantity</c> field.</summary>
    public double? Quantity { get; init; }

    /// <summary>The <c>unitNumber</c> field.</summary>
    public int? UnitNumber { get; init; }

    /// <summary>The <c>unitNetPrice</c> field.</summary>
    public double? UnitNetPrice { get; init; }

    /// <summary>The <c>unitCostPrice</c> field.</summary>
    public double? UnitCostPrice { get; init; }

    /// <summary>The <c>discountPercentage</c> field.</summary>
    public double? DiscountPercentage { get; init; }

    /// <summary>The <c>recommendedPrice</c> field.</summary>
    public double? RecommendedPrice { get; init; }

    /// <summary>The <c>departmentNumber</c> field.</summary>
    public int? DepartmentNumber { get; init; }

    /// <summary>The <c>quantity2</c> field.</summary>
    public double? Quantity2 { get; init; }

    /// <summary>The <c>unit2Number</c> field.</summary>
    public int? Unit2Number { get; init; }

    /// <summary>The <c>bookedAccount</c> field.</summary>
    public int? BookedAccount { get; init; }

    /// <summary>The <c>projectCloseAccount</c> field.</summary>
    public int? ProjectCloseAccount { get; init; }

    /// <summary>The <c>accrue</c> field.</summary>
    public bool? Accrue { get; init; }

    /// <summary>The <c>accrueStartDate</c> field.</summary>
    public System.DateTimeOffset? AccrueStartDate { get; init; }

    /// <summary>The <c>accrueEndDate</c> field.</summary>
    public System.DateTimeOffset? AccrueEndDate { get; init; }

    /// <summary>The <c>vatRate</c> field.</summary>
    public double? VatRate { get; init; }

    /// <summary>The <c>vatAmount</c> field.</summary>
    public double? VatAmount { get; init; }

    /// <summary>The <c>totalNetAmount</c> field.</summary>
    public double? TotalNetAmount { get; init; }
}

/// <summary>
/// What <c>/invoices/booked/lines</c> can be filtered on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class SalesBookedInvoiceLineFilter
{
    /// <summary>Maps to <c>documentId</c>.</summary>
    [EconomicField("documentId")]
    public NumericField<int> DocumentId { get; } = null!;

    /// <summary>Maps to <c>number</c>.</summary>
    [EconomicField("number")]
    public NumericField<int> Number { get; } = null!;

    /// <summary>Maps to <c>userInterfaceNumber</c>.</summary>
    [EconomicField("userInterfaceNumber")]
    public NumericField<int> UserInterfaceNumber { get; } = null!;

    /// <summary>Maps to <c>productNumber</c>.</summary>
    [EconomicField("productNumber")]
    public EqualityField<string> ProductNumber { get; } = null!;

    /// <summary>Maps to <c>discountPercentage</c>.</summary>
    [EconomicField("discountPercentage")]
    public NumericField<double> DiscountPercentage { get; } = null!;

    /// <summary>Maps to <c>departmentNumber</c>.</summary>
    [EconomicField("departmentNumber")]
    public NumericField<int> DepartmentNumber { get; } = null!;

    /// <summary>Maps to <c>bookedAccount</c>.</summary>
    [EconomicField("bookedAccount")]
    public NumericField<int> BookedAccount { get; } = null!;

    /// <summary>Maps to <c>projectCloseAccount</c>.</summary>
    [EconomicField("projectCloseAccount")]
    public NumericField<int> ProjectCloseAccount { get; } = null!;
}

/// <summary>
/// What <c>/invoices/booked/lines</c> can be sorted on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class SalesBookedInvoiceLineSort
{
    /// <summary>Maps to <c>documentId</c>.</summary>
    [EconomicField("documentId")]
    public EconomicSortField DocumentId { get; } = null!;

    /// <summary>Maps to <c>number</c>.</summary>
    [EconomicField("number")]
    public EconomicSortField Number { get; } = null!;

    /// <summary>Maps to <c>userInterfaceNumber</c>.</summary>
    [EconomicField("userInterfaceNumber")]
    public EconomicSortField UserInterfaceNumber { get; } = null!;
}

/// <summary>Fetches <c>/invoices/booked/lines</c> and maps it to <see cref="SalesBookedInvoiceLine"/>.</summary>
internal sealed class SalesBookedInvoiceLineSource(Raw.BookedInvoiceLinesClient client)
    : IEconomicOpenSource<SalesBookedInvoiceLine>
{
    public bool CanCursor => true;

    public bool CanPage => true;

    public async Task<EconomicCursorPage<SalesBookedInvoiceLine>> GetCursorPageAsync(
        string? cursor, string? filter, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetAllBookedInvoiceLinesAsync(cursor: cursor, filter: filter, cancellationToken: cancellationToken),
            "GET /invoices/booked/lines").ConfigureAwait(false);

        var items = new List<SalesBookedInvoiceLine>(response.Items?.Count ?? 0);
        foreach (var item in response.Items ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicCursorPage<SalesBookedInvoiceLine>(items, response.Cursor);
    }

    public async Task<IReadOnlyList<SalesBookedInvoiceLine>> GetPageAsync(
        string? filter, string? sort, int pageSize, int skipPages, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetPageOfBookedInvoiceLinesAsync(filter: filter, sort: sort, pageSize: pageSize, skipPages: skipPages, cancellationToken: cancellationToken),
            "GET /invoices/booked/lines/paged").ConfigureAwait(false);

        var items = new List<SalesBookedInvoiceLine>(response?.Count ?? 0);
        foreach (var item in response ?? Array.Empty<Raw.BookedInvoiceLine>())
        {
            items.Add(Map(item));
        }

        return items;
    }

    public Task<int> CountAsync(string? filter, CancellationToken cancellationToken) =>
        OpenTransport.SendAsync(
            () => client.GetNumberOfBookedInvoiceLinesAsync(filter: filter, cancellationToken: cancellationToken),
            "GET /invoices/booked/lines/count");

    internal static SalesBookedInvoiceLine Map(Raw.BookedInvoiceLine source) => new()
    {
        DocumentId = source.DocumentId,
        Number = source.Number,
        UserInterfaceNumber = source.UserInterfaceNumber,
        ProductNumber = source.ProductNumber,
        Description = source.Description,
        Quantity = source.Quantity,
        UnitNumber = source.UnitNumber,
        UnitNetPrice = source.UnitNetPrice,
        UnitCostPrice = source.UnitCostPrice,
        DiscountPercentage = source.DiscountPercentage,
        RecommendedPrice = source.RecommendedPrice,
        DepartmentNumber = source.DepartmentNumber,
        Quantity2 = source.Quantity2,
        Unit2Number = source.Unit2Number,
        BookedAccount = source.BookedAccount,
        ProjectCloseAccount = source.ProjectCloseAccount,
        Accrue = source.Accrue,
        AccrueStartDate = source.AccrueStartDate,
        AccrueEndDate = source.AccrueEndDate,
        VatRate = source.VatRate,
        VatAmount = source.VatAmount,
        TotalNetAmount = source.TotalNetAmount,
    };

    internal static Raw.BookedInvoiceLine ToGenerated(SalesBookedInvoiceLine source) => new()
    {
        DocumentId = source.DocumentId,
        Number = source.Number,
        UserInterfaceNumber = source.UserInterfaceNumber,
        ProductNumber = source.ProductNumber,
        Description = source.Description,
        Quantity = source.Quantity,
        UnitNumber = source.UnitNumber,
        UnitNetPrice = source.UnitNetPrice,
        UnitCostPrice = source.UnitCostPrice,
        DiscountPercentage = source.DiscountPercentage,
        RecommendedPrice = source.RecommendedPrice,
        DepartmentNumber = source.DepartmentNumber,
        Quantity2 = source.Quantity2,
        Unit2Number = source.Unit2Number,
        BookedAccount = source.BookedAccount,
        ProjectCloseAccount = source.ProjectCloseAccount,
        Accrue = source.Accrue,
        AccrueStartDate = source.AccrueStartDate,
        AccrueEndDate = source.AccrueEndDate,
        VatRate = source.VatRate,
        VatAmount = source.VatAmount,
        TotalNetAmount = source.TotalNetAmount,
    };
}

/// <summary>
/// <c>/invoices/booked/lines</c>, as a query and the writes the service supports.
/// </summary>
public sealed class SalesBookedInvoiceLineResource
{
    private readonly Raw.BookedInvoiceLinesClient _client;

    internal SalesBookedInvoiceLineResource(System.Net.Http.HttpClient httpClient, System.Uri baseAddress)
    {
        _client = new Raw.BookedInvoiceLinesClient(httpClient) { BaseUrl = baseAddress.ToString() };
    }

    /// <summary>This collection as a composable query.</summary>
    /// <returns>A query with no filter or ordering.</returns>
    public EconomicOpenQuery<SalesBookedInvoiceLine, SalesBookedInvoiceLineFilter, SalesBookedInvoiceLineSort> AsQuery() => new(new SalesBookedInvoiceLineSource(_client));

    /// <summary>Restricts what is returned.</summary>
    /// <param name="predicate">A filter over the filterable properties.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<SalesBookedInvoiceLine, SalesBookedInvoiceLineFilter, SalesBookedInvoiceLineSort> Where(System.Linq.Expressions.Expression<System.Func<SalesBookedInvoiceLineFilter, bool>> predicate) => AsQuery().Where(predicate);

    /// <summary>Restricts what is returned, using e-conomic's filter syntax directly.</summary>
    /// <param name="filter">A filter expression.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<SalesBookedInvoiceLine, SalesBookedInvoiceLineFilter, SalesBookedInvoiceLineSort> WhereRaw(string filter) => AsQuery().WhereRaw(filter);

    /// <summary>Orders ascending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<SalesBookedInvoiceLine, SalesBookedInvoiceLineFilter, SalesBookedInvoiceLineSort> OrderBy(System.Linq.Expressions.Expression<System.Func<SalesBookedInvoiceLineSort, EconomicSortField>> selector) => AsQuery().OrderBy(selector);

    /// <summary>Orders descending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<SalesBookedInvoiceLine, SalesBookedInvoiceLineFilter, SalesBookedInvoiceLineSort> OrderByDescending(System.Linq.Expressions.Expression<System.Func<SalesBookedInvoiceLineSort, EconomicSortField>> selector) => AsQuery().OrderByDescending(selector);

    /// <summary>Sets how many items are fetched per request.</summary>
    /// <param name="pageSize">Items per page, up to 1000.</param>
    /// <returns>A query using that page size.</returns>
    public EconomicOpenQuery<SalesBookedInvoiceLine, SalesBookedInvoiceLineFilter, SalesBookedInvoiceLineSort> WithPageSize(int pageSize) => AsQuery().WithPageSize(pageSize);

    /// <summary>Enumerates everything, following the cursor.</summary>
    /// <param name="cancellationToken">Cancels the enumeration.</param>
    /// <returns>The items.</returns>
    public System.Collections.Generic.IAsyncEnumerable<SalesBookedInvoiceLine> AsAsyncEnumerable(CancellationToken cancellationToken = default) => AsQuery().AsAsyncEnumerable(cancellationToken);

    /// <summary>Counts everything in the collection.</summary>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The number of records.</returns>
    public Task<int> CountAsync(CancellationToken cancellationToken = default) => AsQuery().CountAsync(cancellationToken);

    /// <summary>Fetches one numbered page.</summary>
    /// <param name="pageIndex">Zero-based page index.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The page.</returns>
    public Task<IReadOnlyList<SalesBookedInvoiceLine>> GetPageAsync(int pageIndex, CancellationToken cancellationToken = default) => AsQuery().GetPageAsync(pageIndex, cancellationToken);
}

/// <summary>
/// A resource from <c>/invoices/drafts</c>.
/// </summary>
/// <remarks>
/// The same shape is used to read, create and update: these services describe a resource once
/// and accept it back unchanged. Properties the server maintains are simply left unset.
/// </remarks>
public sealed record SalesDraftInvoice
{
    /// <summary>The <c>number</c> field.</summary>
    public int? Number { get; init; }

    /// <summary>The <c>draftInvoiceNumber</c> field.</summary>
    public int? DraftInvoiceNumber { get; init; }

    /// <summary>The <c>customerNumber</c> field.</summary>
    public required int CustomerNumber { get; init; }

    /// <summary>The <c>customerName</c> field.</summary>
    public required string CustomerName { get; init; }

    /// <summary>The <c>date</c> field.</summary>
    public required System.DateTimeOffset Date { get; init; }

    /// <summary>The <c>currencyCode</c> field.</summary>
    public required string CurrencyCode { get; init; }

    /// <summary>The <c>lastUpdated</c> field.</summary>
    public System.DateTimeOffset? LastUpdated { get; init; }

    /// <summary>The <c>layoutNumber</c> field.</summary>
    public required int LayoutNumber { get; init; }

    /// <summary>The <c>termOfPaymentNumber</c> field.</summary>
    public required int TermOfPaymentNumber { get; init; }

    /// <summary>The <c>dueDate</c> field.</summary>
    public System.DateTimeOffset? DueDate { get; init; }

    /// <summary>The <c>vatZoneNumber</c> field.</summary>
    public required int VatZoneNumber { get; init; }

    /// <summary>The <c>isVatIncluded</c> field.</summary>
    public bool? IsVatIncluded { get; init; }

    /// <summary>The <c>amountInBaseCurrency</c> field.</summary>
    public double? AmountInBaseCurrency { get; init; }

    /// <summary>The <c>amount</c> field.</summary>
    public double? Amount { get; init; }

    /// <summary>The <c>vatAmount</c> field.</summary>
    public double? VatAmount { get; init; }

    /// <summary>The <c>roundingAmount</c> field.</summary>
    public double? RoundingAmount { get; init; }

    /// <summary>The <c>projectNumber</c> field.</summary>
    public int? ProjectNumber { get; init; }

    /// <summary>The <c>customerAddress</c> field.</summary>
    public string? CustomerAddress { get; init; }

    /// <summary>The <c>customerPostalCode</c> field.</summary>
    public string? CustomerPostalCode { get; init; }

    /// <summary>The <c>customerCity</c> field.</summary>
    public string? CustomerCity { get; init; }

    /// <summary>The <c>customerCountry</c> field.</summary>
    public string? CustomerCountry { get; init; }

    /// <summary>The <c>otherReference</c> field.</summary>
    public string? OtherReference { get; init; }

    /// <summary>The <c>heading</c> field.</summary>
    public string? Heading { get; init; }

    /// <summary>The <c>textLine1</c> field.</summary>
    public string? TextLine1 { get; init; }

    /// <summary>The <c>textLine2</c> field.</summary>
    public string? TextLine2 { get; init; }

    /// <summary>The <c>ourReferenceNumber</c> field.</summary>
    public int? OurReferenceNumber { get; init; }

    /// <summary>The <c>deliveryLocationNumber</c> field.</summary>
    public int? DeliveryLocationNumber { get; init; }

    /// <summary>The <c>deliveryAddress</c> field.</summary>
    public string? DeliveryAddress { get; init; }

    /// <summary>The <c>deliveryPostalCode</c> field.</summary>
    public string? DeliveryPostalCode { get; init; }

    /// <summary>The <c>deliveryCity</c> field.</summary>
    public string? DeliveryCity { get; init; }

    /// <summary>The <c>deliveryCountry</c> field.</summary>
    public string? DeliveryCountry { get; init; }

    /// <summary>The <c>deliveryTerms</c> field.</summary>
    public string? DeliveryTerms { get; init; }

    /// <summary>The <c>deliveryDate</c> field.</summary>
    public System.DateTimeOffset? DeliveryDate { get; init; }

    /// <summary>The <c>attentionNumber</c> field.</summary>
    public int? AttentionNumber { get; init; }

    /// <summary>The <c>yourReferenceNumber</c> field.</summary>
    public int? YourReferenceNumber { get; init; }

    /// <summary>The <c>ourReference2Number</c> field.</summary>
    public int? OurReference2Number { get; init; }

    /// <summary>The <c>debtorEan</c> field.</summary>
    public string? DebtorEan { get; init; }

    /// <summary>The <c>publicEntryNumber</c> field.</summary>
    public string? PublicEntryNumber { get; init; }

    /// <summary>The <c>totalCostPriceInBaseCurrency</c> field.</summary>
    public double? TotalCostPriceInBaseCurrency { get; init; }

    /// <summary>The <c>exchangeRate</c> field.</summary>
    public double? ExchangeRate { get; init; }

    /// <summary>The <c>cvr</c> field.</summary>
    public string? Cvr { get; init; }

    /// <summary>The <c>pNr</c> field.</summary>
    public string? PNr { get; init; }

    /// <summary>The <c>nemHandelReceiverType</c> field.</summary>
    public int? NemHandelReceiverType { get; init; }

    /// <summary>The <c>debitorMobilePhone</c> field.</summary>
    public string? DebitorMobilePhone { get; init; }

    /// <summary>The <c>externalId</c> field.</summary>
    public string? ExternalId { get; init; }

    /// <summary>The <c>objectVersion</c> field.</summary>
    public string? ObjectVersion { get; init; }
}

/// <summary>
/// What <c>/invoices/drafts</c> can be filtered on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class SalesDraftInvoiceFilter
{
    /// <summary>Maps to <c>number</c>.</summary>
    [EconomicField("number")]
    public NumericField<int> Number { get; } = null!;

    /// <summary>Maps to <c>draftInvoiceNumber</c>.</summary>
    [EconomicField("draftInvoiceNumber")]
    public NumericField<int> DraftInvoiceNumber { get; } = null!;

    /// <summary>Maps to <c>customerNumber</c>.</summary>
    [EconomicField("customerNumber")]
    public NumericField<int> CustomerNumber { get; } = null!;
}

/// <summary>
/// What <c>/invoices/drafts</c> can be sorted on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class SalesDraftInvoiceSort
{
    /// <summary>Maps to <c>number</c>.</summary>
    [EconomicField("number")]
    public EconomicSortField Number { get; } = null!;

    /// <summary>Maps to <c>draftInvoiceNumber</c>.</summary>
    [EconomicField("draftInvoiceNumber")]
    public EconomicSortField DraftInvoiceNumber { get; } = null!;

    /// <summary>Maps to <c>customerNumber</c>.</summary>
    [EconomicField("customerNumber")]
    public EconomicSortField CustomerNumber { get; } = null!;
}

/// <summary>Fetches <c>/invoices/drafts</c> and maps it to <see cref="SalesDraftInvoice"/>.</summary>
internal sealed class SalesDraftInvoiceSource(Raw.DraftInvoicesClient client)
    : IEconomicOpenSource<SalesDraftInvoice>
{
    public bool CanCursor => true;

    public bool CanPage => true;

    public async Task<EconomicCursorPage<SalesDraftInvoice>> GetCursorPageAsync(
        string? cursor, string? filter, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetDraftInvoicesAsync(cursor: cursor, filter: filter, cancellationToken: cancellationToken),
            "GET /invoices/drafts").ConfigureAwait(false);

        var items = new List<SalesDraftInvoice>(response.Items?.Count ?? 0);
        foreach (var item in response.Items ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicCursorPage<SalesDraftInvoice>(items, response.Cursor);
    }

    public async Task<IReadOnlyList<SalesDraftInvoice>> GetPageAsync(
        string? filter, string? sort, int pageSize, int skipPages, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetDraftInvoicesPagedAsync(filter: filter, sort: sort, pageSize: pageSize, skipPages: skipPages, cancellationToken: cancellationToken),
            "GET /invoices/drafts/paged").ConfigureAwait(false);

        var items = new List<SalesDraftInvoice>(response?.Count ?? 0);
        foreach (var item in response ?? Array.Empty<Raw.DraftInvoice>())
        {
            items.Add(Map(item));
        }

        return items;
    }

    public Task<int> CountAsync(string? filter, CancellationToken cancellationToken) =>
        OpenTransport.SendAsync(
            () => client.GetNumberOfDraftInvoicesAsync(filter: filter, cancellationToken: cancellationToken),
            "GET /invoices/drafts/count");

    internal static SalesDraftInvoice Map(Raw.DraftInvoice source) => new()
    {
        Number = source.Number,
        DraftInvoiceNumber = source.DraftInvoiceNumber,
        CustomerNumber = source.CustomerNumber,
        CustomerName = source.CustomerName,
        Date = source.Date,
        CurrencyCode = source.CurrencyCode,
        LastUpdated = source.LastUpdated,
        LayoutNumber = source.LayoutNumber,
        TermOfPaymentNumber = source.TermOfPaymentNumber,
        DueDate = source.DueDate,
        VatZoneNumber = source.VatZoneNumber,
        IsVatIncluded = source.IsVatIncluded,
        AmountInBaseCurrency = source.AmountInBaseCurrency,
        Amount = source.Amount,
        VatAmount = source.VatAmount,
        RoundingAmount = source.RoundingAmount,
        ProjectNumber = source.ProjectNumber,
        CustomerAddress = source.CustomerAddress,
        CustomerPostalCode = source.CustomerPostalCode,
        CustomerCity = source.CustomerCity,
        CustomerCountry = source.CustomerCountry,
        OtherReference = source.OtherReference,
        Heading = source.Heading,
        TextLine1 = source.TextLine1,
        TextLine2 = source.TextLine2,
        OurReferenceNumber = source.OurReferenceNumber,
        DeliveryLocationNumber = source.DeliveryLocationNumber,
        DeliveryAddress = source.DeliveryAddress,
        DeliveryPostalCode = source.DeliveryPostalCode,
        DeliveryCity = source.DeliveryCity,
        DeliveryCountry = source.DeliveryCountry,
        DeliveryTerms = source.DeliveryTerms,
        DeliveryDate = source.DeliveryDate,
        AttentionNumber = source.AttentionNumber,
        YourReferenceNumber = source.YourReferenceNumber,
        OurReference2Number = source.OurReference2Number,
        DebtorEan = source.DebtorEan,
        PublicEntryNumber = source.PublicEntryNumber,
        TotalCostPriceInBaseCurrency = source.TotalCostPriceInBaseCurrency,
        ExchangeRate = source.ExchangeRate,
        Cvr = source.Cvr,
        PNr = source.PNr,
        NemHandelReceiverType = source.NemHandelReceiverType,
        DebitorMobilePhone = source.DebitorMobilePhone,
        ExternalId = source.ExternalId,
        ObjectVersion = source.ObjectVersion,
    };

    internal static Raw.DraftInvoice ToGenerated(SalesDraftInvoice source) => new()
    {
        Number = source.Number,
        DraftInvoiceNumber = source.DraftInvoiceNumber,
        CustomerNumber = source.CustomerNumber,
        CustomerName = source.CustomerName,
        Date = source.Date,
        CurrencyCode = source.CurrencyCode,
        LastUpdated = source.LastUpdated,
        LayoutNumber = source.LayoutNumber,
        TermOfPaymentNumber = source.TermOfPaymentNumber,
        DueDate = source.DueDate,
        VatZoneNumber = source.VatZoneNumber,
        IsVatIncluded = source.IsVatIncluded,
        AmountInBaseCurrency = source.AmountInBaseCurrency,
        Amount = source.Amount,
        VatAmount = source.VatAmount,
        RoundingAmount = source.RoundingAmount,
        ProjectNumber = source.ProjectNumber,
        CustomerAddress = source.CustomerAddress,
        CustomerPostalCode = source.CustomerPostalCode,
        CustomerCity = source.CustomerCity,
        CustomerCountry = source.CustomerCountry,
        OtherReference = source.OtherReference,
        Heading = source.Heading,
        TextLine1 = source.TextLine1,
        TextLine2 = source.TextLine2,
        OurReferenceNumber = source.OurReferenceNumber,
        DeliveryLocationNumber = source.DeliveryLocationNumber,
        DeliveryAddress = source.DeliveryAddress,
        DeliveryPostalCode = source.DeliveryPostalCode,
        DeliveryCity = source.DeliveryCity,
        DeliveryCountry = source.DeliveryCountry,
        DeliveryTerms = source.DeliveryTerms,
        DeliveryDate = source.DeliveryDate,
        AttentionNumber = source.AttentionNumber,
        YourReferenceNumber = source.YourReferenceNumber,
        OurReference2Number = source.OurReference2Number,
        DebtorEan = source.DebtorEan,
        PublicEntryNumber = source.PublicEntryNumber,
        TotalCostPriceInBaseCurrency = source.TotalCostPriceInBaseCurrency,
        ExchangeRate = source.ExchangeRate,
        Cvr = source.Cvr,
        PNr = source.PNr,
        NemHandelReceiverType = source.NemHandelReceiverType,
        DebitorMobilePhone = source.DebitorMobilePhone,
        ExternalId = source.ExternalId,
        ObjectVersion = source.ObjectVersion,
    };
}

/// <summary>
/// <c>/invoices/drafts</c>, as a query and the writes the service supports.
/// </summary>
public sealed class SalesDraftInvoiceResource
{
    private readonly Raw.DraftInvoicesClient _client;

    internal SalesDraftInvoiceResource(System.Net.Http.HttpClient httpClient, System.Uri baseAddress)
    {
        _client = new Raw.DraftInvoicesClient(httpClient) { BaseUrl = baseAddress.ToString() };
    }

    /// <summary>This collection as a composable query.</summary>
    /// <returns>A query with no filter or ordering.</returns>
    public EconomicOpenQuery<SalesDraftInvoice, SalesDraftInvoiceFilter, SalesDraftInvoiceSort> AsQuery() => new(new SalesDraftInvoiceSource(_client));

    /// <summary>Restricts what is returned.</summary>
    /// <param name="predicate">A filter over the filterable properties.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<SalesDraftInvoice, SalesDraftInvoiceFilter, SalesDraftInvoiceSort> Where(System.Linq.Expressions.Expression<System.Func<SalesDraftInvoiceFilter, bool>> predicate) => AsQuery().Where(predicate);

    /// <summary>Restricts what is returned, using e-conomic's filter syntax directly.</summary>
    /// <param name="filter">A filter expression.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<SalesDraftInvoice, SalesDraftInvoiceFilter, SalesDraftInvoiceSort> WhereRaw(string filter) => AsQuery().WhereRaw(filter);

    /// <summary>Orders ascending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<SalesDraftInvoice, SalesDraftInvoiceFilter, SalesDraftInvoiceSort> OrderBy(System.Linq.Expressions.Expression<System.Func<SalesDraftInvoiceSort, EconomicSortField>> selector) => AsQuery().OrderBy(selector);

    /// <summary>Orders descending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<SalesDraftInvoice, SalesDraftInvoiceFilter, SalesDraftInvoiceSort> OrderByDescending(System.Linq.Expressions.Expression<System.Func<SalesDraftInvoiceSort, EconomicSortField>> selector) => AsQuery().OrderByDescending(selector);

    /// <summary>Sets how many items are fetched per request.</summary>
    /// <param name="pageSize">Items per page, up to 1000.</param>
    /// <returns>A query using that page size.</returns>
    public EconomicOpenQuery<SalesDraftInvoice, SalesDraftInvoiceFilter, SalesDraftInvoiceSort> WithPageSize(int pageSize) => AsQuery().WithPageSize(pageSize);

    /// <summary>Enumerates everything, following the cursor.</summary>
    /// <param name="cancellationToken">Cancels the enumeration.</param>
    /// <returns>The items.</returns>
    public System.Collections.Generic.IAsyncEnumerable<SalesDraftInvoice> AsAsyncEnumerable(CancellationToken cancellationToken = default) => AsQuery().AsAsyncEnumerable(cancellationToken);

    /// <summary>Counts everything in the collection.</summary>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The number of records.</returns>
    public Task<int> CountAsync(CancellationToken cancellationToken = default) => AsQuery().CountAsync(cancellationToken);

    /// <summary>Fetches one numbered page.</summary>
    /// <param name="pageIndex">Zero-based page index.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The page.</returns>
    public Task<IReadOnlyList<SalesDraftInvoice>> GetPageAsync(int pageIndex, CancellationToken cancellationToken = default) => AsQuery().GetPageAsync(pageIndex, cancellationToken);

    /// <summary>Fetches one record.</summary>
    /// <param name="number">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The record.</returns>
    public async Task<SalesDraftInvoice> GetAsync(int number, CancellationToken cancellationToken = default)
    {
        var response = await OpenTransport.SendAsync(
            () => _client.GetDraftInvoiceByDocumentIdAsync(number: number, cancellationToken: cancellationToken),
            "GET /invoices/drafts/{number}").ConfigureAwait(false);

        return SalesDraftInvoiceSource.Map(response);
    }

    /// <summary>Creates a record.</summary>
    /// <param name="item">The record to create, whose identifier you supply.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The identifier e-conomic stored it under.</returns>
    /// <remarks>
    /// The response carries the identifier and nothing else, so that is what this returns —
    /// unlike the legacy REST API, whose creates answer with the whole resource. Read it back
    /// with <c>GetAsync</c> if you need the stored record, which also gives you the
    /// <c>objectVersion</c> an update requires.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    public async Task<int?> CreateAsync(SalesDraftInvoice item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        var response = await OpenTransport.SendAsync(
            () => _client.CreateDraftInvoiceAsync(body: SalesDraftInvoiceSource.ToGenerated(item), cancellationToken: cancellationToken),
            "POST /invoices/drafts").ConfigureAwait(false);

        return response.Number;
    }

    /// <summary>Replaces a record.</summary>
    /// <param name="number">The record to replace.</param>
    /// <param name="item">The replacement state, carrying the <c>objectVersion</c> that was read.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is replaced.</returns>
    /// <remarks>
    /// Updates are read-modify-write on this surface. The <c>objectVersion</c> from the record
    /// you read has to come back with it; a stale one, or none, is rejected with
    /// <see cref="Exceptions.EconomicConcurrencyException"/> and nothing is written.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    /// <exception cref="Exceptions.EconomicConcurrencyException">The record changed since it was read.</exception>
    public Task UpdateAsync(int number, SalesDraftInvoice item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        return OpenTransport.SendAsync(
            () => _client.UpdateDraftInvoiceAsync(number: number, body: SalesDraftInvoiceSource.ToGenerated(item), cancellationToken: cancellationToken),
            "PUT /invoices/drafts");
    }

    /// <summary>Deletes a record.</summary>
    /// <param name="number">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is gone.</returns>
    public Task DeleteAsync(int number, CancellationToken cancellationToken = default) =>
        OpenTransport.SendAsync(
            () => _client.DeleteDraftInvoiceByDocumentIdAsync(number: number, cancellationToken: cancellationToken),
            "DELETE /invoices/drafts/{number}");
}

/// <summary>
/// A resource from <c>/invoices/drafts/lines</c>.
/// </summary>
/// <remarks>
/// The same shape is used to read, create and update: these services describe a resource once
/// and accept it back unchanged. Properties the server maintains are simply left unset.
/// </remarks>
public sealed record SalesDraftInvoiceLine
{
    /// <summary>The <c>documentId</c> field.</summary>
    public int? DocumentId { get; init; }

    /// <summary>The <c>draftInvoiceNumber</c> field.</summary>
    public int? DraftInvoiceNumber { get; init; }

    /// <summary>The <c>number</c> field.</summary>
    public int? Number { get; init; }

    /// <summary>The <c>userInterfaceNumber</c> field.</summary>
    public int? UserInterfaceNumber { get; init; }

    /// <summary>The <c>productNumber</c> field.</summary>
    public string? ProductNumber { get; init; }

    /// <summary>The <c>description</c> field.</summary>
    public string? Description { get; init; }

    /// <summary>The <c>quantity</c> field.</summary>
    public double? Quantity { get; init; }

    /// <summary>The <c>unitNumber</c> field.</summary>
    public int? UnitNumber { get; init; }

    /// <summary>The <c>unitNetPrice</c> field.</summary>
    public double? UnitNetPrice { get; init; }

    /// <summary>The <c>unitCostPrice</c> field.</summary>
    public double? UnitCostPrice { get; init; }

    /// <summary>The <c>discountPercentage</c> field.</summary>
    public double? DiscountPercentage { get; init; }

    /// <summary>The <c>recommendedPrice</c> field.</summary>
    public double? RecommendedPrice { get; init; }

    /// <summary>The <c>departmentNumber</c> field.</summary>
    public int? DepartmentNumber { get; init; }

    /// <summary>The <c>quantity2</c> field.</summary>
    public double? Quantity2 { get; init; }

    /// <summary>The <c>unit2Number</c> field.</summary>
    public int? Unit2Number { get; init; }

    /// <summary>The <c>accrue</c> field.</summary>
    public bool? Accrue { get; init; }

    /// <summary>The <c>accrueStartDate</c> field.</summary>
    public System.DateTimeOffset? AccrueStartDate { get; init; }

    /// <summary>The <c>accrueEndDate</c> field.</summary>
    public System.DateTimeOffset? AccrueEndDate { get; init; }

    /// <summary>The <c>marginInBaseCurrency</c> field.</summary>
    public double? MarginInBaseCurrency { get; init; }

    /// <summary>The <c>marginPercentage</c> field.</summary>
    public double? MarginPercentage { get; init; }

    /// <summary>The <c>totalNetAmount</c> field.</summary>
    public double? TotalNetAmount { get; init; }

    /// <summary>The <c>objectVersion</c> field.</summary>
    public string? ObjectVersion { get; init; }
}

/// <summary>
/// What <c>/invoices/drafts/lines</c> can be filtered on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class SalesDraftInvoiceLineFilter
{
    /// <summary>Maps to <c>documentId</c>.</summary>
    [EconomicField("documentId")]
    public NumericField<int> DocumentId { get; } = null!;

    /// <summary>Maps to <c>draftInvoiceNumber</c>.</summary>
    [EconomicField("draftInvoiceNumber")]
    public NumericField<int> DraftInvoiceNumber { get; } = null!;

    /// <summary>Maps to <c>number</c>.</summary>
    [EconomicField("number")]
    public NumericField<int> Number { get; } = null!;

    /// <summary>Maps to <c>userInterfaceNumber</c>.</summary>
    [EconomicField("userInterfaceNumber")]
    public NumericField<int> UserInterfaceNumber { get; } = null!;

    /// <summary>Maps to <c>productNumber</c>.</summary>
    [EconomicField("productNumber")]
    public EqualityField<string> ProductNumber { get; } = null!;

    /// <summary>Maps to <c>discountPercentage</c>.</summary>
    [EconomicField("discountPercentage")]
    public NumericField<double> DiscountPercentage { get; } = null!;

    /// <summary>Maps to <c>departmentNumber</c>.</summary>
    [EconomicField("departmentNumber")]
    public NumericField<int> DepartmentNumber { get; } = null!;
}

/// <summary>
/// What <c>/invoices/drafts/lines</c> can be sorted on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class SalesDraftInvoiceLineSort
{
    /// <summary>Maps to <c>documentId</c>.</summary>
    [EconomicField("documentId")]
    public EconomicSortField DocumentId { get; } = null!;

    /// <summary>Maps to <c>number</c>.</summary>
    [EconomicField("number")]
    public EconomicSortField Number { get; } = null!;

    /// <summary>Maps to <c>userInterfaceNumber</c>.</summary>
    [EconomicField("userInterfaceNumber")]
    public EconomicSortField UserInterfaceNumber { get; } = null!;
}

/// <summary>Fetches <c>/invoices/drafts/lines</c> and maps it to <see cref="SalesDraftInvoiceLine"/>.</summary>
internal sealed class SalesDraftInvoiceLineSource(Raw.DraftInvoiceLinesClient client)
    : IEconomicOpenSource<SalesDraftInvoiceLine>
{
    public bool CanCursor => true;

    public bool CanPage => true;

    public async Task<EconomicCursorPage<SalesDraftInvoiceLine>> GetCursorPageAsync(
        string? cursor, string? filter, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetAllDraftInvoiceLinesAsync(cursor: cursor, filter: filter, cancellationToken: cancellationToken),
            "GET /invoices/drafts/lines").ConfigureAwait(false);

        var items = new List<SalesDraftInvoiceLine>(response.Items?.Count ?? 0);
        foreach (var item in response.Items ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicCursorPage<SalesDraftInvoiceLine>(items, response.Cursor);
    }

    public async Task<IReadOnlyList<SalesDraftInvoiceLine>> GetPageAsync(
        string? filter, string? sort, int pageSize, int skipPages, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetPageOfDraftInvoiceLinesAsync(filter: filter, sort: sort, pageSize: pageSize, skipPages: skipPages, cancellationToken: cancellationToken),
            "GET /invoices/drafts/lines/paged").ConfigureAwait(false);

        var items = new List<SalesDraftInvoiceLine>(response?.Count ?? 0);
        foreach (var item in response ?? Array.Empty<Raw.DraftInvoiceLine>())
        {
            items.Add(Map(item));
        }

        return items;
    }

    public Task<int> CountAsync(string? filter, CancellationToken cancellationToken) =>
        OpenTransport.SendAsync(
            () => client.GetNumberOfDraftInvoiceLinesAsync(filter: filter, cancellationToken: cancellationToken),
            "GET /invoices/drafts/lines/count");

    internal static SalesDraftInvoiceLine Map(Raw.DraftInvoiceLine source) => new()
    {
        DocumentId = source.DocumentId,
        DraftInvoiceNumber = source.DraftInvoiceNumber,
        Number = source.Number,
        UserInterfaceNumber = source.UserInterfaceNumber,
        ProductNumber = source.ProductNumber,
        Description = source.Description,
        Quantity = source.Quantity,
        UnitNumber = source.UnitNumber,
        UnitNetPrice = source.UnitNetPrice,
        UnitCostPrice = source.UnitCostPrice,
        DiscountPercentage = source.DiscountPercentage,
        RecommendedPrice = source.RecommendedPrice,
        DepartmentNumber = source.DepartmentNumber,
        Quantity2 = source.Quantity2,
        Unit2Number = source.Unit2Number,
        Accrue = source.Accrue,
        AccrueStartDate = source.AccrueStartDate,
        AccrueEndDate = source.AccrueEndDate,
        MarginInBaseCurrency = source.MarginInBaseCurrency,
        MarginPercentage = source.MarginPercentage,
        TotalNetAmount = source.TotalNetAmount,
        ObjectVersion = source.ObjectVersion,
    };

    internal static Raw.DraftInvoiceLine ToGenerated(SalesDraftInvoiceLine source) => new()
    {
        DocumentId = source.DocumentId,
        DraftInvoiceNumber = source.DraftInvoiceNumber,
        Number = source.Number,
        UserInterfaceNumber = source.UserInterfaceNumber,
        ProductNumber = source.ProductNumber,
        Description = source.Description,
        Quantity = source.Quantity,
        UnitNumber = source.UnitNumber,
        UnitNetPrice = source.UnitNetPrice,
        UnitCostPrice = source.UnitCostPrice,
        DiscountPercentage = source.DiscountPercentage,
        RecommendedPrice = source.RecommendedPrice,
        DepartmentNumber = source.DepartmentNumber,
        Quantity2 = source.Quantity2,
        Unit2Number = source.Unit2Number,
        Accrue = source.Accrue,
        AccrueStartDate = source.AccrueStartDate,
        AccrueEndDate = source.AccrueEndDate,
        MarginInBaseCurrency = source.MarginInBaseCurrency,
        MarginPercentage = source.MarginPercentage,
        TotalNetAmount = source.TotalNetAmount,
        ObjectVersion = source.ObjectVersion,
    };
}

/// <summary>
/// <c>/invoices/drafts/lines</c>, as a query and the writes the service supports.
/// </summary>
public sealed class SalesDraftInvoiceLineResource
{
    private readonly Raw.DraftInvoiceLinesClient _client;

    internal SalesDraftInvoiceLineResource(System.Net.Http.HttpClient httpClient, System.Uri baseAddress)
    {
        _client = new Raw.DraftInvoiceLinesClient(httpClient) { BaseUrl = baseAddress.ToString() };
    }

    /// <summary>This collection as a composable query.</summary>
    /// <returns>A query with no filter or ordering.</returns>
    public EconomicOpenQuery<SalesDraftInvoiceLine, SalesDraftInvoiceLineFilter, SalesDraftInvoiceLineSort> AsQuery() => new(new SalesDraftInvoiceLineSource(_client));

    /// <summary>Restricts what is returned.</summary>
    /// <param name="predicate">A filter over the filterable properties.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<SalesDraftInvoiceLine, SalesDraftInvoiceLineFilter, SalesDraftInvoiceLineSort> Where(System.Linq.Expressions.Expression<System.Func<SalesDraftInvoiceLineFilter, bool>> predicate) => AsQuery().Where(predicate);

    /// <summary>Restricts what is returned, using e-conomic's filter syntax directly.</summary>
    /// <param name="filter">A filter expression.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<SalesDraftInvoiceLine, SalesDraftInvoiceLineFilter, SalesDraftInvoiceLineSort> WhereRaw(string filter) => AsQuery().WhereRaw(filter);

    /// <summary>Orders ascending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<SalesDraftInvoiceLine, SalesDraftInvoiceLineFilter, SalesDraftInvoiceLineSort> OrderBy(System.Linq.Expressions.Expression<System.Func<SalesDraftInvoiceLineSort, EconomicSortField>> selector) => AsQuery().OrderBy(selector);

    /// <summary>Orders descending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<SalesDraftInvoiceLine, SalesDraftInvoiceLineFilter, SalesDraftInvoiceLineSort> OrderByDescending(System.Linq.Expressions.Expression<System.Func<SalesDraftInvoiceLineSort, EconomicSortField>> selector) => AsQuery().OrderByDescending(selector);

    /// <summary>Sets how many items are fetched per request.</summary>
    /// <param name="pageSize">Items per page, up to 1000.</param>
    /// <returns>A query using that page size.</returns>
    public EconomicOpenQuery<SalesDraftInvoiceLine, SalesDraftInvoiceLineFilter, SalesDraftInvoiceLineSort> WithPageSize(int pageSize) => AsQuery().WithPageSize(pageSize);

    /// <summary>Enumerates everything, following the cursor.</summary>
    /// <param name="cancellationToken">Cancels the enumeration.</param>
    /// <returns>The items.</returns>
    public System.Collections.Generic.IAsyncEnumerable<SalesDraftInvoiceLine> AsAsyncEnumerable(CancellationToken cancellationToken = default) => AsQuery().AsAsyncEnumerable(cancellationToken);

    /// <summary>Counts everything in the collection.</summary>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The number of records.</returns>
    public Task<int> CountAsync(CancellationToken cancellationToken = default) => AsQuery().CountAsync(cancellationToken);

    /// <summary>Fetches one numbered page.</summary>
    /// <param name="pageIndex">Zero-based page index.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The page.</returns>
    public Task<IReadOnlyList<SalesDraftInvoiceLine>> GetPageAsync(int pageIndex, CancellationToken cancellationToken = default) => AsQuery().GetPageAsync(pageIndex, cancellationToken);
}

/// <summary>
/// A resource from <c>/orders/{documentStatus}/lines</c>.
/// </summary>
/// <remarks>
/// The same shape is used to read, create and update: these services describe a resource once
/// and accept it back unchanged. Properties the server maintains are simply left unset.
/// </remarks>
public sealed record SalesOrderLine
{
    /// <summary>The <c>documentId</c> field.</summary>
    public int? DocumentId { get; init; }

    /// <summary>The <c>orderNumber</c> field.</summary>
    public int? OrderNumber { get; init; }

    /// <summary>The <c>number</c> field.</summary>
    public int? Number { get; init; }

    /// <summary>The <c>userInterfaceNumber</c> field.</summary>
    public int? UserInterfaceNumber { get; init; }

    /// <summary>The <c>productNumber</c> field.</summary>
    public string? ProductNumber { get; init; }

    /// <summary>The <c>description</c> field.</summary>
    public string? Description { get; init; }

    /// <summary>The <c>quantity</c> field.</summary>
    public double? Quantity { get; init; }

    /// <summary>The <c>unitNumber</c> field.</summary>
    public int? UnitNumber { get; init; }

    /// <summary>The <c>unitNetPrice</c> field.</summary>
    public double? UnitNetPrice { get; init; }

    /// <summary>The <c>unitCostPrice</c> field.</summary>
    public double? UnitCostPrice { get; init; }

    /// <summary>The <c>discountPercentage</c> field.</summary>
    public double? DiscountPercentage { get; init; }

    /// <summary>The <c>recommendedPrice</c> field.</summary>
    public double? RecommendedPrice { get; init; }

    /// <summary>The <c>departmentNumber</c> field.</summary>
    public int? DepartmentNumber { get; init; }

    /// <summary>The <c>quantity2</c> field.</summary>
    public double? Quantity2 { get; init; }

    /// <summary>The <c>unit2Number</c> field.</summary>
    public int? Unit2Number { get; init; }

    /// <summary>The <c>marginInBaseCurrency</c> field.</summary>
    public double? MarginInBaseCurrency { get; init; }

    /// <summary>The <c>marginPercentage</c> field.</summary>
    public double? MarginPercentage { get; init; }

    /// <summary>The <c>totalNetAmount</c> field.</summary>
    public double? TotalNetAmount { get; init; }
}

/// <summary>
/// What <c>/orders/{documentStatus}/lines</c> can be filtered on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class SalesOrderLineFilter
{
    /// <summary>Maps to <c>documentId</c>.</summary>
    [EconomicField("documentId")]
    public NumericField<int> DocumentId { get; } = null!;

    /// <summary>Maps to <c>orderNumber</c>.</summary>
    [EconomicField("orderNumber")]
    public NumericField<int> OrderNumber { get; } = null!;

    /// <summary>Maps to <c>number</c>.</summary>
    [EconomicField("number")]
    public NumericField<int> Number { get; } = null!;

    /// <summary>Maps to <c>userInterfaceNumber</c>.</summary>
    [EconomicField("userInterfaceNumber")]
    public NumericField<int> UserInterfaceNumber { get; } = null!;

    /// <summary>Maps to <c>productNumber</c>.</summary>
    [EconomicField("productNumber")]
    public EqualityField<string> ProductNumber { get; } = null!;

    /// <summary>Maps to <c>discountPercentage</c>.</summary>
    [EconomicField("discountPercentage")]
    public NumericField<double> DiscountPercentage { get; } = null!;

    /// <summary>Maps to <c>departmentNumber</c>.</summary>
    [EconomicField("departmentNumber")]
    public NumericField<int> DepartmentNumber { get; } = null!;
}

/// <summary>
/// What <c>/orders/{documentStatus}/lines</c> can be sorted on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class SalesOrderLineSort
{
    /// <summary>Maps to <c>documentId</c>.</summary>
    [EconomicField("documentId")]
    public EconomicSortField DocumentId { get; } = null!;

    /// <summary>Maps to <c>number</c>.</summary>
    [EconomicField("number")]
    public EconomicSortField Number { get; } = null!;

    /// <summary>Maps to <c>userInterfaceNumber</c>.</summary>
    [EconomicField("userInterfaceNumber")]
    public EconomicSortField UserInterfaceNumber { get; } = null!;
}

/// <summary>Fetches <c>/orders/{documentStatus}/lines</c> and maps it to <see cref="SalesOrderLine"/>.</summary>
internal sealed class SalesOrderLineSource(Raw.OrderLinesClient client, string documentStatus)
    : IEconomicOpenSource<SalesOrderLine>
{
    public bool CanCursor => true;

    public bool CanPage => true;

    public async Task<EconomicCursorPage<SalesOrderLine>> GetCursorPageAsync(
        string? cursor, string? filter, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetAllOrderLinesAsync(documentStatus: documentStatus, cursor: cursor, filter: filter, cancellationToken: cancellationToken),
            "GET /orders/{documentStatus}/lines").ConfigureAwait(false);

        var items = new List<SalesOrderLine>(response.Items?.Count ?? 0);
        foreach (var item in response.Items ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicCursorPage<SalesOrderLine>(items, response.Cursor);
    }

    public async Task<IReadOnlyList<SalesOrderLine>> GetPageAsync(
        string? filter, string? sort, int pageSize, int skipPages, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetOrderLinesPageAsync(documentStatus: documentStatus, filter: filter, sort: sort, pageSize: pageSize, skipPages: skipPages, cancellationToken: cancellationToken),
            "GET /orders/{documentStatus}/lines/paged").ConfigureAwait(false);

        var items = new List<SalesOrderLine>(response?.Count ?? 0);
        foreach (var item in response ?? Array.Empty<Raw.OrderLine>())
        {
            items.Add(Map(item));
        }

        return items;
    }

    public Task<int> CountAsync(string? filter, CancellationToken cancellationToken) =>
        OpenTransport.SendAsync(
            () => client.GetNumberOfOrderLinesAsync(documentStatus: documentStatus, filter: filter, cancellationToken: cancellationToken),
            "GET /orders/{documentStatus}/lines/count");

    internal static SalesOrderLine Map(Raw.OrderLine source) => new()
    {
        DocumentId = source.DocumentId,
        OrderNumber = source.OrderNumber,
        Number = source.Number,
        UserInterfaceNumber = source.UserInterfaceNumber,
        ProductNumber = source.ProductNumber,
        Description = source.Description,
        Quantity = source.Quantity,
        UnitNumber = source.UnitNumber,
        UnitNetPrice = source.UnitNetPrice,
        UnitCostPrice = source.UnitCostPrice,
        DiscountPercentage = source.DiscountPercentage,
        RecommendedPrice = source.RecommendedPrice,
        DepartmentNumber = source.DepartmentNumber,
        Quantity2 = source.Quantity2,
        Unit2Number = source.Unit2Number,
        MarginInBaseCurrency = source.MarginInBaseCurrency,
        MarginPercentage = source.MarginPercentage,
        TotalNetAmount = source.TotalNetAmount,
    };

    internal static Raw.OrderLine ToGenerated(SalesOrderLine source) => new()
    {
        DocumentId = source.DocumentId,
        OrderNumber = source.OrderNumber,
        Number = source.Number,
        UserInterfaceNumber = source.UserInterfaceNumber,
        ProductNumber = source.ProductNumber,
        Description = source.Description,
        Quantity = source.Quantity,
        UnitNumber = source.UnitNumber,
        UnitNetPrice = source.UnitNetPrice,
        UnitCostPrice = source.UnitCostPrice,
        DiscountPercentage = source.DiscountPercentage,
        RecommendedPrice = source.RecommendedPrice,
        DepartmentNumber = source.DepartmentNumber,
        Quantity2 = source.Quantity2,
        Unit2Number = source.Unit2Number,
        MarginInBaseCurrency = source.MarginInBaseCurrency,
        MarginPercentage = source.MarginPercentage,
        TotalNetAmount = source.TotalNetAmount,
    };
}

/// <summary>
/// <c>/orders/{documentStatus}/lines</c>, as a query and the writes the service supports.
/// </summary>
public sealed class SalesOrderLineResource
{
    private readonly Raw.OrderLinesClient _client;
    private readonly string _documentStatus;

    internal SalesOrderLineResource(System.Net.Http.HttpClient httpClient, System.Uri baseAddress, string documentStatus)
    {
        _client = new Raw.OrderLinesClient(httpClient) { BaseUrl = baseAddress.ToString() };
        _documentStatus = documentStatus;
    }

    /// <summary>This collection as a composable query.</summary>
    /// <returns>A query with no filter or ordering.</returns>
    public EconomicOpenQuery<SalesOrderLine, SalesOrderLineFilter, SalesOrderLineSort> AsQuery() => new(new SalesOrderLineSource(_client, _documentStatus));

    /// <summary>Restricts what is returned.</summary>
    /// <param name="predicate">A filter over the filterable properties.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<SalesOrderLine, SalesOrderLineFilter, SalesOrderLineSort> Where(System.Linq.Expressions.Expression<System.Func<SalesOrderLineFilter, bool>> predicate) => AsQuery().Where(predicate);

    /// <summary>Restricts what is returned, using e-conomic's filter syntax directly.</summary>
    /// <param name="filter">A filter expression.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<SalesOrderLine, SalesOrderLineFilter, SalesOrderLineSort> WhereRaw(string filter) => AsQuery().WhereRaw(filter);

    /// <summary>Orders ascending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<SalesOrderLine, SalesOrderLineFilter, SalesOrderLineSort> OrderBy(System.Linq.Expressions.Expression<System.Func<SalesOrderLineSort, EconomicSortField>> selector) => AsQuery().OrderBy(selector);

    /// <summary>Orders descending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<SalesOrderLine, SalesOrderLineFilter, SalesOrderLineSort> OrderByDescending(System.Linq.Expressions.Expression<System.Func<SalesOrderLineSort, EconomicSortField>> selector) => AsQuery().OrderByDescending(selector);

    /// <summary>Sets how many items are fetched per request.</summary>
    /// <param name="pageSize">Items per page, up to 1000.</param>
    /// <returns>A query using that page size.</returns>
    public EconomicOpenQuery<SalesOrderLine, SalesOrderLineFilter, SalesOrderLineSort> WithPageSize(int pageSize) => AsQuery().WithPageSize(pageSize);

    /// <summary>Enumerates everything, following the cursor.</summary>
    /// <param name="cancellationToken">Cancels the enumeration.</param>
    /// <returns>The items.</returns>
    public System.Collections.Generic.IAsyncEnumerable<SalesOrderLine> AsAsyncEnumerable(CancellationToken cancellationToken = default) => AsQuery().AsAsyncEnumerable(cancellationToken);

    /// <summary>Counts everything in the collection.</summary>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The number of records.</returns>
    public Task<int> CountAsync(CancellationToken cancellationToken = default) => AsQuery().CountAsync(cancellationToken);

    /// <summary>Fetches one numbered page.</summary>
    /// <param name="pageIndex">Zero-based page index.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The page.</returns>
    public Task<IReadOnlyList<SalesOrderLine>> GetPageAsync(int pageIndex, CancellationToken cancellationToken = default) => AsQuery().GetPageAsync(pageIndex, cancellationToken);
}

/// <summary>
/// A resource from <c>/quotes/{documentStatus}/lines</c>.
/// </summary>
/// <remarks>
/// The same shape is used to read, create and update: these services describe a resource once
/// and accept it back unchanged. Properties the server maintains are simply left unset.
/// </remarks>
public sealed record SalesQuoteLine
{
    /// <summary>The <c>documentId</c> field.</summary>
    public int? DocumentId { get; init; }

    /// <summary>The <c>quoteNumber</c> field.</summary>
    public int? QuoteNumber { get; init; }

    /// <summary>The <c>number</c> field.</summary>
    public int? Number { get; init; }

    /// <summary>The <c>userInterfaceNumber</c> field.</summary>
    public int? UserInterfaceNumber { get; init; }

    /// <summary>The <c>productNumber</c> field.</summary>
    public string? ProductNumber { get; init; }

    /// <summary>The <c>description</c> field.</summary>
    public string? Description { get; init; }

    /// <summary>The <c>quantity</c> field.</summary>
    public double? Quantity { get; init; }

    /// <summary>The <c>unitNumber</c> field.</summary>
    public int? UnitNumber { get; init; }

    /// <summary>The <c>unitNetPrice</c> field.</summary>
    public double? UnitNetPrice { get; init; }

    /// <summary>The <c>unitCostPrice</c> field.</summary>
    public double? UnitCostPrice { get; init; }

    /// <summary>The <c>discountPercentage</c> field.</summary>
    public double? DiscountPercentage { get; init; }

    /// <summary>The <c>recommendedPrice</c> field.</summary>
    public double? RecommendedPrice { get; init; }

    /// <summary>The <c>departmentNumber</c> field.</summary>
    public int? DepartmentNumber { get; init; }

    /// <summary>The <c>quantity2</c> field.</summary>
    public double? Quantity2 { get; init; }

    /// <summary>The <c>unit2Number</c> field.</summary>
    public int? Unit2Number { get; init; }

    /// <summary>The <c>marginInBaseCurrency</c> field.</summary>
    public double? MarginInBaseCurrency { get; init; }

    /// <summary>The <c>marginPercentage</c> field.</summary>
    public double? MarginPercentage { get; init; }

    /// <summary>The <c>totalNetAmount</c> field.</summary>
    public double? TotalNetAmount { get; init; }
}

/// <summary>
/// What <c>/quotes/{documentStatus}/lines</c> can be filtered on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class SalesQuoteLineFilter
{
    /// <summary>Maps to <c>documentId</c>.</summary>
    [EconomicField("documentId")]
    public NumericField<int> DocumentId { get; } = null!;

    /// <summary>Maps to <c>quoteNumber</c>.</summary>
    [EconomicField("quoteNumber")]
    public NumericField<int> QuoteNumber { get; } = null!;

    /// <summary>Maps to <c>number</c>.</summary>
    [EconomicField("number")]
    public NumericField<int> Number { get; } = null!;

    /// <summary>Maps to <c>userInterfaceNumber</c>.</summary>
    [EconomicField("userInterfaceNumber")]
    public NumericField<int> UserInterfaceNumber { get; } = null!;

    /// <summary>Maps to <c>productNumber</c>.</summary>
    [EconomicField("productNumber")]
    public EqualityField<string> ProductNumber { get; } = null!;

    /// <summary>Maps to <c>discountPercentage</c>.</summary>
    [EconomicField("discountPercentage")]
    public NumericField<double> DiscountPercentage { get; } = null!;

    /// <summary>Maps to <c>departmentNumber</c>.</summary>
    [EconomicField("departmentNumber")]
    public NumericField<int> DepartmentNumber { get; } = null!;
}

/// <summary>
/// What <c>/quotes/{documentStatus}/lines</c> can be sorted on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class SalesQuoteLineSort
{
    /// <summary>Maps to <c>documentId</c>.</summary>
    [EconomicField("documentId")]
    public EconomicSortField DocumentId { get; } = null!;

    /// <summary>Maps to <c>number</c>.</summary>
    [EconomicField("number")]
    public EconomicSortField Number { get; } = null!;

    /// <summary>Maps to <c>userInterfaceNumber</c>.</summary>
    [EconomicField("userInterfaceNumber")]
    public EconomicSortField UserInterfaceNumber { get; } = null!;
}

/// <summary>Fetches <c>/quotes/{documentStatus}/lines</c> and maps it to <see cref="SalesQuoteLine"/>.</summary>
internal sealed class SalesQuoteLineSource(Raw.QuoteLinesClient client, string documentStatus)
    : IEconomicOpenSource<SalesQuoteLine>
{
    public bool CanCursor => true;

    public bool CanPage => true;

    public async Task<EconomicCursorPage<SalesQuoteLine>> GetCursorPageAsync(
        string? cursor, string? filter, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetAllQuoteLinesAsync(documentStatus: documentStatus, cursor: cursor, filter: filter, cancellationToken: cancellationToken),
            "GET /quotes/{documentStatus}/lines").ConfigureAwait(false);

        var items = new List<SalesQuoteLine>(response.Items?.Count ?? 0);
        foreach (var item in response.Items ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicCursorPage<SalesQuoteLine>(items, response.Cursor);
    }

    public async Task<IReadOnlyList<SalesQuoteLine>> GetPageAsync(
        string? filter, string? sort, int pageSize, int skipPages, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetQuoteLinesPageAsync(documentStatus: documentStatus, filter: filter, sort: sort, pageSize: pageSize, skipPages: skipPages, cancellationToken: cancellationToken),
            "GET /quotes/{documentStatus}/lines/paged").ConfigureAwait(false);

        var items = new List<SalesQuoteLine>(response?.Count ?? 0);
        foreach (var item in response ?? Array.Empty<Raw.QuoteLine>())
        {
            items.Add(Map(item));
        }

        return items;
    }

    public Task<int> CountAsync(string? filter, CancellationToken cancellationToken) =>
        OpenTransport.SendAsync(
            () => client.GetNumberOfQuoteLinesAsync(documentStatus: documentStatus, filter: filter, cancellationToken: cancellationToken),
            "GET /quotes/{documentStatus}/lines/count");

    internal static SalesQuoteLine Map(Raw.QuoteLine source) => new()
    {
        DocumentId = source.DocumentId,
        QuoteNumber = source.QuoteNumber,
        Number = source.Number,
        UserInterfaceNumber = source.UserInterfaceNumber,
        ProductNumber = source.ProductNumber,
        Description = source.Description,
        Quantity = source.Quantity,
        UnitNumber = source.UnitNumber,
        UnitNetPrice = source.UnitNetPrice,
        UnitCostPrice = source.UnitCostPrice,
        DiscountPercentage = source.DiscountPercentage,
        RecommendedPrice = source.RecommendedPrice,
        DepartmentNumber = source.DepartmentNumber,
        Quantity2 = source.Quantity2,
        Unit2Number = source.Unit2Number,
        MarginInBaseCurrency = source.MarginInBaseCurrency,
        MarginPercentage = source.MarginPercentage,
        TotalNetAmount = source.TotalNetAmount,
    };

    internal static Raw.QuoteLine ToGenerated(SalesQuoteLine source) => new()
    {
        DocumentId = source.DocumentId,
        QuoteNumber = source.QuoteNumber,
        Number = source.Number,
        UserInterfaceNumber = source.UserInterfaceNumber,
        ProductNumber = source.ProductNumber,
        Description = source.Description,
        Quantity = source.Quantity,
        UnitNumber = source.UnitNumber,
        UnitNetPrice = source.UnitNetPrice,
        UnitCostPrice = source.UnitCostPrice,
        DiscountPercentage = source.DiscountPercentage,
        RecommendedPrice = source.RecommendedPrice,
        DepartmentNumber = source.DepartmentNumber,
        Quantity2 = source.Quantity2,
        Unit2Number = source.Unit2Number,
        MarginInBaseCurrency = source.MarginInBaseCurrency,
        MarginPercentage = source.MarginPercentage,
        TotalNetAmount = source.TotalNetAmount,
    };
}

/// <summary>
/// <c>/quotes/{documentStatus}/lines</c>, as a query and the writes the service supports.
/// </summary>
public sealed class SalesQuoteLineResource
{
    private readonly Raw.QuoteLinesClient _client;
    private readonly string _documentStatus;

    internal SalesQuoteLineResource(System.Net.Http.HttpClient httpClient, System.Uri baseAddress, string documentStatus)
    {
        _client = new Raw.QuoteLinesClient(httpClient) { BaseUrl = baseAddress.ToString() };
        _documentStatus = documentStatus;
    }

    /// <summary>This collection as a composable query.</summary>
    /// <returns>A query with no filter or ordering.</returns>
    public EconomicOpenQuery<SalesQuoteLine, SalesQuoteLineFilter, SalesQuoteLineSort> AsQuery() => new(new SalesQuoteLineSource(_client, _documentStatus));

    /// <summary>Restricts what is returned.</summary>
    /// <param name="predicate">A filter over the filterable properties.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<SalesQuoteLine, SalesQuoteLineFilter, SalesQuoteLineSort> Where(System.Linq.Expressions.Expression<System.Func<SalesQuoteLineFilter, bool>> predicate) => AsQuery().Where(predicate);

    /// <summary>Restricts what is returned, using e-conomic's filter syntax directly.</summary>
    /// <param name="filter">A filter expression.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<SalesQuoteLine, SalesQuoteLineFilter, SalesQuoteLineSort> WhereRaw(string filter) => AsQuery().WhereRaw(filter);

    /// <summary>Orders ascending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<SalesQuoteLine, SalesQuoteLineFilter, SalesQuoteLineSort> OrderBy(System.Linq.Expressions.Expression<System.Func<SalesQuoteLineSort, EconomicSortField>> selector) => AsQuery().OrderBy(selector);

    /// <summary>Orders descending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<SalesQuoteLine, SalesQuoteLineFilter, SalesQuoteLineSort> OrderByDescending(System.Linq.Expressions.Expression<System.Func<SalesQuoteLineSort, EconomicSortField>> selector) => AsQuery().OrderByDescending(selector);

    /// <summary>Sets how many items are fetched per request.</summary>
    /// <param name="pageSize">Items per page, up to 1000.</param>
    /// <returns>A query using that page size.</returns>
    public EconomicOpenQuery<SalesQuoteLine, SalesQuoteLineFilter, SalesQuoteLineSort> WithPageSize(int pageSize) => AsQuery().WithPageSize(pageSize);

    /// <summary>Enumerates everything, following the cursor.</summary>
    /// <param name="cancellationToken">Cancels the enumeration.</param>
    /// <returns>The items.</returns>
    public System.Collections.Generic.IAsyncEnumerable<SalesQuoteLine> AsAsyncEnumerable(CancellationToken cancellationToken = default) => AsQuery().AsAsyncEnumerable(cancellationToken);

    /// <summary>Counts everything in the collection.</summary>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The number of records.</returns>
    public Task<int> CountAsync(CancellationToken cancellationToken = default) => AsQuery().CountAsync(cancellationToken);

    /// <summary>Fetches one numbered page.</summary>
    /// <param name="pageIndex">Zero-based page index.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The page.</returns>
    public Task<IReadOnlyList<SalesQuoteLine>> GetPageAsync(int pageIndex, CancellationToken cancellationToken = default) => AsQuery().GetPageAsync(pageIndex, cancellationToken);
}
