// <auto-generated>
//     Generated by tools/EConomic.SpecConverter (open-facade).
//     Regenerate after a spec refresh; do not edit by hand.
// </auto-generated>
#nullable enable

using EConomic.Querying;
using Raw = EConomic.Open.Generated.Suppliers;

namespace EConomic.Open;

/// <summary>
/// A resource from <c>/Contacts</c>.
/// </summary>
/// <remarks>
/// The same shape is used to read, create and update: these services describe a resource once
/// and accept it back unchanged. Properties the server maintains are simply left unset.
/// </remarks>
public sealed record SupplierContact
{
    /// <summary>The <c>number</c> field.</summary>
    public int? Number { get; init; }

    /// <summary>The <c>supplierNumber</c> field.</summary>
    public required int SupplierNumber { get; init; }

    /// <summary>The <c>userInterfaceNumber</c> field.</summary>
    public int? UserInterfaceNumber { get; init; }

    /// <summary>The <c>name</c> field.</summary>
    public required string Name { get; init; }

    /// <summary>The <c>email</c> field.</summary>
    public string? Email { get; init; }

    /// <summary>The <c>phone</c> field.</summary>
    public string? Phone { get; init; }

    /// <summary>The <c>notes</c> field.</summary>
    public string? Notes { get; init; }

    /// <summary>The <c>lastUpdated</c> field.</summary>
    public System.DateTimeOffset? LastUpdated { get; init; }

    /// <summary>The <c>objectVersion</c> field.</summary>
    public string? ObjectVersion { get; init; }

    /// <summary>The <c>isDeleted</c> field.</summary>
    public bool? IsDeleted { get; init; }

    /// <summary>The <c>active</c> field.</summary>
    public bool? Active { get; init; }
}

/// <summary>
/// What <c>/Contacts</c> can be filtered on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class SupplierContactFilter
{
    /// <summary>Maps to <c>number</c>.</summary>
    [EconomicField("number")]
    public NumericField<int> Number { get; } = null!;

    /// <summary>Maps to <c>supplierNumber</c>.</summary>
    [EconomicField("supplierNumber")]
    public NumericField<int> SupplierNumber { get; } = null!;

    /// <summary>Maps to <c>userInterfaceNumber</c>.</summary>
    [EconomicField("userInterfaceNumber")]
    public NumericField<int> UserInterfaceNumber { get; } = null!;

    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public TextField Name { get; } = null!;

    /// <summary>Maps to <c>email</c>.</summary>
    [EconomicField("email")]
    public TextField Email { get; } = null!;

    /// <summary>Maps to <c>lastUpdated</c>.</summary>
    [EconomicField("lastUpdated")]
    public ComparableField<System.DateTimeOffset> LastUpdated { get; } = null!;

    /// <summary>Maps to <c>isDeleted</c>.</summary>
    [EconomicField("isDeleted")]
    public EqualityField<bool> IsDeleted { get; } = null!;

    /// <summary>Maps to <c>active</c>.</summary>
    [EconomicField("active")]
    public EqualityField<bool> Active { get; } = null!;
}

/// <summary>
/// What <c>/Contacts</c> can be sorted on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class SupplierContactSort
{
    /// <summary>Maps to <c>number</c>.</summary>
    [EconomicField("number")]
    public EconomicSortField Number { get; } = null!;

    /// <summary>Maps to <c>supplierNumber</c>.</summary>
    [EconomicField("supplierNumber")]
    public EconomicSortField SupplierNumber { get; } = null!;
}

/// <summary>Fetches <c>/Contacts</c> and maps it to <see cref="SupplierContact"/>.</summary>
internal sealed class SupplierContactSource(Raw.ContactsClient client)
    : IEconomicOpenSource<SupplierContact>
{
    public bool CanCursor => true;

    public bool CanPage => true;

    public async Task<EconomicCursorPage<SupplierContact>> GetCursorPageAsync(
        string? cursor, string? filter, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetAllContactsAsync(cursor: cursor, filter: filter, cancellationToken: cancellationToken),
            "GET /Contacts").ConfigureAwait(false);

        var items = new List<SupplierContact>(response.Items?.Count ?? 0);
        foreach (var item in response.Items ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicCursorPage<SupplierContact>(items, response.Cursor);
    }

    public async Task<IReadOnlyList<SupplierContact>> GetPageAsync(
        string? filter, string? sort, int pageSize, int skipPages, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetPageOfContactsAsync(filter: filter, sort: sort, pageSize: pageSize, skipPages: skipPages, cancellationToken: cancellationToken),
            "GET /Contacts/paged").ConfigureAwait(false);

        var items = new List<SupplierContact>(response?.Count ?? 0);
        foreach (var item in response ?? Array.Empty<Raw.Contact>())
        {
            items.Add(Map(item));
        }

        return items;
    }

    public Task<int> CountAsync(string? filter, CancellationToken cancellationToken) =>
        OpenTransport.SendAsync(
            () => client.GetNumberOfContactsAsync(filter: filter, cancellationToken: cancellationToken),
            "GET /Contacts/count");

    internal static SupplierContact Map(Raw.Contact source) => new()
    {
        Number = source.Number,
        SupplierNumber = source.SupplierNumber,
        UserInterfaceNumber = source.UserInterfaceNumber,
        Name = source.Name,
        Email = source.Email,
        Phone = source.Phone,
        Notes = source.Notes,
        LastUpdated = source.LastUpdated,
        ObjectVersion = source.ObjectVersion,
        IsDeleted = source.IsDeleted,
        Active = source.Active,
    };

    internal static Raw.Contact ToGenerated(SupplierContact source) => new()
    {
        Number = source.Number,
        SupplierNumber = source.SupplierNumber,
        UserInterfaceNumber = source.UserInterfaceNumber,
        Name = source.Name,
        Email = source.Email,
        Phone = source.Phone,
        Notes = source.Notes,
        LastUpdated = source.LastUpdated,
        ObjectVersion = source.ObjectVersion,
        IsDeleted = source.IsDeleted,
        Active = source.Active,
    };
}

/// <summary>
/// <c>/Contacts</c>, as a query and the writes the service supports.
/// </summary>
public sealed class SupplierContactResource
{
    private readonly Raw.ContactsClient _client;

    internal SupplierContactResource(System.Net.Http.HttpClient httpClient, System.Uri baseAddress)
    {
        _client = new Raw.ContactsClient(httpClient) { BaseUrl = baseAddress.ToString() };
    }

    /// <summary>This collection as a composable query.</summary>
    /// <returns>A query with no filter or ordering.</returns>
    public EconomicOpenQuery<SupplierContact, SupplierContactFilter, SupplierContactSort> AsQuery() => new(new SupplierContactSource(_client));

    /// <summary>Restricts what is returned.</summary>
    /// <param name="predicate">A filter over the filterable properties.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<SupplierContact, SupplierContactFilter, SupplierContactSort> Where(System.Linq.Expressions.Expression<System.Func<SupplierContactFilter, bool>> predicate) => AsQuery().Where(predicate);

    /// <summary>Restricts what is returned, using e-conomic's filter syntax directly.</summary>
    /// <param name="filter">A filter expression.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<SupplierContact, SupplierContactFilter, SupplierContactSort> WhereRaw(string filter) => AsQuery().WhereRaw(filter);

    /// <summary>Orders ascending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<SupplierContact, SupplierContactFilter, SupplierContactSort> OrderBy(System.Linq.Expressions.Expression<System.Func<SupplierContactSort, EconomicSortField>> selector) => AsQuery().OrderBy(selector);

    /// <summary>Orders descending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<SupplierContact, SupplierContactFilter, SupplierContactSort> OrderByDescending(System.Linq.Expressions.Expression<System.Func<SupplierContactSort, EconomicSortField>> selector) => AsQuery().OrderByDescending(selector);

    /// <summary>Sets how many items are fetched per request.</summary>
    /// <param name="pageSize">Items per page, up to 1000.</param>
    /// <returns>A query using that page size.</returns>
    public EconomicOpenQuery<SupplierContact, SupplierContactFilter, SupplierContactSort> WithPageSize(int pageSize) => AsQuery().WithPageSize(pageSize);

    /// <summary>Enumerates everything, following the cursor.</summary>
    /// <param name="cancellationToken">Cancels the enumeration.</param>
    /// <returns>The items.</returns>
    public System.Collections.Generic.IAsyncEnumerable<SupplierContact> AsAsyncEnumerable(CancellationToken cancellationToken = default) => AsQuery().AsAsyncEnumerable(cancellationToken);

    /// <summary>Counts everything in the collection.</summary>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The number of records.</returns>
    public Task<int> CountAsync(CancellationToken cancellationToken = default) => AsQuery().CountAsync(cancellationToken);

    /// <summary>Fetches one numbered page.</summary>
    /// <param name="pageIndex">Zero-based page index.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The page.</returns>
    public Task<IReadOnlyList<SupplierContact>> GetPageAsync(int pageIndex, CancellationToken cancellationToken = default) => AsQuery().GetPageAsync(pageIndex, cancellationToken);

    /// <summary>Fetches one record.</summary>
    /// <param name="number">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The record.</returns>
    public async Task<SupplierContact> GetAsync(int number, CancellationToken cancellationToken = default)
    {
        var response = await OpenTransport.SendAsync(
            () => _client.GetContactByIdAsync(number: number, cancellationToken: cancellationToken),
            "GET /Contacts/{number}").ConfigureAwait(false);

        return SupplierContactSource.Map(response);
    }

    /// <summary>Creates a record.</summary>
    /// <param name="item">The record to create, whose identifier you supply.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The identifier e-conomic stored it under.</returns>
    /// <remarks>
    /// The response carries the identifier and nothing else, so that is what this returns —
    /// unlike the legacy REST API, whose creates answer with the whole resource. Read it back
    /// with <c>GetAsync</c> if you need the stored record, which also gives you the
    /// <c>objectVersion</c> an update requires.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    public async Task<int?> CreateAsync(SupplierContact item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        var response = await OpenTransport.SendAsync(
            () => _client.CreateContactAsync(body: SupplierContactSource.ToGenerated(item), cancellationToken: cancellationToken),
            "POST /Contacts").ConfigureAwait(false);

        return response.Number;
    }

    /// <summary>Replaces a record.</summary>
    /// <param name="item">The replacement state, carrying the <c>objectVersion</c> that was read.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is replaced.</returns>
    /// <remarks>
    /// Updates are read-modify-write on this surface. The <c>objectVersion</c> from the record
    /// you read has to come back with it; a stale one, or none, is rejected with
    /// <see cref="Exceptions.EconomicConcurrencyException"/> and nothing is written.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    /// <exception cref="Exceptions.EconomicConcurrencyException">The record changed since it was read.</exception>
    public Task UpdateAsync(SupplierContact item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        return OpenTransport.SendAsync(
            () => _client.UpdateContactByIdAsync(body: SupplierContactSource.ToGenerated(item), cancellationToken: cancellationToken),
            "PUT /Contacts");
    }

    /// <summary>Deletes a record.</summary>
    /// <param name="number">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is gone.</returns>
    public Task DeleteAsync(int number, CancellationToken cancellationToken = default) =>
        OpenTransport.SendAsync(
            () => _client.DeleteContactByIdAsync(number: number, cancellationToken: cancellationToken),
            "DELETE /Contacts/{number}");
}

/// <summary>
/// A resource from <c>/Groups</c>.
/// </summary>
/// <remarks>
/// The same shape is used to read, create and update: these services describe a resource once
/// and accept it back unchanged. Properties the server maintains are simply left unset.
/// </remarks>
public sealed record SupplierGroup
{
    /// <summary>The <c>number</c> field.</summary>
    public required int Number { get; init; }

    /// <summary>The <c>name</c> field.</summary>
    public required string Name { get; init; }

    /// <summary>The <c>accountNumber</c> field.</summary>
    public required int AccountNumber { get; init; }

    /// <summary>The <c>objectVersion</c> field.</summary>
    public string? ObjectVersion { get; init; }
}

/// <summary>
/// What <c>/Groups</c> can be filtered on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class SupplierGroupFilter
{
    /// <summary>Maps to <c>number</c>.</summary>
    [EconomicField("number")]
    public NumericField<int> Number { get; } = null!;

    /// <summary>Maps to <c>name</c>.</summary>
    [EconomicField("name")]
    public TextField Name { get; } = null!;

    /// <summary>Maps to <c>accountNumber</c>.</summary>
    [EconomicField("accountNumber")]
    public NumericField<int> AccountNumber { get; } = null!;
}

/// <summary>
/// What <c>/Groups</c> can be sorted on.
/// </summary>
/// <remarks>
/// Each property is typed to the operators the service publishes for it, narrowed to those the
/// value's type can carry: e-conomic restricts <c>$in:</c> to numbers and <c>$like:</c> to text,
/// whatever an individual property claims. Anything absent here is not filterable at all, which
/// is most of them.
/// </remarks>
public sealed class SupplierGroupSort
{
    /// <summary>Maps to <c>number</c>.</summary>
    [EconomicField("number")]
    public EconomicSortField Number { get; } = null!;

    /// <summary>Maps to <c>accountNumber</c>.</summary>
    [EconomicField("accountNumber")]
    public EconomicSortField AccountNumber { get; } = null!;
}

/// <summary>Fetches <c>/Groups</c> and maps it to <see cref="SupplierGroup"/>.</summary>
internal sealed class SupplierGroupSource(Raw.GroupsClient client)
    : IEconomicOpenSource<SupplierGroup>
{
    public bool CanCursor => true;

    public bool CanPage => true;

    public async Task<EconomicCursorPage<SupplierGroup>> GetCursorPageAsync(
        string? cursor, string? filter, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetAllGroupsAsync(cursor: cursor, filter: filter, cancellationToken: cancellationToken),
            "GET /Groups").ConfigureAwait(false);

        var items = new List<SupplierGroup>(response.Items?.Count ?? 0);
        foreach (var item in response.Items ?? [])
        {
            items.Add(Map(item));
        }

        return new EconomicCursorPage<SupplierGroup>(items, response.Cursor);
    }

    public async Task<IReadOnlyList<SupplierGroup>> GetPageAsync(
        string? filter, string? sort, int pageSize, int skipPages, CancellationToken cancellationToken)
    {
        var response = await OpenTransport.SendAsync(
            () => client.GetPageOfGroupsAsync(filter: filter, sort: sort, pageSize: pageSize, skipPages: skipPages, cancellationToken: cancellationToken),
            "GET /Groups/paged").ConfigureAwait(false);

        var items = new List<SupplierGroup>(response?.Count ?? 0);
        foreach (var item in response ?? Array.Empty<Raw.Group>())
        {
            items.Add(Map(item));
        }

        return items;
    }

    public Task<int> CountAsync(string? filter, CancellationToken cancellationToken) =>
        OpenTransport.SendAsync(
            () => client.GetNumberOfGroupsAsync(filter: filter, cancellationToken: cancellationToken),
            "GET /Groups/count");

    internal static SupplierGroup Map(Raw.Group source) => new()
    {
        Number = source.Number,
        Name = source.Name,
        AccountNumber = source.AccountNumber,
        ObjectVersion = source.ObjectVersion,
    };

    internal static Raw.Group ToGenerated(SupplierGroup source) => new()
    {
        Number = source.Number,
        Name = source.Name,
        AccountNumber = source.AccountNumber,
        ObjectVersion = source.ObjectVersion,
    };
}

/// <summary>
/// <c>/Groups</c>, as a query and the writes the service supports.
/// </summary>
public sealed class SupplierGroupResource
{
    private readonly Raw.GroupsClient _client;

    internal SupplierGroupResource(System.Net.Http.HttpClient httpClient, System.Uri baseAddress)
    {
        _client = new Raw.GroupsClient(httpClient) { BaseUrl = baseAddress.ToString() };
    }

    /// <summary>This collection as a composable query.</summary>
    /// <returns>A query with no filter or ordering.</returns>
    public EconomicOpenQuery<SupplierGroup, SupplierGroupFilter, SupplierGroupSort> AsQuery() => new(new SupplierGroupSource(_client));

    /// <summary>Restricts what is returned.</summary>
    /// <param name="predicate">A filter over the filterable properties.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<SupplierGroup, SupplierGroupFilter, SupplierGroupSort> Where(System.Linq.Expressions.Expression<System.Func<SupplierGroupFilter, bool>> predicate) => AsQuery().Where(predicate);

    /// <summary>Restricts what is returned, using e-conomic's filter syntax directly.</summary>
    /// <param name="filter">A filter expression.</param>
    /// <returns>A query carrying the filter.</returns>
    public EconomicOpenQuery<SupplierGroup, SupplierGroupFilter, SupplierGroupSort> WhereRaw(string filter) => AsQuery().WhereRaw(filter);

    /// <summary>Orders ascending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<SupplierGroup, SupplierGroupFilter, SupplierGroupSort> OrderBy(System.Linq.Expressions.Expression<System.Func<SupplierGroupSort, EconomicSortField>> selector) => AsQuery().OrderBy(selector);

    /// <summary>Orders descending, which moves the query onto the paged endpoint.</summary>
    /// <param name="selector">The property to sort by.</param>
    /// <returns>A query carrying the ordering.</returns>
    public EconomicOpenQuery<SupplierGroup, SupplierGroupFilter, SupplierGroupSort> OrderByDescending(System.Linq.Expressions.Expression<System.Func<SupplierGroupSort, EconomicSortField>> selector) => AsQuery().OrderByDescending(selector);

    /// <summary>Sets how many items are fetched per request.</summary>
    /// <param name="pageSize">Items per page, up to 1000.</param>
    /// <returns>A query using that page size.</returns>
    public EconomicOpenQuery<SupplierGroup, SupplierGroupFilter, SupplierGroupSort> WithPageSize(int pageSize) => AsQuery().WithPageSize(pageSize);

    /// <summary>Enumerates everything, following the cursor.</summary>
    /// <param name="cancellationToken">Cancels the enumeration.</param>
    /// <returns>The items.</returns>
    public System.Collections.Generic.IAsyncEnumerable<SupplierGroup> AsAsyncEnumerable(CancellationToken cancellationToken = default) => AsQuery().AsAsyncEnumerable(cancellationToken);

    /// <summary>Counts everything in the collection.</summary>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The number of records.</returns>
    public Task<int> CountAsync(CancellationToken cancellationToken = default) => AsQuery().CountAsync(cancellationToken);

    /// <summary>Fetches one numbered page.</summary>
    /// <param name="pageIndex">Zero-based page index.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The page.</returns>
    public Task<IReadOnlyList<SupplierGroup>> GetPageAsync(int pageIndex, CancellationToken cancellationToken = default) => AsQuery().GetPageAsync(pageIndex, cancellationToken);

    /// <summary>Fetches one record.</summary>
    /// <param name="number">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The record.</returns>
    public async Task<SupplierGroup> GetAsync(int number, CancellationToken cancellationToken = default)
    {
        var response = await OpenTransport.SendAsync(
            () => _client.GetGroupByIdAsync(number: number, cancellationToken: cancellationToken),
            "GET /Groups/{number}").ConfigureAwait(false);

        return SupplierGroupSource.Map(response);
    }

    /// <summary>Creates a record.</summary>
    /// <param name="item">The record to create, whose identifier you supply.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>The identifier e-conomic stored it under.</returns>
    /// <remarks>
    /// The response carries the identifier and nothing else, so that is what this returns —
    /// unlike the legacy REST API, whose creates answer with the whole resource. Read it back
    /// with <c>GetAsync</c> if you need the stored record, which also gives you the
    /// <c>objectVersion</c> an update requires.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    public async Task<int?> CreateAsync(SupplierGroup item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        var response = await OpenTransport.SendAsync(
            () => _client.CreateGroupAsync(body: SupplierGroupSource.ToGenerated(item), cancellationToken: cancellationToken),
            "POST /Groups").ConfigureAwait(false);

        return response.Number;
    }

    /// <summary>Replaces a record.</summary>
    /// <param name="item">The replacement state, carrying the <c>objectVersion</c> that was read.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is replaced.</returns>
    /// <remarks>
    /// Updates are read-modify-write on this surface. The <c>objectVersion</c> from the record
    /// you read has to come back with it; a stale one, or none, is rejected with
    /// <see cref="Exceptions.EconomicConcurrencyException"/> and nothing is written.
    /// </remarks>
    /// <exception cref="System.ArgumentNullException"><paramref name="item"/> is <see langword="null"/>.</exception>
    /// <exception cref="Exceptions.EconomicConcurrencyException">The record changed since it was read.</exception>
    public Task UpdateAsync(SupplierGroup item, CancellationToken cancellationToken = default)
    {
        System.ArgumentNullException.ThrowIfNull(item);

        return OpenTransport.SendAsync(
            () => _client.UpdateGroupByIdAsync(body: SupplierGroupSource.ToGenerated(item), cancellationToken: cancellationToken),
            "PUT /Groups");
    }

    /// <summary>Deletes a record.</summary>
    /// <param name="number">Its identifier.</param>
    /// <param name="cancellationToken">Cancels the request.</param>
    /// <returns>A task that completes once the record is gone.</returns>
    public Task DeleteAsync(int number, CancellationToken cancellationToken = default) =>
        OpenTransport.SendAsync(
            () => _client.DeleteGroupByIdAsync(number: number, cancellationToken: cancellationToken),
            "DELETE /Groups/{number}");
}
