using System.Text;
using System.Text.RegularExpressions;

namespace EConomic.SpecConverter;

/// <summary>
/// Emits the source-generated <c>JsonSerializerContext</c> for NSwag's generated clients.
/// </summary>
/// <remarks>
/// NSwag emits reflection-based <c>System.Text.Json</c> calls, which do not survive trimming or
/// AOT. Every generated client exposes a <c>static partial void UpdateJsonSerializerSettings</c>
/// hook, so pointing that at a source-generated resolver makes the runtime path metadata-driven
/// instead.
/// <para>
/// The roots are read out of the generated code rather than out of the specs, so the context
/// always matches what was actually generated. Only roots are needed: the System.Text.Json source
/// generator walks nested types transitively.
/// </para>
/// </remarks>
public static partial class JsonContextGenerator
{
    /// <summary>Builds the context source for a generated client file.</summary>
    /// <param name="generatedSource">Contents of the NSwag-generated file.</param>
    /// <param name="namespaceName">Namespace the generated code lives in.</param>
    /// <param name="contextName">Name to give the generated context class.</param>
    /// <param name="stringEnums">
    /// Whether the API sends enums as names rather than numbers. True for the legacy REST API, which
    /// sends <c>"heading"</c> and <c>"debit"</c>; false for the OpenAPI services, where every
    /// enumerated schema is declared <c>type: integer</c> and the server sends <c>"type": 1</c>.
    /// Getting this wrong is silent in one direction and wrong in the other: the string converter
    /// still reads a number, but it writes the member's name, and NSwag names the members of a
    /// nameless integer enum <c>_0</c>, <c>_1</c> — so a subscription's interval went out as
    /// <c>"_7"</c>.
    /// </param>
    /// <returns>The C# source for the context and the client hooks.</returns>
    public static string Generate(
        string generatedSource,
        string namespaceName,
        string contextName,
        bool stringEnums = true)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(generatedSource);
        ArgumentException.ThrowIfNullOrWhiteSpace(namespaceName);
        ArgumentException.ThrowIfNullOrWhiteSpace(contextName);

        var roots = SerializationRoots(generatedSource);
        var clients = ClientClasses(generatedSource);

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated>");
        builder.AppendLine("//     Generated by tools/EConomic.SpecConverter (json-context).");
        builder.AppendLine("//     Regenerate after running NSwag; do not edit by hand.");
        builder.AppendLine("// </auto-generated>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System.Text.Json;");
        builder.AppendLine("using System.Text.Json.Serialization;");
        builder.AppendLine();
        builder.AppendLine($"namespace {namespaceName};");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// Source-generated serialization metadata for the generated legacy clients, so the");
        builder.AppendLine("/// package stays trim- and AOT-compatible despite NSwag emitting reflection-based calls.");
        builder.AppendLine("/// </summary>");
        if (stringEnums)
        {
            // The legacy API sends enums as strings ("heading", "debit"). System.Text.Json defaults
            // to numbers, so without a string converter every response carrying one fails to
            // deserialize. UseStringEnumConverter is the source-generated, AOT-safe form but only
            // exists on net9.0+; older targets add the reflection-based converter in the hook below.
            builder.AppendLine("#if NET9_0_OR_GREATER");
            builder.AppendLine("[JsonSourceGenerationOptions(");
            builder.AppendLine("    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,");
            builder.AppendLine("    PropertyNameCaseInsensitive = true,");
            builder.AppendLine("    UseStringEnumConverter = true)]");
            builder.AppendLine("#else");
            builder.AppendLine("[JsonSourceGenerationOptions(");
            builder.AppendLine("    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,");
            builder.AppendLine("    PropertyNameCaseInsensitive = true)]");
            builder.AppendLine("#endif");
        }
        else
        {
            // The OpenAPI services declare every enumerated schema as type: integer, and the server
            // sends and accepts the number. Converting to strings here would write the name NSwag
            // invented for a nameless member.
            builder.AppendLine("[JsonSourceGenerationOptions(");
            builder.AppendLine("    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,");
            builder.AppendLine("    PropertyNameCaseInsensitive = true)]");
        }

        foreach (var root in roots)
        {
            builder.AppendLine($"[JsonSerializable(typeof({root}))]");
        }

        builder.AppendLine($"internal sealed partial class {contextName} : JsonSerializerContext;");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// Points each generated client at the source-generated resolver. NSwag declares");
        builder.AppendLine("/// <c>UpdateJsonSerializerSettings</c> as a partial hook for exactly this purpose.");
        builder.AppendLine("/// </summary>");

        foreach (var client in clients)
        {
            builder.AppendLine($"internal partial class {client}");
            builder.AppendLine("{");
            builder.AppendLine("    static partial void UpdateJsonSerializerSettings(JsonSerializerOptions settings)");
            builder.AppendLine("    {");
            if (stringEnums)
            {
                builder.AppendLine("#if !NET9_0_OR_GREATER");
                builder.AppendLine("        settings.Converters.Add(new JsonStringEnumConverter());");
                builder.AppendLine("#endif");
                builder.AppendLine();
            }

            builder.AppendLine("        // e-conomic rejects an explicit null: sending \"address\": null fails schema");
            builder.AppendLine("        // validation with \"Expected String but got Null\", so an unset optional property");
            builder.AppendLine("        // must be omitted rather than written. This has to be set on these settings, not");
            builder.AppendLine("        // only through JsonSourceGenerationOptions: those apply to the context's own");
            builder.AppendLine("        // Default instance, while the generated clients serialize through options of");
            builder.AppendLine("        // their own that merely borrow the resolver.");
            builder.AppendLine("        settings.DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull;");
            builder.AppendLine();
            builder.AppendLine($"        settings.TypeInfoResolverChain.Add({contextName}.Default);");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            builder.AppendLine();
        }

        return builder.ToString();
    }

    /// <summary>Types the generated code serializes or deserializes directly.</summary>
    /// <param name="generatedSource">Contents of the NSwag-generated file.</param>
    /// <returns>The root type names, sorted.</returns>
    public static IReadOnlyList<string> SerializationRoots(string generatedSource)
    {
        ArgumentNullException.ThrowIfNull(generatedSource);

        var roots = new SortedSet<string>(StringComparer.Ordinal);

        foreach (Match match in ResponseTypePattern().Matches(generatedSource))
        {
            roots.Add(match.Groups["type"].Value);
        }

        foreach (Match match in RequestBodyPattern().Matches(generatedSource))
        {
            roots.Add(match.Groups["type"].Value);
        }

        // The helper these calls live in is itself generic, so its own declaration
        // (ReadObjectResponseAsync<T>) matches the pattern. T is not a type to serialize.
        roots.RemoveWhere(IsGenericParameter);

        // Several generated DTOs type a free-form payload as `object` — metaData, for one. With
        // only a source-generated resolver in the chain there is no reflection fallback, so a type
        // the context does not know about fails the whole response at run time.
        roots.Add("object");

        return [.. roots];
    }

    /// <summary>The generated client classes that need the resolver hook.</summary>
    /// <param name="generatedSource">Contents of the NSwag-generated file.</param>
    /// <returns>The client class names, sorted.</returns>
    public static IReadOnlyList<string> ClientClasses(string generatedSource)
    {
        ArgumentNullException.ThrowIfNull(generatedSource);

        var clients = new SortedSet<string>(StringComparer.Ordinal);

        foreach (Match match in ClientClassPattern().Matches(generatedSource))
        {
            clients.Add(match.Groups["name"].Value);
        }

        return [.. clients];
    }

    private static bool IsGenericParameter(string name) =>
        name.Length <= 2 && name[0] is 'T' or 'U' or 'V';

    // The response type is not always a bare name: a voucher create answers with a collection, so
    // NSwag emits ReadObjectResponseAsync<System.Collections.Generic.ICollection<VoucherEntry>>.
    // Anchoring on the `response_` argument keeps the generic declaration of the helper itself out.
    [GeneratedRegex(
        @"ReadObjectResponseAsync<(?<type>[\w.]+(?:<[\w.]+>)?)>\(response_",
        RegexOptions.ExplicitCapture)]
    private static partial Regex ResponseTypePattern();

    // The body is not always the first parameter: an update takes its identifier first, as in
    // PutCustomersBycustomerNoAsync(int customerNo, CustomerPUT body, ...). Anchoring on "(" alone
    // missed every one of those, and they went unnoticed only because the payload type doubled as
    // the response type and was rooted that way. Once writes started returning the read entity,
    // that second route disappeared and every PUT failed at run time for want of metadata.
    [GeneratedRegex(@"[(,]\s*(?<type>[A-Za-z_][A-Za-z0-9_]*) body[,)]", RegexOptions.ExplicitCapture)]
    private static partial Regex RequestBodyPattern();

    [GeneratedRegex(
        @"^\s*internal partial class (?<name>[A-Za-z_][A-Za-z0-9_]*Client)\b",
        RegexOptions.ExplicitCapture | RegexOptions.Multiline)]
    private static partial Regex ClientClassPattern();
}
